//!!NODE_ROOT <section>
[.topic]
[[auto-create-node-role,auto-create-node-role.title]]
= Amazon EKS Auto Mode node IAM role
:idprefix: id_

include::../../attributes.txt[]

// write short desc

[NOTE]
====

You can't use the same role that is used to create any clusters.

====

Before you create nodes, you must create an IAM role with the following policies, or equivalent permissions: 

* xref:security-iam-awsmanpol-AmazonEKSWorkerNodeMinimalPolicy[AmazonEKSWorkerNodeMinimalPolicy]
* link:AmazonECR/latest/userguide/security-iam-awsmanpol.html#security-iam-awsmanpol-AmazonEC2ContainerRegistryPullOnly["AmazonEC2ContainerRegistryPullOnly",type="documentation"]


== Check for an existing node role

You can use the following procedure to check and see if your account already has the Amazon EKS node role.

. Open the IAM console at https://console.aws.amazon.com/iam/.
. In the left navigation pane, choose *Roles*.  
. Search the list of roles for `AmazonEKSAutoNodeRole`. If a role with one of those names doesn't exist, then see instructions in the next section to create the role. If a role that contains `AmazonEKSAutoNodeRole` does exist, then select the role to view the attached policies.
. Choose *Permissions*.
. Ensure that the required policies above are attached, or equivalent custom policies.
. Choose *Trust relationships*, and then choose  *Edit trust policy*.
. Verify that the trust relationship contains the following policy. If the trust relationship matches the following policy, choose *Cancel*. If the trust relationship doesn't match, copy the policy into the  *Edit trust policy* window and choose  *Update policy*.
+
[source,json,subs="verbatim,attributes"]
----
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "Service": "ec2.amazonaws.com"
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
----


== Creating the Amazon EKS node IAM role

You can create the node IAM role with the {aws-management-console} or the {aws} CLI.



=== {aws-management-console}
. Open the IAM console at https://console.aws.amazon.com/iam/.
. In the left navigation pane, choose *Roles*.
. On the *Roles* page, choose  *Create role*.
. On the *Select trusted entity* page, do the following:
+
.. In the *Trusted entity type* section, choose  *{aws} service*.  
.. Under *Use case*, choose  *EC2*.
.. Choose *Next*.
. On the *Add permissions* page, attach the following policies:
** xref:security-iam-awsmanpol-AmazonEKSWorkerNodeMinimalPolicy[AmazonEKSWorkerNodeMinimalPolicy]
** link:AmazonECR/latest/userguide/security-iam-awsmanpol.html#security-iam-awsmanpol-AmazonEC2ContainerRegistryPullOnly["AmazonEC2ContainerRegistryPullOnly",type="documentation"]
. On the *Name, review, and create* page, do the following:
+
.. For *Role name*, enter a unique name for your role, such as `AmazonEKSAutoNodeRole`.
.. For *Description*, replace the current text with descriptive text such as `Amazon EKS - Node role`.
.. Under *Add tags (Optional)*, add metadata to the role by attaching tags as key-value pairs. For more information about using tags in IAM, see   link:IAM/latest/UserGuide/id_tags.html[Tagging IAM resources,type="documentation"] in the _IAM User Guide_.
.. Choose *Create role*.


=== {aws} CLI

*Create the Node IAM Role*

Use the **node-trust-policy.json** file from the previous step to define which entities can assume the role. Run the following command to create the Node IAM Role:

```
aws iam create-role \
    --role-name AmazonEKSAutoNodeRole \
    --assume-role-policy-document file://node-trust-policy.json
```

*Note the Role ARN*

After creating the role, retrieve and save the ARN of the Node IAM Role. You will need this ARN in subsequent steps. Use the following command to get the ARN:

```
aws iam get-role --role-name AmazonEKSAutoNodeRole --query "Role.Arn" --output text
```

*Attach Required Policies*

Attach the following {aws} managed policies to the Node IAM Role to provide the necessary permissions:

To attach AmazonEKSWorkerNodeMinimalPolicy:

```
aws iam attach-role-policy \
    --role-name AmazonEKSAutoNodeRole \
    --policy-arn arn:aws:iam::aws:policy/AmazonEKSWorkerNodeMinimalPolicy
```

To attach AmazonEC2ContainerRegistryPullOnly:

```
aws iam attach-role-policy \
    --role-name AmazonEKSAutoNodeRole \
    --policy-arn arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryPullOnly
```

