//!!NODE_ROOT <section>
[.topic]
[[auto-cluster-iam-role,auto-cluster-iam-role.title]]
= Amazon EKS Auto Mode cluster IAM role
:idprefix: wip_

include::../../attributes.txt[]

[abstract]
--
Learn how to create and configure the required {aws} Identity and Access Management role for Amazon EKS Auto Mode clusters to automate routine tasks for storage, networking, and compute autoscaling. 
--

An Amazon EKS cluster IAM role is required for each cluster. [.noloc]`Kubernetes` clusters managed by Amazon EKS use this role to automate routine tasks for storage, networking, and compute autoscaling.

Before you can create Amazon EKS clusters, you must create an IAM role with the policies required for EKS Auto Mode. You can either attach the suggested {aws} IAM managed policies, or create custom polices with equivalent permissions. 

* xref:security-iam-awsmanpol-AmazonEKSComputePolicy[AmazonEKSComputePolicy]
* xref:security-iam-awsmanpol-AmazonEKSBlockStoragePolicy[AmazonEKSBlockStoragePolicy]
* xref:security-iam-awsmanpol-AmazonEKSLoadBalancingPolicy[AmazonEKSLoadBalancingPolicy]
* xref:security-iam-awsmanpol-AmazonEKSNetworkingPolicy[AmazonEKSNetworkingPolicy]
* xref:security-iam-awsmanpol-amazoneksclusterpolicy[AmazonEKSClusterPolicy]

== Check for an existing cluster role

You can use the following procedure to check and see if your account already has the Amazon EKS cluster role.

. Open the IAM console at https://console.aws.amazon.com/iam/.
. In the left navigation pane, choose *Roles*.  
. Search the list of roles for `AmazonEKSAutoClusterRole`. If a role that includes `AmazonEKSAutoClusterRole` doesn't exist, then see the instructions in the next section to create the role. If a role that includes `AmazonEKSAutoClusterRole` does exist, then select the role to view the attached policies.
. Choose *Permissions*.
. Ensure that the *AmazonEKSClusterPolicy* managed policy is attached to the role. If the policy is attached, your Amazon EKS cluster role is properly configured.
. Choose *Trust relationships*, and then choose  *Edit trust policy*.
. Verify that the trust relationship contains the following policy. If the trust relationship matches the following policy, choose *Cancel*. If the trust relationship doesn't match, copy the policy into the  *Edit trust policy* window and choose  *Update policy*.  
+
[source,json,subs="verbatim,attributes"]
----
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow", 
      "Principal": {
        "Service": "eks.amazonaws.com"
      },
      "Action": [
        "sts:AssumeRole",
        "sts:TagSession"
      ]
    }
  ]
}
----

[NOTE]
====
{aws} does not require the name `AmazonEKSAutoClusterRole` for this role. 
====

== Creating the Amazon EKS cluster role

You can use the {aws-management-console} or the {aws} CLI to create the cluster role.


=== {aws-management-console}

. Open the IAM console at https://console.aws.amazon.com/iam/.
. Choose *Roles*, then  *Create role*.
. Under *Trusted entity type*, select  *{aws} service*.
. From the *Use cases for other {aws} services* dropdown list, choose  *EKS*.
. Choose *EKS - Cluster* for your use case, and then choose  *Next*.
. On the *Add permissions* tab, select the policies and then choose  *Next*.
** xref:security-iam-awsmanpol-AmazonEKSComputePolicy[AmazonEKSComputePolicy]
** xref:security-iam-awsmanpol-AmazonEKSBlockStoragePolicy[AmazonEKSBlockStoragePolicy]
** xref:security-iam-awsmanpol-AmazonEKSLoadBalancingPolicy[AmazonEKSLoadBalancingPolicy]
** xref:security-iam-awsmanpol-AmazonEKSNetworkingPolicy[AmazonEKSNetworkingPolicy]
** xref:security-iam-awsmanpol-amazoneksclusterpolicy[AmazonEKSClusterPolicy]
. For *Role name*, enter a unique name for your role, such as `AmazonEKSAutoClusterRole`.
. For *Description*, enter descriptive text such as `Amazon EKS - Cluster role`.
. Choose *Create role*.


=== {aws} CLI

. Copy the following contents to a file named [.replaceable]`cluster-trust-policy.json`. 
+
[source,json,subs="verbatim,attributes"]
----
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow", 
      "Principal": {
        "Service": "eks.amazonaws.com"
      },
      "Action": [
        "sts:AssumeRole",
        "sts:TagSession"
      ]
    }
  ]
}
----
. Create the role. You can replace [.replaceable]`AmazonEKSAutoClusterRole` with any name that you choose.
+
[source,bash,subs="verbatim,attributes"]
----
aws iam create-role \
  --role-name AmazonEKSAutoClusterRole \
  --assume-role-policy-document file://"cluster-trust-policy.json"
----
. Attach the required IAM policies to the role:

**AmazonEKSClusterPolicy**:

```
aws iam attach-role-policy \
    --role-name AmazonEKSAutoClusterRole \
    --policy-arn arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
```

**AmazonEKSComputePolicy**:

```
aws iam attach-role-policy \
    --role-name AmazonEKSAutoClusterRole \
    --policy-arn arn:aws:iam::aws:policy/AmazonEKSComputePolicy
```

**AmazonEKSBlockStoragePolicy**:

```
aws iam attach-role-policy \
    --role-name AmazonEKSAutoClusterRole \
    --policy-arn arn:aws:iam::aws:policy/AmazonEKSBlockStoragePolicy
```

**AmazonEKSLoadBalancingPolicy**:

```
aws iam attach-role-policy \
    --role-name AmazonEKSAutoClusterRole \
    --policy-arn arn:aws:iam::aws:policy/AmazonEKSLoadBalancingPolicy
```

**AmazonEKSNetworkingPolicy**:

```
aws iam attach-role-policy \
    --role-name AmazonEKSAutoClusterRole \
    --policy-arn arn:aws:iam::aws:policy/AmazonEKSNetworkingPolicy
```
