//!!NODE_ROOT <section>
[.topic]
[[create-node-role,create-node-role.title]]
= Amazon EKS node IAM role

include::../../attributes.txt[]

The Amazon EKS node `kubelet` daemon makes calls to {aws} APIs on your behalf. Nodes receive permissions for these API calls through an IAM instance profile and associated policies. Before you can launch nodes and register them into a cluster, you must create an IAM role for those nodes to use when they are launched. This requirement applies to nodes launched with the Amazon EKS optimized AMI provided by Amazon, or with any other node AMIs that you intend to use. Additionally, this requirement applies to both managed node groups and self-managed nodes.

[NOTE]
====
You can't use the same role that is used to create any clusters.
====

Before you create nodes, you must create an IAM role with the following permissions:



* Permissions for the `kubelet` to describe Amazon EC2 resources in the VPC, such as provided by the link:aws-managed-policy/latest/reference/AmazonEKSWorkerNodePolicy.html[AmazonEKSWorkerNodePolicy,type="documentation"] policy. This policy also provides the permissions for the Amazon EKS Pod Identity Agent.
* Permissions for the `kubelet` to use container images from Amazon Elastic Container Registry (Amazon ECR), such as provided by the link:aws-managed-policy/latest/reference/AmazonEC2ContainerRegistryPullOnly.html[AmazonEC2ContainerRegistryPullOnly,type="documentation"] policy. The permissions to use container images from Amazon Elastic Container Registry (Amazon ECR) are required because the built-in add-ons for networking run pods that use container images from Amazon ECR.
* (Optional) Permissions for the Amazon EKS Pod Identity Agent to use the `eks-auth:AssumeRoleForPodIdentity` action to retrieve credentials for pods. If you don't use the link:aws-managed-policy/latest/reference/AmazonEKSWorkerNodePolicy.html[AmazonEKSWorkerNodePolicy,type="documentation"], then you must provide this permission in addition to the EC2 permissions to use EKS Pod Identity.`
* (Optional) If you don't use IRSA or EKS Pod Identity to give permissions to the VPC CNI pods, then you must provide  permissions for the VPC CNI on the instance role. You can use either the ` link:aws-managed-policy/latest/reference/AmazonEKS_CNI_Policy.html[AmazonEKS_CNI_Policy,type="documentation"]` managed policy (if you created your cluster with the  IPv4` family) or an <<cni-iam-role-create-ipv6-policy,IPv6 policy that you create>> (if you created your cluster with the `IPv6` family). Rather than attaching the policy to this role however, we recommend that you attach the policy to a separate role used specifically for the Amazon VPC CNI add-on. For more information about creating a separate role for the Amazon VPC CNI add-on, see <<cni-iam-role>>.


[NOTE]
====
The Amazon EC2 node groups must have a different IAM role than the Fargate profile. For more information, see <<pod-execution-role>>.
====

[[check-worker-node-role,check-worker-node-role.title]]
== Check for an existing node role

You can use the following procedure to check and see if your account already has the Amazon EKS node role.

. Open the IAM console at https://console.aws.amazon.com/iam/.
. In the left navigation pane, choose *Roles*.  
. Search the list of roles for `eksNodeRole`, `AmazonEKSNodeRole`, or `NodeInstanceRole`. If a role with one of those names doesn't exist, then see <<create-worker-node-role>> to create the role. If a role that contains `eksNodeRole`, `AmazonEKSNodeRole`, or `NodeInstanceRole` does exist, then select the role to view the attached policies.
. Choose *Permissions*.
. Ensure that the *AmazonEKSWorkerNodePolicy* and  *AmazonEC2ContainerRegistryPullOnly* managed policies are attached to the role or a custom policy is attached with the minimal permissions.
+
NOTE: If the *AmazonEKS_CNI_Policy* policy is attached to the role, we recommend removing it and attaching it to an IAM role that is mapped to the `aws-node` [.noloc]`Kubernetes` service account instead. For more information, see <<cni-iam-role>>.
. Choose *Trust relationships*, and then choose  *Edit trust policy*.
. Verify that the trust relationship contains the following policy. If the trust relationship matches the following policy, choose *Cancel*. If the trust relationship doesn't match, copy the policy into the  *Edit trust policy* window and choose  *Update policy*.
+
[source,json,subs="verbatim,attributes"]
----
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "Service": "ec2.amazonaws.com"
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
----


[[create-worker-node-role,create-worker-node-role.title]]
== Creating the Amazon EKS node IAM role

You can create the node IAM role with the {aws-management-console} or the {aws} CLI.



{aws-management-console}::
.. Open the IAM console at https://console.aws.amazon.com/iam/.
.. In the left navigation pane, choose *Roles*.
.. On the *Roles* page, choose  *Create role*.
.. On the *Select trusted entity* page, do the following:
+
... In the *Trusted entity type* section, choose  *{aws} service*.  
... Under *Use case*, choose  *EC2*.
... Choose *Next*.
.. On the *Add permissions* page, attach a custom policy or do the following:
+
... In the *Filter policies* box, enter `AmazonEKSWorkerNodePolicy`.
... Select the check box to the left of *AmazonEKSWorkerNodePolicy* in the search results.
... Choose *Clear filters*.  
... In the *Filter policies* box, enter `AmazonEC2ContainerRegistryPullOnly`.
... Select the check box to the left of *AmazonEC2ContainerRegistryPullOnly* in the search results.
+
Either the *AmazonEKS_CNI_Policy* managed policy, or an  <<cni-iam-role-create-ipv6-policy,IPv6 policy>> that you create must also be attached to either this role or to a different role that's mapped to the `aws-node` [.noloc]`Kubernetes` service account. We recommend assigning the policy to the role associated to the [.noloc]`Kubernetes` service account instead of assigning it to this role. For more information, see <<cni-iam-role>>.
... Choose *Next*.
.. On the *Name, review, and create* page, do the following:
+
... For *Role name*, enter a unique name for your role, such as `AmazonEKSNodeRole`.
... For *Description*, replace the current text with descriptive text such as `Amazon EKS - Node role`.
... Under *Add tags (Optional)*, add metadata to the role by attaching tags as key-value pairs. For more information about using tags in IAM, see   link:IAM/latest/UserGuide/id_tags.html[Tagging IAM resources,type="documentation"] in the _IAM User Guide_.
... Choose *Create role*.


{aws} CLI::
.. Run the following command to create the `node-role-trust-relationship.json` file.
+
[source,json,subs="verbatim,attributes"]
----
cat >node-role-trust-relationship.json <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "Service": "ec2.amazonaws.com"
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
EOF
----
.. Create the IAM role.
+
[source,bash,subs="verbatim,attributes"]
----
aws iam create-role \
  --role-name AmazonEKSNodeRole \
  --assume-role-policy-document file://"node-role-trust-relationship.json"
----
.. Attach two required IAM managed policies to the IAM role.
+
[source,bash,subs="verbatim,attributes"]
----
aws iam attach-role-policy \
  --policy-arn {arn-aws}iam::aws:policy/AmazonEKSWorkerNodePolicy \
  --role-name AmazonEKSNodeRole
aws iam attach-role-policy \
  --policy-arn {arn-aws}iam::aws:policy/AmazonEC2ContainerRegistryPullOnly \
  --role-name AmazonEKSNodeRole
----
.. Attach one of the following IAM policies to the IAM role depending on which IP family you created your cluster with. The policy must be attached to this role or to a role associated to the [.noloc]`Kubernetes` `aws-node` service account that's used for the [.noloc]`Amazon VPC CNI plugin for Kubernetes`. We recommend assigning the policy to the role associated to the [.noloc]`Kubernetes` service account. To assign the policy to the role associated to the [.noloc]`Kubernetes` service account, see <<cni-iam-role>>.
+
*** IPv4
+
[source,bash,subs="verbatim,attributes"]
----
aws iam attach-role-policy \
  --policy-arn {arn-aws}iam::aws:policy/AmazonEKS_CNI_Policy \
  --role-name AmazonEKSNodeRole
----
*** IPv6
+
.... Copy the following text and save it to a file named `vpc-cni-ipv6-policy.json`.
+
[source,json,subs="verbatim,attributes"]
----
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "ec2:AssignIpv6Addresses",
                "ec2:DescribeInstances",
                "ec2:DescribeTags",
                "ec2:DescribeNetworkInterfaces",
                "ec2:DescribeInstanceTypes"
            ],
            "Resource": "*"
        },
        {
            "Effect": "Allow",
            "Action": [
                "ec2:CreateTags"
            ],
            "Resource": [
                "{arn-aws}ec2:*:*:network-interface/*"
            ]
        }
    ]
}
----
.... Create the IAM policy.
+
[source,bash,subs="verbatim,attributes"]
----
aws iam create-policy --policy-name AmazonEKS_CNI_IPv6_Policy --policy-document file://vpc-cni-ipv6-policy.json
----
.... Attach the IAM policy to the IAM role. Replace [.replaceable]`111122223333` with your account ID.
+
[source,bash,subs="verbatim,attributes"]
----
aws iam attach-role-policy \
  --policy-arn {arn-aws}iam::111122223333:policy/AmazonEKS_CNI_IPv6_Policy \
  --role-name AmazonEKSNodeRole
----

