//!!NODE_ROOT <section>
include::../../attributes.txt[]
[.topic]
[[security-iam-awsmanpol,security-iam-awsmanpol.title]]
= {aws} managed policies for Amazon Elastic Kubernetes Service
:info_titleabbrev: {aws} managed policies

[abstract]
--
Learn about {aws} managed policies for Amazon EKS and recent changes to those policies.
--

An {aws} managed policy is a standalone policy that is created and administered by {aws}. {aws} managed policies are designed to provide permissions for many common use cases so that you can start assigning permissions to users, groups, and roles.

Keep in mind that {aws} managed policies might not grant least-privilege permissions for your specific use cases because they're available for all {aws} customers to use. We recommend that you reduce permissions further by defining  link:IAM/latest/UserGuide/access_policies_managed-vs-inline.html#customer-managed-policies[customer managed policies,type="documentation"] that are specific to your use cases.

You cannot change the permissions defined in {aws} managed policies. If {aws} updates the permissions defined in an {aws} managed policy, the update affects all principal identities (users, groups, and roles) that the policy is attached to. {aws} is most likely to update an {aws} managed policy when a new {aws} service is launched or new API operations become available for existing services.

For more information, see  link:IAM/latest/UserGuide/access_policies_managed-vs-inline.html#aws-managed-policies[{aws} managed policies,type="documentation"] in the _IAM User Guide_.

[[security-iam-awsmanpol-amazoneks-cni-policy,security-iam-awsmanpol-amazoneks-cni-policy.title]]
== {aws} managed policy: AmazonEKS_CNI_Policy
:info_titleabbrev: AmazonEKS_CNI_Policy

You can attach the `AmazonEKS_CNI_Policy` to your IAM entities. Before you create an Amazon EC2 node group, this policy must be attached to either the <<create-node-role,node IAM role>>, or to an IAM role that's used specifically by the [.noloc]`Amazon VPC CNI plugin for Kubernetes`. This is so that it can perform actions on your behalf. We recommend that you attach the policy to a role that's used only by the plugin. For more information, see <<managing-vpc-cni>> and <<cni-iam-role>>.

*Permissions details*

This policy includes the following permissions that allow Amazon EKS to complete the following tasks:

* *`ec2:*NetworkInterface` and `ec2:*PrivateIpAddresses`* – Allows the Amazon VPC CNI plugin to perform actions such as provisioning Elastic Network Interfaces and IP addresses for [.noloc]`Pods` to provide networking for applications that run in Amazon EKS.
* *`ec2` read actions* – Allows the Amazon VPC CNI plugin to perform actions such as describe instances and subnets to see the amount of free IP addresses in your Amazon VPC subnets. The VPC CNI can use the free IP addresses in each subnet to pick the subnets with the most free IP addresses to use when creating an elastic network interface.

To view the latest version of the JSON policy document, see   link:aws-managed-policy/latest/reference/AmazonEKS_CNI_Policy.html#AmazonEKS_CNI_Policy-json[AmazonEKS_CNI_Policy,type="documentation"] in the {aws} Managed Policy Reference Guide.

[[security-iam-awsmanpol-amazoneksclusterpolicy,security-iam-awsmanpol-amazoneksclusterpolicy.title]]
== {aws} managed policy: AmazonEKSClusterPolicy
:info_titleabbrev: AmazonEKSClusterPolicy

You can attach `AmazonEKSClusterPolicy` to your IAM entities. Before creating a cluster, you must have a <<cluster-iam-role,cluster IAM role>> with this policy attached. [.noloc]`Kubernetes` clusters that are managed by Amazon EKS make calls to other {aws} services on your behalf. They do this to manage the resources that you use with the service.

This policy includes the following permissions that allow Amazon EKS to complete the following tasks:

* *`autoscaling`* – Read and update the configuration of an Auto Scaling group. These permissions aren't used by Amazon EKS but remain in the policy for backwards compatibility.
* *`ec2`* – Work with volumes and network resources that are associated to Amazon EC2 nodes. This is required so that the [.noloc]`Kubernetes` control plane can join instances to a cluster and dynamically provision and manage Amazon EBS volumes that are requested by [.noloc]`Kubernetes` persistent volumes.  
* *`elasticloadbalancing`* – Work with Elastic Load Balancers and add nodes to them as targets. This is required so that the [.noloc]`Kubernetes` control plane can dynamically provision Elastic Load Balancers requested by [.noloc]`Kubernetes` services.
* *`iam`* – Create a service-linked role. This is required so that the [.noloc]`Kubernetes` control plane can dynamically provision Elastic Load Balancers that are requested by [.noloc]`Kubernetes` services.
* *`kms`* – Read a key from {aws} KMS. This is required for the [.noloc]`Kubernetes` control plane to support https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/[secrets encryption] of [.noloc]`Kubernetes` secrets stored in `etcd`.

To view the latest version of the JSON policy document, see   link:aws-managed-policy/latest/reference/AmazonEKSClusterPolicy.html#AmazonEKSClusterPolicy-json[AmazonEKSClusterPolicy,type="documentation"] in the {aws} Managed Policy Reference Guide.

[[security-iam-awsmanpol-amazoneksfargatepodexecutionrolepolicy,security-iam-awsmanpol-amazoneksfargatepodexecutionrolepolicy.title]]
== {aws} managed policy: AmazonEKSFargatePodExecutionRolePolicy
:info_titleabbrev: AmazonEKSFargatePodExecutionRolePolicy

You can attach `AmazonEKSFargatePodExecutionRolePolicy` to your IAM entities. Before you can create a Fargate profile, you must create a Fargate [.noloc]`Pod` execution role and attach this policy to it. For more information, see <<fargate-sg-pod-execution-role>> and <<fargate-profile>>.

This policy grants the role the permissions that provide access to other {aws} service resources that are required to run Amazon EKS [.noloc]`Pods` on Fargate.

*Permissions details*

This policy includes the following permissions that allow Amazon EKS to complete the following tasks:

* *`ecr`* – Allows Pods that are running on Fargate to pull container images that are stored in Amazon ECR.

To view the latest version of the JSON policy document, see   link:aws-managed-policy/latest/reference/AmazonEKSFargatePodExecutionRolePolicy.html#AmazonEKSFargatePodExecutionRolePolicy-json[AmazonEKSFargatePodExecutionRolePolicy,type="documentation"] in the {aws} Managed Policy Reference Guide.

[[security-iam-awsmanpol-amazoneksforfargateservicerolepolicy,security-iam-awsmanpol-amazoneksforfargateservicerolepolicy.title]]
== {aws} managed policy: AmazonEKSForFargateServiceRolePolicy
:info_titleabbrev: AmazonEKSForFargateServiceRolePolicy

You can't attach `AmazonEKSForFargateServiceRolePolicy` to your IAM entities. This policy is attached to a service-linked role that allows Amazon EKS to perform actions on your behalf. For more information, see `AWSServiceRoleforAmazonEKSForFargate`.

This policy grants necessary permissions to Amazon EKS to run Fargate tasks. The policy is only used if you have Fargate nodes.

*Permissions details*

This policy includes the following permissions that allow Amazon EKS to complete the following tasks.

* *`ec2`* – Create and delete Elastic Network Interfaces and describe Elastic Network Interfaces and resources. This is required so that the Amazon EKS Fargate service can configure the VPC networking that's required for Fargate Pods.

To view the latest version of the JSON policy document, see   link:aws-managed-policy/latest/reference/AmazonEKSForFargateServiceRolePolicy.html#AmazonEKSForFargateServiceRolePolicy-json[AmazonEKSForFargateServiceRolePolicy,type="documentation"] in the {aws} Managed Policy Reference Guide.

[[security-iam-awsmanpol-AmazonEKSComputePolicy,security-iam-awsmanpol-AmazonEKSComputePolicy.title]]
== {aws} managed policy: AmazonEKSComputePolicy
:info_titleabbrev: AmazonEKSComputePolicy

You can attach `AmazonEKSComputePolicy` to your IAM entities. You may attach this policy to your <<cluster-iam-role,cluster IAM role>> to expand the resources EKS can manage in your account.

This policy grants the permissions required for Amazon EKS to create and manage EC2 instances for the EKS cluster, as well as the necessary IAM permissions to configure EC2. 

=== Permissions details

This policy includes the following permissions that allow Amazon EKS to complete the following tasks:

* **`ec2` Permissions**:
   - `ec2:CreateFleet` and `ec2:RunInstances` - Allows creating EC2 instances and using specific EC2 resources (images, security groups, subnets) for EKS cluster nodes.
   - `ec2:CreateLaunchTemplate` - Allows creating EC2 launch templates for EKS cluster nodes.
   - The policy also includes conditions to restrict the use of these EC2 permissions to resources tagged with the EKS cluster name and other relevant tags.
   - `ec2:CreateTags` - Allows adding tags to EC2 resources created by the `CreateFleet`, `RunInstances`, and `CreateLaunchTemplate` actions.

* **`iam` Permissions**:
   - `iam:AddRoleToInstanceProfile` - Allows adding an IAM role to the EKS compute instance profile.
   - `iam:PassRole` - Allows passing the necessary IAM roles to the EC2 service.

To view the latest version of the JSON policy document, see   link:aws-managed-policy/latest/reference/AmazonEKSComputePolicy.html#AmazonEKSComputePolicy-json[AmazonEKSComputePolicy,type="documentation"] in the {aws} Managed Policy Reference Guide.

[[security-iam-awsmanpol-AmazonEKSNetworkingPolicy,security-iam-awsmanpol-AmazonEKSNetworkingPolicy.title]]
== {aws} managed policy: AmazonEKSNetworkingPolicy
:info_titleabbrev: AmazonEKSNetworkingPolicy

You can attach `AmazonEKSNetworkingPolicy` to your IAM entities. You may attach this policy to your <<cluster-iam-role,cluster IAM role>> to expand the resources EKS can manage in your account. 

This policy is designed to grant the necessary permissions for Amazon EKS to create and manage network interfaces for the EKS cluster, allowing the control plane and worker nodes to communicate and function properly.

=== Permissions details

This policy grants the following permissions to allow Amazon EKS to manage network interfaces for the cluster:

* **`ec2` Network Interface Permissions**:
   - `ec2:CreateNetworkInterface` - Allows creating EC2 network interfaces.
   - The policy includes conditions to restrict the use of this permission to network interfaces tagged with the EKS cluster name and the Kubernetes CNI node name.
   - `ec2:CreateTags` - Allows adding tags to the network interfaces created by the `CreateNetworkInterface` action.

* **`ec2` Network Interface Management Permissions**:
   - `ec2:AttachNetworkInterface`, `ec2:DetachNetworkInterface` - Allows attaching and detaching network interfaces to EC2 instances.
   - `ec2:UnassignPrivateIpAddresses`, `ec2:UnassignIpv6Addresses`, `ec2:AssignPrivateIpAddresses`, `ec2:AssignIpv6Addresses` - Allows managing the IP address assignments of the network interfaces.
   - These permissions are restricted to network interfaces tagged with the EKS cluster name.



To view the latest version of the JSON policy document, see   link:aws-managed-policy/latest/reference/AmazonEKSNetworkingPolicy.html#AmazonEKSNetworkingPolicy-json[AmazonEKSNetworkingPolicy,type="documentation"] in the {aws} Managed Policy Reference Guide.


 
[[security-iam-awsmanpol-AmazonEKSBlockStoragePolicy,security-iam-awsmanpol-AmazonEKSBlockStoragePolicy.title]]
== {aws} managed policy: AmazonEKSBlockStoragePolicy
:info_titleabbrev: AmazonEKSBlockStoragePolicy
 
You can attach `AmazonEKSBlockStoragePolicy` to your IAM entities. You may attach this policy to your <<cluster-iam-role,cluster IAM role>> to expand the resources EKS can manage in your account. 
 
This policy grants the necessary permissions for Amazon EKS to create, manage, and maintain EC2 volumes and snapshots for the EKS cluster, enabling the control plane and worker nodes to provision and use persistent storage as required by Kubernetes workloads.
 
=== Permissions details
 
This IAM policy grants the following permissions to allow Amazon EKS to manage EC2 volumes and snapshots:
 
* **`ec2` Volume Management Permissions**:
   - `ec2:AttachVolume`, `ec2:DetachVolume`, `ec2:ModifyVolume`, `ec2:EnableFastSnapshotRestores` - Allows attaching, detaching, modifying, and enabling fast snapshot restores for EC2 volumes.
   - These permissions are restricted to volumes tagged with the EKS cluster name.
   - `ec2:CreateTags` - Allows adding tags to the EC2 volumes and snapshots created by the `CreateVolume` and `CreateSnapshot` actions.
 
* **`ec2` Volume Creation Permissions**:
   - `ec2:CreateVolume` - Allows creating new EC2 volumes.
   - The policy includes conditions to restrict the use of this permission to volumes tagged with the EKS cluster name and other relevant tags.
   - `ec2:CreateSnapshot` - Allows creating new EC2 volume snapshots.
   - The policy includes conditions to restrict the use of this permission to snapshots tagged with the EKS cluster name and other relevant tags.
 
 
 
To view the latest version of the JSON policy document, see   link:aws-managed-policy/latest/reference/AmazonEKSBlockStoragePolicy.html#AmazonEKSBlockStoragePolicy-json[AmazonEKSBlockStoragePolicy,type="documentation"] in the {aws} Managed Policy Reference Guide.
 

[[security-iam-awsmanpol-AmazonEKSLoadBalancingPolicy,security-iam-awsmanpol-AmazonEKSLoadBalancingPolicy.title]]
== {aws} managed policy: AmazonEKSLoadBalancingPolicy
:info_titleabbrev: AmazonEKSLoadBalancingPolicy

You can attach `AmazonEKSLoadBalancingPolicy` to your IAM entities. You may attach this policy to your <<cluster-iam-role,cluster IAM role>> to expand the resources EKS can manage in your account. 

This IAM policy grants the necessary permissions for Amazon EKS to work with various {aws} services to manage Elastic Load Balancers (ELBs) and related resources. 

=== Permissions details

The key permissions granted by this policy are:

* **`elasticloadbalancing`**: Allows creating, modifying, and managing Elastic Load Balancers and Target Groups. This includes permissions to create, update, and delete load balancers, target groups, listeners, and rules.

* **`ec2`**: Allows creating and managing security groups, which are required for the Kubernetes control plane to join instances to a cluster and manage Amazon EBS volumes.

* **`iam`**: Allows creating a service-linked role for Elastic Load Balancing, which is required for the Kubernetes control plane to dynamically provision ELBs.

* **`kms`**: Allows reading a key from {aws} KMS, which is required for the Kubernetes control plane to support encryption of Kubernetes secrets stored in etcd.

* **`wafv2`** and **`shield`**: Allows associating and disassociating Web ACLs and creating/deleting {aws} Shield protections for the Elastic Load Balancers.

* **`cognito-idp`**, **`acm`**, and **`elasticloadbalancing`**: Grants permissions to describe user pool clients, list and describe certificates, and describe target groups, which are required for the Kubernetes control plane to manage the Elastic Load Balancers.

The policy also includes several condition checks to ensure that the permissions are scoped to the specific EKS cluster being managed, using the `eks:eks-cluster-name` tag.

To view the latest version of the JSON policy document, see   link:aws-managed-policy/latest/reference/AmazonEKSLoadBalancingPolicy.html#AmazonEKSLoadBalancingPolicy-json[AmazonEKSLoadBalancingPolicy,type="documentation"] in the {aws} Managed Policy Reference Guide.

[[security-iam-awsmanpol-amazoneksservicepolicy,security-iam-awsmanpol-amazoneksservicepolicy.title]]
== {aws} managed policy: AmazonEKSServicePolicy
:info_titleabbrev: AmazonEKSServicePolicy

You can attach `AmazonEKSServicePolicy` to your IAM entities. Clusters that were created before April 16, 2020, required you to create an IAM role and attach this policy to it. Clusters that were created on or after April 16, 2020, don't require you to create a role and don't require you to assign this policy. When you create a cluster using an IAM principal that has the `iam:CreateServiceLinkedRole` permission, the <<service-linked-role-permissions-eks,AWSServiceRoleforAmazonEKS>> service-linked role is automatically created for you. The service-linked role has the <<security-iam-awsmanpol-amazoneksservicerolepolicy,managed policy: AmazonEKSServiceRolePolicy>> attached to it.

This policy allows Amazon EKS to create and manage the necessary resources to operate Amazon EKS clusters. 

*Permissions details*

This policy includes the following permissions that allow Amazon EKS to complete the following tasks.

* *`eks`* – Update the [.noloc]`Kubernetes` version of your cluster after you initiate an update. This permission isn't used by Amazon EKS but remains in the policy for backwards compatibility.
* *`ec2`* – Work with Elastic Network Interfaces and other network resources and tags. This is required by Amazon EKS to configure networking that facilitates communication between nodes and the [.noloc]`Kubernetes` control plane. Read information about security groups. Update tags on security groups.
* *`route53`* – Associate a VPC with a hosted zone. This is required by Amazon EKS to enable private endpoint networking for your [.noloc]`Kubernetes` cluster API server.
* *`logs`* – Log events. This is required so that Amazon EKS can ship [.noloc]`Kubernetes` control plane logs to CloudWatch.
* *`iam`* – Create a service-linked role. This is required so that Amazon EKS can create the  <<service-linked-role-permissions-eks>> service-linked role on your behalf.

To view the latest version of the JSON policy document, see   link:aws-managed-policy/latest/reference/AmazonEKSServicePolicy.html#AmazonEKSServicePolicy-json[AmazonEKSServicePolicy,type="documentation"] in the {aws} Managed Policy Reference Guide.

[[security-iam-awsmanpol-amazoneksservicerolepolicy,security-iam-awsmanpol-amazoneksservicerolepolicy.title]]
== {aws} managed policy: AmazonEKSServiceRolePolicy
:info_titleabbrev: AmazonEKSServiceRolePolicy

You can't attach `AmazonEKSServiceRolePolicy` to your IAM entities. This policy is attached to a service-linked role that allows Amazon EKS to perform actions on your behalf. For more information, see <<service-linked-role-permissions-eks>>. When you create a cluster using an IAM principal that has the `iam:CreateServiceLinkedRole` permission, the <<service-linked-role-permissions-eks,AWSServiceRoleforAmazonEKS>> service-linked role is automatically created for you and this policy is attached to it.

This policy allows the service-linked role to call {aws} services on your behalf. 

*Permissions details*

This policy includes the following permissions that allow Amazon EKS to complete the following tasks.

* *`ec2`* – Create and describe Elastic Network Interfaces and Amazon EC2 instances, the cluster security group, and VPC that are required to create a cluster. For more information, see <<sec-group-reqs>>. Read information about security groups. Update tags on security groups.
* *`iam`* – List all of the managed policies that attached to an IAM role. This is required so that Amazon EKS can list and validate all managed policies and permissions required to create a cluster.
* *Associate a VPC with a hosted zone* – This is required by Amazon EKS to enable private endpoint networking for your [.noloc]`Kubernetes` cluster API server.
* *Log event* – This is required so that Amazon EKS can ship [.noloc]`Kubernetes` control plane logs to CloudWatch.
* *Put metric* – This is required so that Amazon EKS can ship [.noloc]`Kubernetes` control plane logs to CloudWatch.
* *`eks`* - Manage cluster access entries and policies, allowing fine-grained control over who can access EKS resources and what actions they can perform. This includes associating standard access policies for compute, networking, load balancing, and storage operations.
* *`elasticloadbalancing`* - Create, manage, and delete load balancers and their components (listeners, target groups, certificates) that are associated with EKS clusters. View load balancer attributes and health status.
* *`events`* - Create and manage EventBridge rules for monitoring EC2 and {aws} Health events related to EKS clusters, enabling automated responses to infrastructure changes and health alerts.
* *`iam`* - Manage EC2 instance profiles with the "eks" prefix, including creation, deletion, and role association, which is necessary for EKS node management.
* *`pricing`* & *`shield`* - Access {aws} pricing information and Shield protection status, enabling cost management and advanced security features for EKS resources.
* **Resource cleanup** - Safely delete EKS-tagged resources including volumes, snapshots, launch templates, and network interfaces during cluster cleanup operations.

To view the latest version of the JSON policy document, see   link:aws-managed-policy/latest/reference/AmazonEKSServiceRolePolicy.html#AmazonEKSServiceRolePolicy-json[AmazonEKSServiceRolePolicy,type="documentation"] in the {aws} Managed Policy Reference Guide.

[[security-iam-awsmanpol-amazoneksvpcresourcecontroller,security-iam-awsmanpol-amazoneksvpcresourcecontroller.title]]
== {aws} managed policy: AmazonEKSVPCResourceController
:info_titleabbrev: AmazonEKSVPCResourceController

You can attach the `AmazonEKSVPCResourceController` policy to your IAM identities. If you're using <<security-groups-for-pods,security groups for Pods>>, you must attach this policy to your <<cluster-iam-role,Amazon EKS cluster IAM role>> to perform actions on your behalf. 

This policy grants the cluster role permissions to manage Elastic Network Interfaces and IP addresses for nodes. 

*Permissions details*

This policy includes the following permissions that allow Amazon EKS to complete the following tasks:

* *`ec2`* – Manage Elastic Network Interfaces and IP addresses to support [.noloc]`Pod` security groups and [.noloc]`Windows` nodes.

To view the latest version of the JSON policy document, see   link:aws-managed-policy/latest/reference/AmazonEKSVPCResourceController.html#AmazonEKSVPCResourceController-json[AmazonEKSVPCResourceController,type="documentation"] in the {aws} Managed Policy Reference Guide.

[[security-iam-awsmanpol-amazoneksworkernodepolicy,security-iam-awsmanpol-amazoneksworkernodepolicy.title]]
== {aws} managed policy: AmazonEKSWorkerNodePolicy
:info_titleabbrev: AmazonEKSWorkerNodePolicy

You can attach the `AmazonEKSWorkerNodePolicy` to your IAM entities. You must attach this policy to a <<create-node-role,node IAM role>> that you specify when you create Amazon EC2 nodes that allow Amazon EKS to perform actions on your behalf. If you create a node group using `eksctl`, it creates the node IAM role and attaches this policy to the role automatically.

This policy grants Amazon EKS Amazon EC2 nodes permissions to connect to Amazon EKS clusters. 

*Permissions details*

This policy includes the following permissions that allow Amazon EKS to complete the following tasks:

* *`ec2`* – Read instance volume and network information. This is required so that [.noloc]`Kubernetes` nodes can describe information about Amazon EC2 resources that are required for the node to join the Amazon EKS cluster.
* *`eks`* – Optionally describe the cluster as part of node bootstrapping.
* *`eks-auth:AssumeRoleForPodIdentity`* – Allow retrieving credentials for EKS workloads on the node. This is required for EKS Pod Identity to function properly.

To view the latest version of the JSON policy document, see   link:aws-managed-policy/latest/reference/AmazonEKSWorkerNodePolicy.html#AmazonEKSWorkerNodePolicy-json[AmazonEKSWorkerNodePolicy,type="documentation"] in the {aws} Managed Policy Reference Guide.


[[security-iam-awsmanpol-AmazonEKSWorkerNodeMinimalPolicy,security-iam-awsmanpol-AmazonEKSWorkerNodeMinimalPolicy.title]]
== {aws} managed policy: AmazonEKSWorkerNodeMinimalPolicy
:info_titleabbrev: AmazonEKSWorkerNodeMinimalPolicy

You can attach the AmazonEKSWorkerNodeMinimalPolicy to your IAM entities. You may attach this policy to a node IAM role that you specify when you create Amazon EC2 nodes that allow Amazon EKS to perform actions on your behalf.

This policy grants Amazon EKS Amazon EC2 nodes permissions to connect to Amazon EKS clusters. This policy has fewer permissions compared to AmazonEKSWorkerNodePolicy.

*Permissions details*

This policy includes the following permissions that allow Amazon EKS to complete the following tasks:

* `eks-auth:AssumeRoleForPodIdentity` - Allow retrieving credentials for EKS workloads on the node. This is required for EKS Pod Identity to function properly.

To view the latest version of the JSON policy document, see link:aws-managed-policy/latest/reference/AmazonEKSWorkerNodeMinimalPolicy.html#AmazonEKSWorkerNodeMinimalPolicy-json["AmazonEKSWorkerNodePolicy", type="documentation"] in the {aws} Managed Policy Reference Guide.

[[security-iam-awsmanpol-awsserviceroleforamazoneksnodegroup,security-iam-awsmanpol-awsserviceroleforamazoneksnodegroup.title]]
== {aws} managed policy: AWSServiceRoleForAmazonEKSNodegroup
:info_titleabbrev: AWSServiceRoleForAmazonEKSNodegroup

You can't attach `AWSServiceRoleForAmazonEKSNodegroup` to your IAM entities. This policy is attached to a service-linked role that allows Amazon EKS to perform actions on your behalf. For more information, see <<service-linked-role-permissions-eks-nodegroups>>.

This policy grants the `AWSServiceRoleForAmazonEKSNodegroup` role permissions that allow it to create and manage Amazon EC2 node groups in your account. 

*Permissions details*

This policy includes the following permissions that allow Amazon EKS to complete the following tasks:

* *`ec2`* – Work with security groups, tags, capacity reservations, and launch templates. This is required for Amazon EKS managed node groups to enable remote access configuration and to describe capacity reservations that can be used in managed node groups. Additionally, Amazon EKS managed node groups create a launch template on your behalf. This is to configure the Amazon EC2 Auto Scaling group that backs each managed node group.
* *`iam`* – Create a service-linked role and pass a role. This is required by Amazon EKS managed node groups to manage instance profiles for the role being passed when creating a managed node group. This instance profile is used by Amazon EC2 instances launched as part of a managed node group. Amazon EKS needs to create service-linked roles for other services such as Amazon EC2 Auto Scaling groups. These permissions are used in the creation of a managed node group.
* *`autoscaling`* – Work with security Auto Scaling groups. This is required by Amazon EKS managed node groups to manage the Amazon EC2 Auto Scaling group that backs each managed node group. It's also used to support functionality such as evicting [.noloc]`Pods` when nodes are terminated or recycled during node group updates.

To view the latest version of the JSON policy document, see   link:aws-managed-policy/latest/reference/AWSServiceRoleForAmazonEKSNodegroup.html#AWSServiceRoleForAmazonEKSNodegroup-json[AWSServiceRoleForAmazonEKSNodegroup,type="documentation"] in the {aws} Managed Policy Reference Guide.

[[security-iam-awsmanpol-amazonebscsidriverservicerolepolicy,security-iam-awsmanpol-amazonebscsidriverservicerolepolicy.title]]
== {aws} managed policy: AmazonEBSCSIDriverPolicy
:info_titleabbrev: AmazonEBSCSIDriverPolicy

The `AmazonEBSCSIDriverPolicy` policy allows the Amazon EBS Container Storage Interface (CSI) driver to create, modify, attach, detach, and delete volumes on your behalf. It also grants the EBS CSI driver permissions to create and delete snapshots, and to list your instances, volumes, and snapshots.

To view the latest version of the JSON policy document, see  link:aws-managed-policy/latest/reference/AmazonEBSCSIDriverPolicy.html#AmazonEBSCSIDriverPolicy-json[AmazonEBSCSIDriverServiceRolePolicy,type="documentation"] in the {aws} Managed Policy Reference Guide.

[[security-iam-awsmanpol-amazonefscsidriverservicerolepolicy,security-iam-awsmanpol-amazonefscsidriverservicerolepolicy.title]]
== {aws} managed policy: AmazonEFSCSIDriverPolicy
:info_titleabbrev: AmazonEFSCSIDriverPolicy

The `AmazonEFSCSIDriverPolicy` policy allows the Amazon EFS Container Storage Interface (CSI) to create and delete access points on your behalf. It also grants the Amazon EFS CSI driver permissions to list your access points file systems, mount targets, and Amazon EC2 availability zones.

To view the latest version of the JSON policy document, see  link:aws-managed-policy/latest/reference/AmazonEFSCSIDriverPolicy.html#AmazonEFSCSIDriverPolicy-json[AmazonEFSCSIDriverServiceRolePolicy,type="documentation"] in the {aws} Managed Policy Reference Guide.

[[security-iam-awsmanpol-amazonekslocaloutpostclusterpolicy,security-iam-awsmanpol-amazonekslocaloutpostclusterpolicy.title]]
== {aws} managed policy: AmazonEKSLocalOutpostClusterPolicy
:info_titleabbrev: AmazonEKSLocalOutpostClusterPolicy

You can attach this policy to IAM entities. Before creating a local cluster, you must attach this policy to your  <<cluster-iam-role,cluster role>>. [.noloc]`Kubernetes` clusters that are managed by Amazon EKS make calls to other {aws} services on your behalf. They do this to manage the resources that you use with the service.

The `AmazonEKSLocalOutpostClusterPolicy` includes the following permissions:

* *`ec2` read actions* – Allows control plane instances to describe Availability Zone, route table, instance, and network interface properties.Required permissions for Amazon EC2 instances to successfully join the cluster as control plane instances.
* *`ssm`* – Allows Amazon EC2 Systems Manager connection to the control plane instance, which is used by Amazon EKS to communicate and manage the local cluster in your account.
* *`logs`* – Allows instances to push logs to Amazon CloudWatch.
* *`secretsmanager`* – Allows instances to get and delete bootstrap data for the control plane instances securely from {aws} Secrets Manager.
* *`ecr`* – Allows [.noloc]`Pods` and containers that are running on the control plane instances to pull container images that are stored in Amazon Elastic Container Registry.

To view the latest version of the JSON policy document, see   link:aws-managed-policy/latest/reference/AmazonEKSLocalOutpostClusterPolicy.html#AmazonEKSLocalOutpostClusterPolicy-json[AmazonEKSLocalOutpostClusterPolicy,type="documentation"] in the {aws} Managed Policy Reference Guide.

[[security-iam-awsmanpol-amazonekslocaloutpostservicerolepolicy,security-iam-awsmanpol-amazonekslocaloutpostservicerolepolicy.title]]
== {aws} managed policy: AmazonEKSLocalOutpostServiceRolePolicy
:info_titleabbrev: AmazonEKSLocalOutpostServiceRolePolicy

You can't attach this policy to your IAM entities. When you create a cluster using an IAM principal that has the `iam:CreateServiceLinkedRole` permission, Amazon EKS automatically creates the <<using-service-linked-roles-eks-outpost,AWSServiceRoleforAmazonEKSLocalOutpost>> service-linked role for you and attaches this policy to it. This policy allows the service-linked role to call {aws} services on your behalf for local clusters. 

The `AmazonEKSLocalOutpostServiceRolePolicy` includes the following permissions:

* *`ec2`* – Allows Amazon EKS to work with security, network, and other resources to successfully launch and manage control plane instances in your account.
* *`ssm`* – Allows Amazon EC2 Systems Manager connection to the control plane instances, which is used by Amazon EKS to communicate and manage the local cluster in your account.
* *`iam`* – Allows Amazon EKS to manage the instance profile associated with the control plane instances.
* *`secretsmanager`* - Allows Amazon EKS to put bootstrap data for the control plane instances into {aws} Secrets Manager so it can be securely referenced during instance bootstrapping.
* *`outposts`* – Allows Amazon EKS to get Outpost information from your account to successfully launch a local cluster in an Outpost.

To view the latest version of the JSON policy document, see   link:aws-managed-policy/latest/reference/AmazonEKSLocalOutpostServiceRolePolicy.html#AmazonEKSLocalOutpostServiceRolePolicy-json[AmazonEKSLocalOutpostServiceRolePolicy,type="documentation"] in the {aws} Managed Policy Reference Guide.

[[security-iam-awsmanpol-updates,security-iam-awsmanpol-updates.title]]
== Amazon EKS updates to {aws} managed policies
:info_titleabbrev: Policy updates

View details about updates to {aws} managed policies for Amazon EKS since this service began tracking these changes. For automatic alerts about changes to this page, subscribe to the RSS feed on the Amazon EKS Document history page.

[cols="1,1,1", options="header"]
|===

|Change
|Description
|Date

|Added permissions to <<security-iam-awsmanpol-amazonekslocaloutpostclusterpolicy>>
|Added `ec2:DescribeAvailabilityZones` permission to `AmazonEKSLocalOutpostClusterPolicy` so the {aws} Cloud Controller Manager on the cluster control plane can identify the Availability Zone that each node is in.
|November 21, 2024

|Added permissions to <<security-iam-awsmanpol-awsserviceroleforamazoneksnodegroup>>.
|Updated `AWSServiceRoleForAmazonEKSNodegroup` policy to allow `ec2:RebootInstances` for instances created by Amazon EKS managed node groups. Restricted the `ec2:CreateTags` permissions for Amazon EC2 resources.
|November 20, 2024

|Added permissions to <<security-iam-awsmanpol-amazoneksservicerolepolicy>>.
|EKS updated {aws} managed policy `AmazonEKSServiceRolePolicy`. Added permissions for EKS access policies, load balancer management, and automated cluster resource cleanup.
|November 16, 2024

|Introduced <<security-iam-awsmanpol-AmazonEKSComputePolicy>>.
|EKS updated {aws} managed policy `AmazonEKSComputePolicy`. Updated resource permissions for the `iam:AddRoleToInstanceProfile` action.
|November 7, 2024

|Introduced <<security-iam-awsmanpol-AmazonEKSComputePolicy>>.
|{aws} introduced the `AmazonEKSComputePolicy`.
|November 1, 2024

|Added permissions to `AmazonEKSClusterPolicy`
|Added `ec2:DescribeInstanceTopology` permission to allow Amazon EKS to attach topology information to the node as labels.
|November 1, 2024

|Introduced <<security-iam-awsmanpol-AmazonEKSBlockStoragePolicy>>.
|{aws} introduced the `AmazonEKSBlockStoragePolicy`.
|October 30, 2024

|Introduced <<security-iam-awsmanpol-AmazonEKSLoadBalancingPolicy>>.
|{aws} introduced the `AmazonEKSLoadBalancingPolicy`.
|October 30, 2024

|Added permissions to <<security-iam-awsmanpol-amazoneksservicerolepolicy,AmazonEKSServiceRolePolicy>>.
|Added `cloudwatch:PutMetricData` permissions to allow Amazon EKS to publish metrics to Amazon CloudWatch.
|October 29, 2024

|Introduced <<security-iam-awsmanpol-AmazonEKSNetworkingPolicy>>.
|{aws} introduced the `AmazonEKSNetworkingPolicy`.
|October 28, 2024

|Added permissions to `AmazonEKSServicePolicy` and `AmazonEKSServiceRolePolicy`
|Added `ec2:GetSecurityGroupsForVpc` and associated tag permissions to allow EKS to read security group information and update related tags.
|October 10, 2024

|Introduced xref:security-iam-awsmanpol-AmazonEKSWorkerNodeMinimalPolicy[AmazonEKSWorkerNodeMinimalPolicy].
|{aws} introduced the `AmazonEKSWorkerNodeMinimalPolicy`.
|October 3, 2024

|Added permissions to <<security-iam-awsmanpol-awsserviceroleforamazoneksnodegroup,AWSServiceRoleForAmazonEKSNodegroup>>.
|Added `autoscaling:ResumeProcesses` and `autoscaling:SuspendProcesses` permissions to allow Amazon EKS to suspend and resume `AZRebalance` in Amazon EKS-managed Auto Scaling groups.
|August 21, 2024

|Added permissions to <<security-iam-awsmanpol-awsserviceroleforamazoneksnodegroup,AWSServiceRoleForAmazonEKSNodegroup>>.
|Added `ec2:DescribeCapacityReservations` permission to allow Amazon EKS to describe capacity reservation in user's account. Added `autoscaling:PutScheduledUpdateGroupAction` permission to enable setting scheduled scaling on `CAPACITY_BLOCK` node groups.
|June 27, 2024

|<<security-iam-awsmanpol-amazoneks-cni-policy,AmazonEKS_CNI_Policy>> – Update to an existing policy
|Amazon EKS added new `ec2:DescribeSubnets` permissions to allow the [.noloc]`Amazon VPC CNI plugin for Kubernetes` to see the amount of free IP addresses in your Amazon VPC subnets. The VPC CNI can use the free IP addresses in each subnet to pick the subnets with the most free IP addresses to use when creating an elastic network interface.
|March 4, 2024

|<<security-iam-awsmanpol-amazoneksworkernodepolicy,AmazonEKSWorkerNodePolicy>> – Update to an existing policy
|Amazon EKS added new permissions to allow EKS Pod Identities. The Amazon EKS Pod Identity Agent uses the node role.
|November 26, 2023

|Introduced <<security-iam-awsmanpol-amazonefscsidriverservicerolepolicy,AmazonEFSCSIDriverPolicy>>.
|{aws} introduced the `AmazonEFSCSIDriverPolicy`.
|July 26, 2023

|Added permissions to <<security-iam-awsmanpol-amazoneksclusterpolicy,AmazonEKSClusterPolicy>>.
|Added `ec2:DescribeAvailabilityZones` permission to allow Amazon EKS to get the AZ details during subnet auto-discovery while creating load balancers.
|February 7, 2023

|Updated policy conditions in <<security-iam-awsmanpol-amazonebscsidriverservicerolepolicy,AmazonEBSCSIDriverPolicy>>.
|Removed invalid policy conditions with wildcard characters in the `StringLike` key field. Also added a new condition `ec2:ResourceTag/kubernetes.io/created-for/pvc/name: "*"` to `ec2:DeleteVolume`, which allows the EBS CSI driver to delete volumes created by the in-tree plugin.
|November 17, 2022

|Added permissions to <<security-iam-awsmanpol-amazonekslocaloutpostservicerolepolicy,AmazonEKSLocalOutpostServiceRolePolicy>>.
|Added `ec2:DescribeVPCAttribute`, `ec2:GetConsoleOutput` and `ec2:DescribeSecret` to allow better prerequisite validation and managed lifecycle control. Also added `ec2:DescribePlacementGroups` and `"{arn-aws}ec2:*:*:placement-group/*"` to `ec2:RunInstances` to support placement control of the control plane Amazon EC2 instances on Outposts.
|October 24, 2022

|Update Amazon Elastic Container Registry permissions in <<security-iam-awsmanpol-amazonekslocaloutpostclusterpolicy,AmazonEKSLocalOutpostClusterPolicy>>.
|Moved action `ecr:GetDownloadUrlForLayer` from all resource sections to a scoped section. Added resource `{arn-aws}ecr:*:*:repository/eks/*`. Removed resource `{arn-aws}ecr:*:*:repository/eks/eks-certificates-controller-public`. This resource is covered by the added `{arn-aws}ecr:*:*:repository/eks/*` resource.
|October 20, 2022

|Added permissions to <<security-iam-awsmanpol-amazonekslocaloutpostclusterpolicy,AmazonEKSLocalOutpostClusterPolicy>>.
|Added the `{arn-aws}ecr:*:*:repository/kubelet-config-updater` Amazon Elastic Container Registry repository so the cluster control plane instances can update some `kubelet` arguments.
|August 31, 2022

|Introduced <<security-iam-awsmanpol-amazonekslocaloutpostclusterpolicy,AmazonEKSLocalOutpostClusterPolicy>>.
|{aws} introduced the `AmazonEKSLocalOutpostClusterPolicy`.
|August 24, 2022

|Introduced <<security-iam-awsmanpol-amazonekslocaloutpostservicerolepolicy,AmazonEKSLocalOutpostServiceRolePolicy>>.
|{aws} introduced the `AmazonEKSLocalOutpostServiceRolePolicy`.
|August 23, 2022

|Introduced <<security-iam-awsmanpol-amazonebscsidriverservicerolepolicy,AmazonEBSCSIDriverPolicy>>.
|{aws} introduced the `AmazonEBSCSIDriverPolicy`.
|April 4, 2022

|Added permissions to <<security-iam-awsmanpol-amazoneksworkernodepolicy,AmazonEKSWorkerNodePolicy>>.
|Added `ec2:DescribeInstanceTypes` to enable Amazon EKS-optimized AMIs that can auto discover instance level properties.
|March 21, 2022

|Added permissions to <<security-iam-awsmanpol-awsserviceroleforamazoneksnodegroup,AWSServiceRoleForAmazonEKSNodegroup>>.
|Added `autoscaling:EnableMetricsCollection` permission to allow Amazon EKS to enable metrics collection.
|December 13, 2021

|Added permissions to <<security-iam-awsmanpol-amazoneksclusterpolicy,AmazonEKSClusterPolicy>>.
|Added `ec2:DescribeAccountAttributes`, `ec2:DescribeAddresses`, and `ec2:DescribeInternetGateways` permissions to allow Amazon EKS to create a service-linked role for a Network Load Balancer.
|June 17, 2021

|Amazon EKS started tracking changes.
|Amazon EKS started tracking changes for its {aws} managed policies.
|June 17, 2021

|===
