AWSTemplateFormatVersion: '2010-09-09'
Description: 'Amazon EKS Karpenter NodeRole'
Resources:
  TachyonNodeRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: TachyonNodeRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodeMinimalPolicy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryPullOnly
Outputs:
  RoleArn:
    Description: The role that EKS will use by default for launching instances
    Value: !GetAtt TachyonNodeRole.Arn
    Export:
      Name: !Sub "${AWS::StackName}-RoleArn"
