include::../attributes.txt[]

[.topic]
[#view-kubernetes-resources]
= View Kubernetes resources in the {aws-management-console}
:info_titleabbrev: Access cluster resources

[abstract]
--
Learn how to view Kubernetes resources in the {aws-management-console}.
--

You can view the Kubernetes resources deployed to your cluster with the {aws-management-console}. You can't view Kubernetes resources with the {aws} CLI or https://eksctl.io/[eksctl]. To view Kubernetes resources using a command-line tool, use <<install-kubectl,kubectl>>.

[NOTE]
====
To view the *Resources* tab and *Nodes* section on the *Compute* tab in the {aws-management-console}, the link:IAM/latest/UserGuide/id_roles.html#iam-term-principal[IAM principal,type="documentation"] that you're using must have specific IAM and Kubernetes permissions. For more information, see <<view-kubernetes-resources-permissions>>.
====

. Open the link:eks/home#/clusters[Amazon EKS console,type="console"].
. In the *Clusters* list, select the cluster that contains the Kubernetes resources that you want to view.
. Select the *Resources* tab.
. Select a *Resource type* group that you want to view resources for, such as *Workloads*. You see a list of resource types in that group.
. Select a resource type, such as *Deployments*, in the *Workloads* group. You see a description of the resource type, a link to the Kubernetes documentation for more information about the resource type, and a list of resources of that type that are deployed on your cluster. If the list is empty, then there are no resources of that type deployed to your cluster.
. Select a resource to view more information about it. Try the following examples:
+
** Select the *Workloads* group, select the *Deployments* resource type, and then select the *coredns* resource. When you select a resource, you are in *Structured view*, by default. For some resource types, you see a *Pods* section in *Structured view*. This section lists the Pods managed by the workload. You can select any Pod listed to view information about the Pod. Not all resource types display information in *Structured View*. If you select *Raw view* in the top right corner of the page for the resource, you see the complete JSON response from the Kubernetes API for the resource.
** Select the *Cluster* group and then select the *Nodes* resource type. You see a list of all nodes in your cluster. The nodes can be any <<eks-compute,Amazon EKS node type>>. This is the same list that you see in the *Nodes* section when you select the *Compute* tab for your cluster. Select a node resource from the list. In *Structured view*, you also see a *Pods* section. This section shows you all Pods running on the node.


[#view-kubernetes-resources-permissions]
== Required permissions

To view the *Resources* tab and *Nodes* section on the *Compute* tab in the {aws-management-console}, the link:IAM/latest/UserGuide/id_roles.html#iam-term-principal[IAM principal,type="documentation"] that you're using must have specific minimum IAM and Kubernetes permissions. You must have both IAM and Kubernetes RBAC permissions configured correctly. Complete the following steps to assign the required permissions to your IAM principals.

. Make sure that the `eks:AccessKubernetesApi`, and other necessary IAM permissions to view Kubernetes resources, are assigned to the IAM principal that you're using. For more information about how to edit permissions for an IAM principal, see link:IAM/latest/UserGuide/access_controlling.html#access_controlling-principals[Controlling access for principals,type="documentation"] in the IAM User Guide. For more information about how to edit permissions for a role, see link:IAM/latest/UserGuide/roles-managingrole-editing-console.html#roles-modify_permissions-policy[Modifying a role permissions policy (console),type="documentation"] in the IAM User Guide.
+
The following example policy includes the necessary permissions for a principal to view Kubernetes resources for all clusters in your account. Replace [.replaceable]`111122223333` with your {aws} account ID. 
+
[source,json,subs="verbatim,attributes"]
----
include::iam_snippet:6ed8ab20-4391-4d6d-831b-70710f90ec60[]
----
+
To view nodes in <<eks-connector,connected clusters>>, the <<connector-iam-role,Amazon EKS connector IAM role>> should be able to impersonate the principal in the cluster. This allows the <<eks-connector,Amazon EKS Connector>> to map the principal to a Kubernetes user.
. Configure Kubernetes RBAC permissions using EKS access entries. 
+
*What are EKS Access Entries?*
+
EKS access entries are a streamlined way to grant IAM principals (users and roles) access to your Kubernetes cluster. Instead of manually managing Kubernetes RBAC resources and the `aws-auth` ConfigMap, access entries automatically handle the mapping between IAM and Kubernetes permissions using managed policies provided by {aws}. For detailed information about access entries, see <<access-entries>>. For information about available access policies and their permissions, see link:eks/latest/userguide/access-policy-permissions.html[Access policy permissions,type="documentation"].
+
You can attach Kubernetes permissions to access entries in two ways:
+
** *Use an access policy:* Access policies are pre-defined Kubernetes permissions templates maintained by {aws}. These provide standardized permission sets for common use cases.
** *Reference a Kubernetes group:* If you associate an IAM identity with a Kubernetes group, you can create Kubernetes resources that grant the group permissions. For more information, see https://kubernetes.io/docs/reference/access-authn-authz/rbac/[Using RBAC Authorization] in the Kubernetes documentation.
+
.. Create an access entry for your IAM principal using the {aws} CLI. Replace [.replaceable]`my-cluster` with the name of your cluster. Replace [.replaceable]`111122223333` with your account ID.
+
[source,bash,subs="verbatim,attributes"]
----
aws eks create-access-entry \
    --cluster-name my-cluster \
    --principal-arn {arn-aws}iam::111122223333:role/my-console-viewer-role
----
+
An example output is as follows.
+
[source,bash,subs="verbatim,attributes"]
----
{
    "accessEntry": {
        "clusterName": "my-cluster",
        "principalArn": "{arn-aws}iam::111122223333:role/my-console-viewer-role",
        "kubernetesGroups": [],
        "accessEntryArn": "{arn-aws}eks:region-code:111122223333:access-entry/my-cluster/role/111122223333/my-console-viewer-role/abc12345-1234-1234-1234-123456789012",
        "createdAt": "2024-03-15T10:30:45.123000-07:00",
        "modifiedAt": "2024-03-15T10:30:45.123000-07:00",
        "tags": {},
        "username": "{arn-aws}iam::111122223333:role/my-console-viewer-role",
        "type": "STANDARD"
    }
}
----
+
.. Associate a policy with the access entry. For viewing Kubernetes resources, use the `AmazonEKSViewPolicy`:
+
[source,bash,subs="verbatim,attributes"]
----
aws eks associate-access-policy \
    --cluster-name my-cluster \
    --principal-arn {arn-aws}iam::111122223333:role/my-console-viewer-role \
    --policy-arn {arn-aws}eks::aws:cluster-access-policy/AmazonEKSViewPolicy \
    --access-scope type=cluster
----
+
An example output is as follows.
+
[source,bash,subs="verbatim,attributes"]
----
{
    "clusterName": "my-cluster",
    "principalArn": "{arn-aws}iam::111122223333:role/my-console-viewer-role",
    "associatedAt": "2024-03-15T10:31:15.456000-07:00"
}
----
+
For namespace-specific access, you can scope the policy to specific namespaces:
+
[source,bash,subs="verbatim,attributes"]
----
aws eks associate-access-policy \
    --cluster-name my-cluster \
    --principal-arn {arn-aws}iam::111122223333:role/my-console-viewer-role \
    --policy-arn {arn-aws}eks::aws:cluster-access-policy/AmazonEKSViewPolicy \
    --access-scope type=namespace,namespaces=default,kube-system
----
+
.. Verify the access entry was created successfully:
+
[source,bash,subs="verbatim,attributes"]
----
aws eks describe-access-entry \
    --cluster-name my-cluster \
    --principal-arn {arn-aws}iam::111122223333:role/my-console-viewer-role
----
+
.. List the associated policies to confirm the policy association:
+
[source,bash,subs="verbatim,attributes"]
----
aws eks list-associated-access-policies \
    --cluster-name my-cluster \
    --principal-arn {arn-aws}iam::111122223333:role/my-console-viewer-role
----
+
An example output is as follows.
+
[source,bash,subs="verbatim,attributes"]
----
{
    "associatedAccessPolicies": [
        {
            "policyArn": "{arn-aws}eks::aws:cluster-access-policy/AmazonEKSViewPolicy",
            "accessScope": {
                "type": "cluster"
            },
            "associatedAt": "2024-03-15T10:31:15.456000-07:00",
            "modifiedAt": "2024-03-15T10:31:15.456000-07:00"
        }
    ]
}
----

[#cloudtrail-visibility]
== CloudTrail visibility

When viewing Kubernetes resources, you will see the following operation name in your CloudTrail logs:

* `AccessKubernetesApi` - When reading or viewing resources

This CloudTrail event provides an audit trail of read access to your Kubernetes resources.

NOTE: This operation name appears in CloudTrail logs for auditing purposes only. It is not an IAM action and cannot be used in IAM policy statements. To control read access to Kubernetes resources through IAM policies, use the `eks:AccessKubernetesApi` permission as shown in the <<view-kubernetes-resources-permissions>> section.
