//!!NODE_ROOT <section>
include::../attributes.txt[]

[.topic]
[[choosing-instance-type,choosing-instance-type.title]]
= Choose an optimal Amazon EC2 node instance type
:info_doctype: section
:info_title: Choose an optimal Amazon EC2 node instance type
:info_titleabbrev: Amazon EC2 instance types
:keywords: choose, select, instance, type, family, group, max-pods, max pods, maximum pods
:info_abstract: Each Amazon EC2 instance type offers different compute, memory, storage, and network \
                capabilities.

[abstract]
--
Each Amazon EC2 instance type offers different compute, memory, storage, and network capabilities.
--

Amazon EC2 provides a wide selection of instance types for worker nodes. Each instance type offers different compute, memory, storage, and network capabilities. Each instance is also grouped in an instance family based on these capabilities. For a list, see link:AWSEC2/latest/UserGuide/instance-types.html#AvailableInstanceTypes[Available instance types,type="documentation"] in the _Amazon EC2 User Guide_. Amazon EKS releases several variations of Amazon EC2 AMIs to enable support. To make sure that the instance type you select is compatible with Amazon EKS, consider the following criteria.



* All Amazon EKS AMIs don't currently support the `g5g` and `mac` families.
* [.noloc]`Arm` and non-accelerated Amazon EKS AMIs don't support the `g3`, `g4`, `inf`, and `p` families.
* Accelerated Amazon EKS AMIs don't support the `a`, `c`, `hpc`, `m`, and `t` families.
* For Arm-based instances, Amazon Linux 2023 (AL2023) only supports instance types that use [.noloc]`Graviton2` or later processors. AL2023 doesn't support `A1` instances.

When choosing between instance types that are supported by Amazon EKS, consider the following capabilities of each type.



*Number of instances in a node group*::
In general, fewer, larger instances are better, especially if you have a lot of [.noloc]`Daemonsets`. Each instance requires API calls to the API server, so the more instances you have, the more load on the API server.


*Operating system*::
Review the supported instance types for link:AWSEC2/latest/UserGuide/instance-types.html[Linux,type="documentation"], link:AWSEC2/latest/WindowsGuide/instance-types.html[Windows,type="documentation"], and link:bottlerocket/faqs/[Bottlerocket,type="marketing"]. Before creating [.noloc]`Windows` instances, review  <<windows-support,Deploy Windows nodes on EKS clusters>>.


*Hardware architecture*::
Do you need [.noloc]`x86` or [.noloc]`Arm`? Before deploying [.noloc]`Arm` instances, review  <<arm-ami,Amazon EKS optimized Arm Amazon Linux AMIs>>. Do you need instances built on the [.noloc]`Nitro System` ( link:AWSEC2/latest/UserGuide/instance-types.html#ec2-nitro-instances[Linux,type="documentation"] or  link:AWSEC2/latest/WindowsGuide/instance-types.html#ec2-nitro-instances[Windows,type="documentation"]) or that have link:AWSEC2/latest/WindowsGuide/accelerated-computing-instances.html[Accelerated,type="documentation"] capabilities? If you need accelerated capabilities, you can only use [.noloc]`Linux` with Amazon EKS.


*Maximum number of [.noloc]`Pods`*::
Since each [.noloc]`Pod` is assigned its own IP address, the number of IP addresses supported by an instance type is a factor in determining the number of [.noloc]`Pods` that can run on the instance. To manually determine how many [.noloc]`Pods` an instance type supports, see <<determine-max-pods>>.
+`NOTE: If you're using an Amazon EKS optimized Amazon Linux 2 AMI that's `v20220406` or newer, you can use a new instance type without upgrading to the latest AMI. For these AMIs, the AMI auto-calculates the necessary `max-pods` value if it isn't listed in the https://github.com/awslabs/amazon-eks-ami/blob/main/templates/shared/runtime/eni-max-pods.txt[eni-max-pods.txt] file. Instance types that are currently in preview may not be supported by Amazon EKS by default. Values for  max-pods` for such types still need to be added to `eni-max-pods.txt` in our AMI.
+
link:ec2/nitro/[{aws} Nitro System,type="marketing"] instance types optionally support significantly more IP addresses than non-Nitro System instance types. However, not all IP addresses assigned for an instance are available to [.noloc]`Pods`. To assign a significantly larger number of IP addresses to your instances, you must have version `1.9.0` or later of the Amazon VPC CNI add-on installed in your cluster and configured appropriately. For more information, see <<cni-increase-ip-addresses>>. To assign the largest number of IP addresses to your instances, you must have version `1.10.1` or later of the Amazon VPC CNI add-on installed in your cluster and deploy the cluster with the `IPv6` family.


*IP family*::
You can use any supported instance type when using the `IPv4` family for a cluster, which allows your cluster to assign private `IPv4` addresses to your [.noloc]`Pods` and Services. But if you want to use the `IPv6` family for your cluster, then you must use link:ec2/nitro/[{aws} Nitro System,type="marketing"] instance types or bare metal instance types. Only `IPv4` is supported for [.noloc]`Windows` instances. Your cluster must be running version `1.10.1` or later of the Amazon VPC CNI add-on. For more information about using `IPv6`, see <<cni-ipv6>>. 


*Version of the Amazon VPC CNI add-on that you're running*::
The latest version of the https://github.com/aws/amazon-vpc-cni-k8s[Amazon VPC CNI plugin for Kubernetes] supports https://github.com/aws/amazon-vpc-cni-k8s/blob/master/pkg/vpc/vpc_ip_resource_limit.go[these instance types]. You may need to update your Amazon VPC CNI add-on version to take advantage of the latest supported instance types. For more information, see <<managing-vpc-cni>>. The latest version supports the latest features for use with Amazon EKS. Earlier versions don't support all features. You can view features supported by different versions in the https://github.com/aws/amazon-vpc-cni-k8s/blob/master/CHANGELOG.md[Changelog] on [.noloc]`GitHub`.


*{aws} Region that you're creating your nodes in*::
Not all instance types are available in all {aws} Regions.


*Whether you're using security groups for [.noloc]`Pods`*::
If you're using security groups for [.noloc]`Pods`, only specific instance types are supported. For more information, see <<security-groups-for-pods>>.


[[determine-max-pods,determine-max-pods.title]]
== Amazon EKS recommended maximum [.noloc]`Pods` for each Amazon EC2 instance type

Since each [.noloc]`Pod` is assigned its own IP address, the number of IP addresses supported by an instance type is a factor in determining the number of [.noloc]`Pods` that can run on the instance. Amazon EKS provides a script that you can download and run to determine the Amazon EKS recommended maximum number of [.noloc]`Pods` to run on each instance type. The script uses hardware attributes of each instance, and configuration options, to determine the maximum [.noloc]`Pods` number.  You can use the number returned in these steps to enable capabilities such as <<cni-custom-network,assigning IP addresses to Pods from a different subnet than the instance's>> and <<cni-increase-ip-addresses,significantly increasing the number of IP addresses for your instance>>. If you're using a managed node group with multiple instance types, use a value that would work for all instance types.

. Download a script that you can use to calculate the maximum number of [.noloc]`Pods` for each instance type.
+
[source,bash,subs="verbatim,attributes"]
----
curl -O https://raw.githubusercontent.com/awslabs/amazon-eks-ami/master/templates/al2/runtime/max-pods-calculator.sh
----
. Mark the script as executable on your computer.
+
[source,bash,subs="verbatim,attributes"]
----
chmod +x max-pods-calculator.sh
----
. Run the script, replacing [.replaceable]`m5.large` with the instance type that you plan to deploy and [.replaceable]`1.9.0-eksbuild.1` with your Amazon VPC CNI add-on version. To determine your add-on version, see the update procedures in <<managing-vpc-cni,Assign IPs to Pods with the Amazon VPC CNI>>.
+
[source,bash,subs="verbatim,attributes"]
----
./max-pods-calculator.sh --instance-type m5.large --cni-version 1.9.0-eksbuild.1
----
+
An example output is as follows.
+
[source,bash,subs="verbatim,attributes"]
----
29
----
+
You can add the following options to the script to see the maximum [.noloc]`Pods` supported when using optional capabilities.
+
** `--cni-custom-networking-enabled` – Use this option when you want to assign IP addresses from a different subnet than your instance's. For more information, see <<cni-custom-network>>. Adding this option to the previous script with the same example values yields `20`.
** `--cni-prefix-delegation-enabled` – Use this option when you want to assign significantly more IP addresses to each elastic network interface. This capability requires an Amazon Linux instance that run on the Nitro System and version `1.9.0` or later of the Amazon VPC CNI add-on. For more information, see <<cni-increase-ip-addresses>>. Adding this option to the previous script with the same example values yields `110`.

You can also run the script with the `--help` option to see all available options.

[NOTE]
====

The max [.noloc]`Pods` calculator script limits the return value to `110` based on https://github.com/kubernetes/community/blob/master/sig-scalability/configs-and-limits/thresholds.md[Kubernetes scalability thresholds] and recommended settings. If your instance type has greater than 30 vCPUs, this limit jumps to `250`, a number based on internal Amazon EKS scalability team testing. For more information, see the link:containers/amazon-vpc-cni-increases-pods-per-node-limits[Amazon VPC CNI plugin increases pods per node limits,type="blog"] blog post.

====