//!!NODE_ROOT <section>
include::../attributes.txt[]
[.topic]
[[delete-managed-node-group,delete-managed-node-group.title]]
= Delete a managed node group from your cluster
:info_titleabbrev: Delete

[abstract]
--
This topic describes how you can delete an Amazon EKS managed node group.
--

This topic describes how you can delete an Amazon EKS managed node group. When you delete a managed node group, Amazon EKS first sets the minimum, maximum, and desired size of your Auto Scaling group to zero. This then causes your node group to scale down.

Before each instance is terminated, Amazon EKS sends a signal to drain the [.noloc]`Pods` from that node. If the [.noloc]`Pods` haven't drained after a few minutes, Amazon EKS lets Auto Scaling continue the termination of the instance. After every instance is terminated, the Auto Scaling group is deleted.

[IMPORTANT]
====

If you delete a managed node group that uses a node IAM role that isn't used by any other managed node group in the cluster, the role is removed from the `aws-auth` `ConfigMap`. If any of the self-managed node groups in the cluster are using the same node IAM role, the self-managed nodes move to the `NotReady` status. Additionally, the cluster operation is also disrupted. To add a mapping for the role you're using only for the self-managed node groups, see <<creating-access-entries>>, if your cluster's platform version is at least minimum version listed in the prerequisites section of <<access-entries,Grant IAM users access to Kubernetes with EKS access entries>>. If your platform version is earlier than the required minimum version for access entries, you can add the entry back to the `aws-auth` `ConfigMap`. For more information, enter `eksctl create iamidentitymapping --help` in your terminal.

====

You can delete a managed node group with:

* <<eksctl-delete-managed-nodegroup>>
* <<console-delete-managed-nodegroup>>
* <<awscli-delete-managed-nodegroup>>


== `eksctl` [[eksctl-delete-managed-nodegroup]]

*Delete a managed node group with `eksctl`*

Enter the following command. Replace every [.replaceable]`example value` with your own values.

[source,bash,subs="verbatim,attributes"]
----
eksctl delete nodegroup \
  --cluster my-cluster \
  --name my-mng \
  --region region-code
----

For more options, see https://eksctl.io/usage/nodegroups/#deleting-and-draining-nodegroups[Deleting and draining nodegroups] in the `eksctl` documentation.

== {aws-management-console} [[console-delete-managed-nodegroup]]

*Delete a managed node group with {aws-management-console}*

. Open the link:eks/home#/clusters[Amazon EKS console,type="console"].
. On the *Clusters* page, choose the cluster that contains the node group to delete.
. On the selected cluster page, choose the *Compute* tab.
. In the *Node groups* section, choose the node group to delete. Then choose  *Delete*.
. In the *Delete node group* confirmation dialog box, enter the name of the node group. Then choose  *Delete*.

== {aws} CLI [[awscli-delete-managed-nodegroup]]

*Delete a managed node group with {aws} CLI*


. Enter the following command. Replace every [.replaceable]`example value` with your own values.
+
[source,bash,subs="verbatim,attributes"]
----
aws eks delete-nodegroup \
  --cluster-name my-cluster \
  --nodegroup-name my-mng \
  --region region-code
----
. Use the arrow keys on your keyboard to scroll through the response output. Press the `q` key when you're finished.

+
For more options, see the `link:cli/latest/reference/eks/delete-nodegroup.html[delete-nodegroup,type="documentation"]` command in the _{aws} CLI Command Reference_.


📝 https://github.com/search?q=repo:awsdocs/amazon-eks-user-guide+&#91;&#91;delete-managed-node-group,&type=code[Edit this page on GitHub]