//!!NODE_ROOT <section>
include::../attributes.txt[]
[.topic]
[[dl1,dl1.title]]
= Use Habana Deep Learning ([.noloc]`DL1`) workloads
:info_titleabbrev: Deep learning

[abstract]
--
Custom Amazon Linux 2 (AL2) AMIs in Amazon EKS can support deep learning workloads at scale through additional configuration and [.noloc]`Kubernetes` add-ons.  
--

Custom Amazon Linux 2 (AL2) AMIs in Amazon EKS can support deep learning workloads at scale through additional configuration and [.noloc]`Kubernetes` add-ons. This document describes the components required to set up a generic [.noloc]`Kubernetes` solution for an on-premise setup or as a baseline in a larger cloud configuration. To support this function, you will have to perform the following steps in your custom environment:



* [.noloc]`SynapaseAI(R) Software` drivers loaded on the system – These are included in the https://github.com/aws-samples/aws-habana-baseami-pipeline[AMIs available on Github].
* The [.noloc]`Habana` device plugin – A [.noloc]`DaemonSet` that allows you to automatically enable the registration of [.noloc]`Habana` devices in your [.noloc]`Kubernetes` cluster and track device health.
* Helm 3.x
* https://docs.habana.ai/en/latest/Gaudi_Kubernetes/Gaudi_Kubernetes.html#habana-mpi-operator-and-helm-chart-for-kubernetes[Helm chart to install MPI Operator].
* MPI Operator
. Create and launch a base AMI from AL2, [.noloc]`Ubuntu` 18, or [.noloc]`Ubuntu` 20.
. Follow https://docs.habana.ai/en/latest/Gaudi_Kubernetes/Gaudi_Kubernetes.html[these instructions] to set up the environment for [.noloc]`DL1`.


