//!!NODE_ROOT <section>
[.topic]
[[eks-optimized-windows-ami,eks-optimized-windows-ami.title]]
= Create nodes with optimized [.noloc]`Windows` AMIs
:info_titleabbrev: Windows

include::../attributes.txt[]

[abstract]
--
[.noloc]`Windows` Amazon EKS optimized AMIs are built on top of [.noloc]`Windows` Server 2019.
--

[.noloc]`Windows` Amazon EKS optimized AMIs are built on top of [.noloc]`Windows` Server 2019 and [.noloc]`Windows` Server 2022. They are configured to serve as the base image for Amazon EKS nodes. By default, the AMIs include the following components:

* https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/[kubelet]
* https://kubernetes.io/docs/reference/command-line-tools-reference/kube-proxy/[kube-proxy]
* https://github.com/kubernetes-sigs/aws-iam-authenticator[{aws} IAM Authenticator for Kubernetes]
* https://github.com/kubernetes-csi/csi-proxy[csi-proxy]
* https://containerd.io/[containerd]


[NOTE]
====

You can track security or privacy events for [.noloc]`Windows` Server with the https://portal.msrc.microsoft.com/en-us/security-guidance[Microsoft security update guide].

====

Amazon EKS offers AMIs that are optimized for [.noloc]`Windows` containers in the following variants:

* Amazon EKS-optimized [.noloc]`Windows` Server 2019 Core AMI
* Amazon EKS-optimized [.noloc]`Windows` Server 2019 Full AMI
* Amazon EKS-optimized [.noloc]`Windows` Server 2022 Core AMI
* Amazon EKS-optimized [.noloc]`Windows` Server 2022 Full AMI


[IMPORTANT]
====

* The Amazon EKS-optimized [.noloc]`Windows` Server [.noloc]`20H2` Core AMI is deprecated. No new versions of this AMI will be released.
* To ensure that you have the latest security updates by default, Amazon EKS maintains optimized [.noloc]`Windows` AMIs for the last 4 months. Each new AMI will be available for 4 months from the time of initial release. After this period, older AMIs are made private and are no longer accessible. We encourage using the latest AMIs to avoid security vulnerabilities and losing access to older AMIs which have reached the end of their supported lifetime. While we can't guarantee that we can provide access to AMIs that have been made private, you can request access by filing a ticket with {aws} Support.

====

[[windows-ami-release-calendar,windows-ami-release-calendar.title]]
== Release calendar

The following table lists the release and end of support dates for [.noloc]`Windows` versions on Amazon EKS. If an end date is blank, it's because the version is still supported.

[cols="1,1,1", options="header"]
|===
|Windows version
|Amazon EKS release
|Amazon EKS end of support


|[.noloc]`Windows` Server 2022 Core
|[.noloc]`10/17/2022`
|

|[.noloc]`Windows` Server 2022 Full
|[.noloc]`10/17/2022`
|

|[.noloc]`Windows` Server [.noloc]`20H2` Core
|[.noloc]`8/12/2021`
|[.noloc]`8/9/2022`

|[.noloc]`Windows` Server 2004 Core
|[.noloc]`8/19/2020`
|[.noloc]`12/14/2021`

|[.noloc]`Windows` Server 2019 Core
|[.noloc]`10/7/2019`
|

|[.noloc]`Windows` Server 2019 Full
|[.noloc]`10/7/2019`
|

|[.noloc]`Windows` Server 1909 Core
|[.noloc]`10/7/2019`
|[.noloc]`12/8/2020`
|===

[[bootstrap-script-configuration-parameters,bootstrap-script-configuration-parameters.title]]
== Bootstrap script configuration parameters

When you create a [.noloc]`Windows` node, there's a script on the node that allows for configuring different parameters. Depending on your setup, this script can be found on the node at a location similar to: `C:\Program Files\Amazon\EKS\Start-EKSBootstrap.ps1`. You can specify custom parameter values by specifying them as arguments to the bootstrap script. For example, you can update the user data in the launch template. For more information, see <<launch-template-user-data>>.

The script includes the following command-line parameters:

* `-EKSClusterName` – Specifies the Amazon EKS cluster name for this worker node to join.
* `-KubeletExtraArgs` – Specifies extra arguments for `kubelet` (optional).
* `-KubeProxyExtraArgs` – Specifies extra arguments for `kube-proxy` (optional).
* `-APIServerEndpoint` – Specifies the Amazon EKS cluster API server endpoint (optional). Only valid when used with `-Base64ClusterCA`. Bypasses calling `Get-EKSCluster`.
* `-Base64ClusterCA` – Specifies the base64 encoded cluster CA content (optional). Only valid when used with `-APIServerEndpoint`. Bypasses calling `Get-EKSCluster`.
* `-DNSClusterIP` – Overrides the IP address to use for DNS queries within the cluster (optional). Defaults to `10.100.0.10` or `172.20.0.10` based on the IP address of the primary interface.
* `-ServiceCIDR` – Overrides the [.noloc]`Kubernetes` service IP address range from which cluster services are addressed. Defaults to `172.20.0.0/16` or `10.100.0.0/16` based on the IP address of the primary interface.
* `-ExcludedSnatCIDRs` – A list of `IPv4` CIDRs to exclude from Source Network Address Translation (SNAT). This means that the pod private IP which is VPC addressable wouldn't be translated to the IP address of the instance ENI's primary `IPv4` address for outbound traffic. By default, the `IPv4` CIDR of the VPC for the Amazon EKS [.noloc]`Windows` node is added. Specifying CIDRs to this parameter also additionally excludes the specified CIDRs. For more information, see <<external-snat>>.

In addition to the command line parameters, you can also specify some environment variable parameters. When specifying a command line parameter, it takes precedence over the respective environment variable. The environment variable(s) should be defined as machine (or system) scoped as the bootstrap script will only read machine-scoped variables.

The script takes into account the following environment variables:

* `SERVICE_IPV4_CIDR` – Refer to the `ServiceCIDR` command line parameter for the definition. 
* `EXCLUDED_SNAT_CIDRS` – Should be a comma separated string. Refer to the `ExcludedSnatCIDRs` command line parameter for the definition.


[[ad-and-gmsa-support,ad-and-gmsa-support.title]]
=== [.noloc]`gMSA` authentication support

Amazon EKS Windows [.noloc]`Pods` allow different types of group Managed Service Account ([.noloc]`gMSA`) authentication.

* Amazon EKS supports [.noloc]`Active Directory` domain identities for authentication. For more information on domain-joined [.noloc]`gMSA`, see link:containers/windows-authentication-on-amazon-eks-windows-pods[Windows Authentication on Amazon EKS Windowspods,type="blog"] on the {aws} blog.
* Amazon EKS offers a plugin that enables non-domain-joined [.noloc]`Windows` nodes to retrieve [.noloc]`gMSA` credentials with a portable user identity. For more information on domainless [.noloc]`gMSA`, see link:containers/domainless-windows-authentication-for-amazon-eks-windows-pods[Domainless Windows Authentication for Amazon EKS Windowspods,type="blog"] on the {aws} blog.


[[windows-cached-container-images,windows-cached-container-images.title]]
== Cached container images

Amazon EKS Windows optimized AMIs have certain container images cached for the `containerd` runtime. Container images are cached when building custom AMIs using Amazon-managed build components. For more information, see <<custom-windows-ami-build-component>>.

The following cached container images are for the `containerd` runtime:

* `amazonaws.com/eks/pause-windows`
* `mcr.microsoft.com/windows/nanoserver`
* `mcr.microsoft.com/windows/servercore`

[[windows-more-information,windows-more-information.title]]
== More information

For more information about using Amazon EKS optimized [.noloc]`Windows` AMIs, see the following sections:

* For details on running workloads on Amazon EKS optimized accelerated Windows AMIs, see <<ml-eks-windows-optimized-ami>>.
* To use [.noloc]`Windows` with managed node groups, see <<managed-node-groups>>.
* To launch self-managed [.noloc]`Windows` nodes, see <<launch-windows-workers>>.
* For version information, see <<eks-ami-versions-windows>>.
* To retrieve the latest IDs of the Amazon EKS optimized [.noloc]`Windows` AMIs, see <<retrieve-windows-ami-id>>.
* To use Amazon EC2 Image Builder to create custom Amazon EKS optimized [.noloc]`Windows` AMIs, see <<eks-custom-ami-windows>>.
* For best practices, see https://aws.github.io/aws-eks-best-practices/windows/docs/ami/[Amazon EKS optimized Windows AMI management] in the _EKS Best Practices Guide_.

include::self-managed-windows-server-2022.adoc[leveloffset=+1]

include::eks-ami-versions-windows.adoc[leveloffset=+1]

include::retrieve-windows-ami-id.adoc[leveloffset=+1]

include::eks-custom-ami-windows.adoc[leveloffset=+1]


📝 https://github.com/search?q=repo:awsdocs/amazon-eks-user-guide+&#91;&#91;eks-optimized-windows-ami,&type=code[Edit this page on GitHub]