//!!NODE_ROOT <chapter>
[[eks-compute,eks-compute.title]]
= Manage compute resources by using nodes
:doctype: book
:sectnums:
:toc: left
:icons: font
:experimental:
:idprefix:
:idseparator: -
:sourcedir: .
:info_doctype: chapter
:info_title: Manage compute resources by using nodes
:info_titleabbrev: Manage compute
:keywords: nodes, node groups
:info_abstract: Your Amazon EKS cluster can schedule Pods on any combination of self-managed nodes, Amazon EKS managed node groups, and Fargate in the {aws} Cloud and hybrid nodes on-premises.

include::../attributes.txt[]

[abstract]
--
Your Amazon EKS cluster can schedule [.noloc]`Pods` on any combination of self-managed nodes, Amazon EKS managed node groups, Fargate, and Amazon EKS Hybrid Nodes in the {aws} Cloud and hybrid nodes on-premises.
--

A [.noloc]`Kubernetes` node is a machine that runs containerized applications. Each node has the following components:

* *https://kubernetes.io/docs/setup/production-environment/container-runtimes/[Container runtime]* – Software that's responsible for running the containers.
* *https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/[kubelet]* – Makes sure that containers are healthy and running within their associated [.noloc]`Pod`.
* *https://kubernetes.io/docs/reference/command-line-tools-reference/kube-proxy/[kube-proxy]* – Maintains network rules that allow communication to your [.noloc]`Pods`.

For more information, see https://kubernetes.io/docs/concepts/architecture/nodes/[Nodes] in the [.noloc]`Kubernetes` documentation.

Your Amazon EKS cluster can schedule [.noloc]`Pods` on any combination of <<automode, EKS Auto Mode managed nodes>>, <<worker,self-managed nodes>>, <<managed-node-groups,Amazon EKS managed node groups>>, <<fargate,{aws} Fargate>>, and <<hybrid-nodes-overview,Amazon EKS Hybrid Nodes>>. To learn more about nodes deployed in your cluster, see <<view-kubernetes-resources>>.

[IMPORTANT]
====

{aws} Fargate with Amazon EKS isn't available in {aws} GovCloud (US-East) and {aws} GovCloud (US-West).
Amazon EKS Hybrid Nodes isn't available in {aws} GovCloud Regions and China Regions.

====

[NOTE]
====

Excluding hybrid nodes, nodes must be in the same VPC as the subnets you selected when you created the cluster. However, the nodes don't have to be in the same subnets.

====

== Compare compute options


The following table provides several criteria to evaluate when deciding which options best meet your requirements.

[NOTE]
====

[.noloc]`Bottlerocket` has some specific differences from the general information in this table. For more information, see the [.noloc]`Bottlerocket` https://github.com/bottlerocket-os/bottlerocket/blob/develop/README.md[documentation] on [.noloc]`GitHub`.

====


include::compute-table.adoc[]

include::managed-node-groups.adoc[leveloffset=+1]

include::worker.adoc[leveloffset=+1]

include::fargate.adoc[leveloffset=+1]

include::choosing-instance-type.adoc[leveloffset=+1]

include::eks-optimized-amis.adoc[leveloffset=+1]

include::hybrid-nodes.adoc[leveloffset=+1]
