//!!NODE_ROOT <section>
include::../attributes.txt[]
[.topic]
[[fargate-getting-started,fargate-getting-started.title]]
= Get started with {aws} Fargate for your cluster
:info_titleabbrev: Get started

[abstract]
--
This topic describes how to get started running [.noloc]`Pods` on {aws} Fargate with your Amazon EKS cluster.
--

[IMPORTANT]
====

{aws} Fargate with Amazon EKS isn't available in {aws} GovCloud (US-East) and {aws} GovCloud (US-West).

====

This topic describes how to get started running [.noloc]`Pods` on {aws} Fargate with your Amazon EKS cluster.

If you restrict access to the public endpoint of your cluster using CIDR blocks, we recommend that you also enable private endpoint access. This way, Fargate [.noloc]`Pods` can communicate with the cluster. Without the private endpoint enabled, the CIDR blocks that you specify for public access must include the outbound sources from your VPC. For more information, see <<cluster-endpoint>>. 

.Prerequisite
An existing cluster. If you don't already have an Amazon EKS cluster, see <<getting-started>>.

[[fargate-gs-check-compatibility,fargate-gs-check-compatibility.title]]
== Step 1: Ensure that existing nodes can communicate with Fargate [.noloc]`Pods`

If you're working with a new cluster with no nodes, or a cluster with only managed node groups (see <<managed-node-groups>>), you can skip to <<fargate-sg-pod-execution-role>>.

Assume that you're working with an existing cluster that already has nodes that are associated with it. Make sure that [.noloc]`Pods` on these nodes can communicate freely with the [.noloc]`Pods` that are running on Fargate. [.noloc]`Pods` that are running on Fargate are automatically configured to use the cluster security group for the cluster that they're associated with. Ensure that any existing nodes in your cluster can send and receive traffic to and from the cluster security group.  Managed node groups are automatically configured to use the cluster security group as well, so you don't need to modify or check them for this compatibility (see <<managed-node-groups>>).

For existing node groups that were created with `eksctl` or the Amazon EKS managed {aws} CloudFormation templates, you can add the cluster security group to the nodes manually. Or, alternatively, you can modify the Auto Scaling group launch template for the node group to attach the cluster security group to the instances. For more information, see  link:vpc/latest/userguide/VPC_SecurityGroups.html#SG_Changing_Group_Membership[Changing an instance's security groups,type="documentation"] in the _Amazon VPC User Guide_.

You can check for a security group for your cluster in the {aws-management-console} under the *Networking* section for the cluster. Or, you can do this using the following {aws} CLI command. When using this command, replace [.replaceable]`my-cluster` with the name of your cluster.

[source,bash,subs="verbatim,attributes"]
----
aws eks describe-cluster --name my-cluster --query cluster.resourcesVpcConfig.clusterSecurityGroupId
----


[[fargate-sg-pod-execution-role,fargate-sg-pod-execution-role.title]]
== Step 2: Create a Fargate [.noloc]`Pod` execution role

When your cluster creates [.noloc]`Pods` on {aws} Fargate, the components that run on the Fargate infrastructure must make calls to {aws} APIs on your behalf. The Amazon EKS [.noloc]`Pod` execution role provides the IAM permissions to do this. To create an {aws} Fargate [.noloc]`Pod` execution role, see <<pod-execution-role>>.

[NOTE]
====

If you created your cluster with `eksctl` using the `--fargate` option, your cluster already has a [.noloc]`Pod` execution role that you can find in the IAM console with the pattern `eksctl-my-cluster-FargatePodExecutionRole-ABCDEFGHIJKL`. Similarly, if you use `eksctl` to create your Fargate profiles, `eksctl` creates your [.noloc]`Pod` execution role if one isn't already created.

====

[[fargate-gs-create-profile,fargate-gs-create-profile.title]]
== Step 3: Create a Fargate profile for your cluster

Before you can schedule [.noloc]`Pods` that are running on Fargate in your cluster, you must define a Fargate profile that specifies which [.noloc]`Pods` use Fargate when they're launched. For more information, see <<fargate-profile>>.

[NOTE]
====

If you created your cluster with `eksctl` using the `--fargate` option, then a Fargate profile is already created for your cluster with selectors for all [.noloc]`Pods` in the `kube-system` and `default` namespaces. Use the following procedure to create Fargate profiles for any other namespaces you would like to use with Fargate.

====

You can create a Fargate profile using either of these tools:

* <<eksctl_fargate_profile_create>>
* <<console_fargate_profile_create>>

=== `eksctl` [[eksctl_fargate_profile_create]]

This procedure requires `eksctl` version `{eksctl-min-version}` or later. You can check your version with the following command:

[source,bash,subs="verbatim,attributes"]
----
eksctl version
----

For instructions on how to install or upgrade `eksctl`, see https://eksctl.io/installation[Installation] in the `eksctl` documentation.

*To create a Fargate profile with `eksctl`*

Create your Fargate profile with the following `eksctl` command, replacing every [.replaceable]`example value` with your own values. You're required to specify a namespace. However, the `--labels` option isn't required.

[source,bash,subs="verbatim,attributes"]
----
eksctl create fargateprofile \
    --cluster my-cluster \
    --name my-fargate-profile \
    --namespace my-kubernetes-namespace \
    --labels key=value
----

You can use certain wildcards for [.replaceable]`my-kubernetes-namespace` and [.replaceable]`key=value` labels. For more information, see <<fargate-profile-wildcards>>.

=== {aws-management-console} [[console_fargate_profile_create]]

*To create a Fargate profile with {aws-management-console}*

. Open the link:eks/home#/clusters[Amazon EKS console,type="console"].
. Choose the cluster to create a Fargate profile for.
. Choose the *Compute* tab.
. Under *Fargate profiles*, choose  *Add Fargate profile*.
. On the *Configure Fargate profile* page, do the following:
+
.. For *Name*, enter a name for your Fargate profile. The name must be unique.
.. For *Pod execution role*, choose the [.noloc]`Pod` execution role to use with your Fargate profile. Only the IAM roles with the `eks-fargate-pods.amazonaws.com` service principal are shown. If you don't see any roles listed, you must create one. For more information, see <<pod-execution-role>>.
.. Modify the selected *Subnets* as needed.
+
NOTE: Only private subnets are supported for [.noloc]`Pods` that are running on Fargate.
.. For *Tags*, you can optionally tag your Fargate profile. These tags don't propagate to other resources that are associated with the profile such as [.noloc]`Pods`.
.. Choose *Next*.
. On the *Configure [.noloc]`Pod` selection* page, do the following:
+
.. For *Namespace*, enter a namespace to match for [.noloc]`Pods`.
+
*** You can use specific namespaces to match, such as `kube-system` or `default`.
*** You can use certain wildcards (for example, `prod-*`) to match multiple namespaces (for example, `prod-deployment` and `prod-test`). For more information, see <<fargate-profile-wildcards>>.
.. (Optional) Add [.noloc]`Kubernetes` labels to the selector. Specifically add them to the one that the [.noloc]`Pods` in the specified namespace need to match.
+
*** You can add the label `infrastructure: fargate` to the selector so that only [.noloc]`Pods` in the specified namespace that also have the `infrastructure: fargate` [.noloc]`Kubernetes` label match the selector.
*** You can use certain wildcards (for example, `key?: value?`) to match multiple namespaces (for example, `keya: valuea` and `keyb: valueb`). For more information, see <<fargate-profile-wildcards>>.
.. Choose *Next*.
. On the *Review and create* page, review the information for your Fargate profile and choose  *Create*.


[[fargate-gs-coredns,fargate-gs-coredns.title]]
== Step 4: Update [.noloc]`CoreDNS`

By default, [.noloc]`CoreDNS` is configured to run on Amazon EC2 infrastructure on Amazon EKS clusters. If you want to  _only_ run your [.noloc]`Pods` on Fargate in your cluster, complete the following steps.

[NOTE]
====

If you created your cluster with `eksctl` using the `--fargate` option, then you can skip to <<fargate-gs-next-steps>>.

====
. Create a Fargate profile for [.noloc]`CoreDNS` with the following command. Replace [.replaceable]`my-cluster` with your cluster name, [.replaceable]`111122223333` with your account ID, [.replaceable]`AmazonEKSFargatePodExecutionRole` with the name of your [.noloc]`Pod` execution role, and [.replaceable]`0000000000000001`, [.replaceable]`0000000000000002`, and [.replaceable]`0000000000000003` with the IDs of your private subnets. If you don't have a [.noloc]`Pod` execution role, you must create one first (see <<fargate-sg-pod-execution-role>>).
+
IMPORTANT: The role ARN can't include a  link:IAM/latest/UserGuide/reference_identifiers.html#identifiers-friendly-names[path,type="documentation"] other than `/`. For example, if the name of your role is `development/apps/my-role`, you need to change it to `my-role` when specifying the ARN for the role. The format of the role ARN must be `{arn-aws}iam::111122223333:role/role-name`.
+
[source,bash,subs="verbatim,attributes"]
----
aws eks create-fargate-profile \
    --fargate-profile-name coredns \
    --cluster-name my-cluster \
    --pod-execution-role-arn {arn-aws}iam::111122223333:role/AmazonEKSFargatePodExecutionRole \
    --selectors namespace=kube-system,labels={k8s-app=kube-dns} \
    --subnets subnet-0000000000000001 subnet-0000000000000002 subnet-0000000000000003
----
. Run the following command to remove the `eks.amazonaws.com/compute-type : ec2` annotation from the [.noloc]`CoreDNS` [.noloc]`Pods`.
+
[source,bash,subs="verbatim,attributes"]
----
kubectl patch deployment coredns \
    -n kube-system \
    --type json \
    -p='[{"op": "remove", "path": "/spec/template/metadata/annotations/eks.amazonaws.com~1compute-type"}]'
----


[[fargate-gs-next-steps,fargate-gs-next-steps.title]]
== Next steps

* You can start migrating your existing applications to run on Fargate with the following workflow.
+
.. <<create-fargate-profile>> that matches your application's [.noloc]`Kubernetes` namespace and [.noloc]`Kubernetes` labels.
.. Delete and re-create any existing [.noloc]`Pods` so that they're scheduled on Fargate. For example, the following command triggers a rollout of the `coredns` deployment. You can modify the namespace and deployment type to update your specific [.noloc]`Pods`.
+
[source,bash,subs="verbatim,attributes"]
----
kubectl rollout restart -n kube-system deployment coredns
----
* Deploy the <<alb-ingress>> to allow Ingress objects for your [.noloc]`Pods` running on Fargate.
* You can use the <<vertical-pod-autoscaler>> to set the initial correct size of CPU and memory for your Fargate [.noloc]`Pods`, and then use the  <<horizontal-pod-autoscaler>> to scale those [.noloc]`Pods`. If you want the Vertical Pod Autoscaler to automatically re-deploy [.noloc]`Pods` to Fargate with higher CPU and memory combinations, set the Vertical Pod Autoscaler's mode to either `Auto` or `Recreate`. This is to ensure correct functionality. For more information, see the https://github.com/kubernetes/autoscaler/tree/master/vertical-pod-autoscaler#quick-start[Vertical Pod Autoscaler] documentation on [.noloc]`GitHub`.
* You can set up the link:otel[{aws} Distro for OpenTelemetry,type="marketing"] (ADOT) collector for application monitoring by following link:AmazonCloudWatch/latest/monitoring/Container-Insights-EKS-otel.html[these instructions,type="documentation"].


📝 https://github.com/search?q=repo:awsdocs/amazon-eks-user-guide+&#91;&#91;fargate-getting-started,&type=code[Edit this page on GitHub]