//!!NODE_ROOT <section>
include::../attributes.txt[]

[.topic]
[[fargate,fargate.title]]
= Simplify compute management with {aws} Fargate
:info_doctype: section
:info_title: Simplify compute management with {aws} Fargate
:info_titleabbrev: {aws} Fargate
:keywords: Fargate, nodes
:info_abstract: This topic discusses using Amazon EKS to run Kubernetes Pods on {aws} Fargate.

[abstract]
--
This topic discusses using Amazon EKS to run [.noloc]`Kubernetes` [.noloc]`Pods` on {aws} Fargate.
--

[IMPORTANT]
====

{aws} Fargate with Amazon EKS isn't available in {aws} GovCloud (US-East) and {aws} GovCloud (US-West).

====

This topic discusses using Amazon EKS to run [.noloc]`Kubernetes` [.noloc]`Pods` on {aws} Fargate. Fargate is a technology that provides on-demand, right-sized compute capacity for link:what-are-containers[containers,type="marketing"]. With Fargate, you don't have to provision, configure, or scale groups of virtual machines on your own to run containers. You also don't need to choose server types, decide when to scale your node groups, or optimize cluster packing.

You can control which [.noloc]`Pods` start on Fargate and how they run with  <<fargate-profile,Fargate profiles>>. Fargate profiles are defined as part of your Amazon EKS cluster. Amazon EKS integrates [.noloc]`Kubernetes` with Fargate by using controllers that are built by {aws} using the upstream, extensible model provided by [.noloc]`Kubernetes`. These controllers run as part of the Amazon EKS managed [.noloc]`Kubernetes` control plane and are responsible for scheduling native [.noloc]`Kubernetes` [.noloc]`Pods` onto Fargate. The Fargate controllers include a new scheduler that runs alongside the default [.noloc]`Kubernetes` scheduler in addition to several mutating and validating admission controllers. When you start a [.noloc]`Pod` that meets the criteria for running on Fargate, the Fargate controllers that are running in the cluster recognize, update, and schedule the [.noloc]`Pod` onto Fargate.

This topic describes the different components of [.noloc]`Pods` that run on Fargate, and calls out special considerations for using Fargate with Amazon EKS.

[[fargate-considerations,fargate-considerations.title]]
= {aws} Fargate considerations

Here are some things to consider about using Fargate on Amazon EKS.



* Each [.noloc]`Pod` that runs on Fargate has its own isolation boundary. They don't share the underlying kernel, CPU resources, memory resources, or elastic network interface with another [.noloc]`Pod`.
* Network Load Balancers and Application Load Balancers (ALBs) can be used with Fargate with IP targets only. For more information, see <<network-load-balancer>> and <<alb-ingress>>. 
* Fargate exposed services only run on target type IP mode, and not on node IP mode. The recommended way to check the connectivity from a service running on a managed node and a service running on Fargate is to connect via service name.
* Pods must match a Fargate profile at the time that they're scheduled to run on Fargate. Pods that don't match a Fargate profile might be stuck as `Pending`. If a matching Fargate profile exists, you can delete pending [.noloc]`Pods` that you have created to reschedule them onto Fargate.
* Daemonsets aren't supported on Fargate. If your application requires a daemon, reconfigure that daemon to run as a sidecar container in your [.noloc]`Pods`.
* Privileged containers aren't supported on Fargate.
* Pods running on Fargate can't specify `HostPort` or `HostNetwork` in the [.noloc]`Pod` manifest.
* The default `nofile` and `nproc` soft limit is 1024 and the hard limit is 65535 for Fargate [.noloc]`Pods`.
* GPUs aren't currently available on Fargate.
* Pods that run on Fargate are only supported on private subnets (with NAT gateway access to {aws} services, but not a direct route to an Internet Gateway), so your cluster's VPC must have private subnets available. For clusters without outbound internet access, see <<private-clusters>>.
* You can use the <<vertical-pod-autoscaler,Adjust pod resources with Vertical Pod Autoscaler>> to set the initial correct size of CPU and memory for your Fargate [.noloc]`Pods`, and then use the  <<horizontal-pod-autoscaler,Scale pod deployments with Horizontal Pod Autoscaler>> to scale those [.noloc]`Pods`. If you want the Vertical Pod Autoscaler to automatically re-deploy [.noloc]`Pods` to Fargate with larger CPU and memory combinations, set the mode for the Vertical Pod Autoscaler to either `Auto` or `Recreate` to ensure correct functionality. For more information, see the https://github.com/kubernetes/autoscaler/tree/master/vertical-pod-autoscaler#quick-start[Vertical Pod Autoscaler] documentation on [.noloc]`GitHub`.
* DNS resolution and DNS hostnames must be enabled for your VPC. For more information, see  link:vpc/latest/userguide/vpc-dns.html#vpc-dns-updating[Viewing and updating DNS support for your VPC,type="documentation"].
* Amazon EKS Fargate adds defense-in-depth for [.noloc]`Kubernetes` applications by isolating each Pod within a Virtual Machine (VM). This VM boundary prevents access to host-based resources used by other Pods in the event of a container escape, which is a common method of attacking containerized applications and gain access to resources outside of the container.
+
Using Amazon EKS doesn't change your responsibilities under the <<security,shared responsibility model>>. You should carefully consider the configuration of cluster security and governance controls. The safest way to isolate an application is always to run it in a separate cluster.
* Fargate profiles support specifying subnets from VPC secondary CIDR blocks. You might want to specify a secondary CIDR block. This is because there's a limited number of IP addresses available in a subnet. As a result, there's also a limited number of [.noloc]`Pods` that can be created in the cluster. By using different subnets for [.noloc]`Pods`, you can increase the number of available IP addresses. For more information, see   link:vpc/latest/userguide/VPC_Subnets.html#vpc-resize[Adding IPv4 CIDR blocks to a VPC.,type="documentation"]
* The Amazon EC2 instance metadata service (IMDS) isn't available to [.noloc]`Pods` that are deployed to Fargate nodes. If you have [.noloc]`Pods` that are deployed to Fargate that need IAM credentials, assign them to your [.noloc]`Pods` using  <<iam-roles-for-service-accounts,IAM roles for service accounts>>. If your [.noloc]`Pods` need access to other information available through IMDS, then you must hard code this information into your [.noloc]`Pod` spec. This includes the {aws} Region or Availability Zone that a [.noloc]`Pod` is deployed to.
* You can't deploy Fargate [.noloc]`Pods` to {aws} Outposts, {aws} Wavelength, or {aws} Local Zones.
* Amazon EKS must periodically patch Fargate [.noloc]`Pods` to keep them secure. We attempt the updates in a way that reduces impact, but there are times when [.noloc]`Pods` must be deleted if they aren't successfully evicted. There are some actions you can take to minimize disruption. For more information, see <<fargate-pod-patching>>.
* The https://github.com/aws/amazon-vpc-cni-plugins[Amazon VPC CNI plugin for Amazon EKS] is installed on Fargate nodes. You can't use <<alternate-cni-plugins,Alternate CNI plugins for Amazon EKS clusters>> with Fargate nodes.
* A [.noloc]`Pod` running on Fargate automatically mounts an Amazon EFS file system. You can't use dynamic persistent volume provisioning with Fargate nodes, but you can use static provisioning.
* Amazon EKS doesn't support Fargate Spot.
* You can't mount Amazon EBS volumes to Fargate [.noloc]`Pods`.
* You can run the Amazon EBS CSI controller on Fargate nodes, but the Amazon EBS CSI node [.noloc]`DaemonSet` can only run on Amazon EC2 instances.
* After a https://kubernetes.io/docs/concepts/workloads/controllers/job/[Kubernetes Job] is marked `Completed` or `Failed`, the [.noloc]`Pods` that the [.noloc]`Job` creates normally continue to exist. This behavior allows you to view your logs and results, but with Fargate you will incur costs if you don't clean up the [.noloc]`Job` afterwards.
+
To automatically delete the related [.noloc]`Pods` after a [.noloc]`Job` completes or fails, you can specify a time period using the time-to-live (TTL) controller. The following example shows specifying `.spec.ttlSecondsAfterFinished` in your [.noloc]`Job` manifest.
+
[source,yaml,subs="verbatim,attributes,quotes"]
----
apiVersion: batch/v1
kind: Job
metadata:
  name: busybox
spec:
  template:
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["/bin/sh", "-c", "sleep 10"]
      restartPolicy: Never
  ttlSecondsAfterFinished: 60 # <-- TTL controller
----


[.topic]
include::fargate-getting-started.adoc[leveloffset=+1]

include::fargate-profile.adoc[leveloffset=+1]

include::delete-fargate-profile.adoc[leveloffset=+1]

include::fargate-pod-configuration.adoc[leveloffset=+1]

include::fargate-pod-patching.adoc[leveloffset=+1]

include::monitoring-fargate-usage.adoc[leveloffset=+1]

include::fargate-logging.adoc[leveloffset=+1]

