//!!NODE_ROOT <section>
include::../attributes.txt[]
[.topic]
[[fargate-pod-patching,fargate-pod-patching.title]]
= Set actions for {aws} Fargate OS patching events
:info_titleabbrev: OS patching events

[abstract]
--
Amazon EKS periodically patches the OS for {aws} Fargate nodes to keep them secure.
--

[IMPORTANT]
====

{aws} Fargate with Amazon EKS isn't available in {aws} GovCloud (US-East) and {aws} GovCloud (US-West).

====

Amazon EKS periodically patches the OS for {aws} Fargate nodes to keep them secure. As part of the patching process, we recycle the nodes to install OS patches. Updates are attempted in a way that creates the least impact on your services. However, if [.noloc]`Pods` aren't successfully evicted, there are times when they must be deleted. The following are actions that you can take to minimize potential disruptions:

* Set appropriate [.noloc]`Pod` disruption budgets (PDBs) to control the number of [.noloc]`Pods` that are down simultaneously.
* Create Amazon EventBridge rules to handle failed evictions before the [.noloc]`Pods` are deleted.
* Create a notification configuration in {aws} User Notifications.

Amazon EKS works closely with the [.noloc]`Kubernetes` community to make bug fixes and security patches available as quickly as possible. All Fargate [.noloc]`Pods` start on the most recent [.noloc]`Kubernetes` patch version, which is available from Amazon EKS for the [.noloc]`Kubernetes` version of your cluster. If you have a [.noloc]`Pod` with an older patch version, Amazon EKS might recycle it to update it to the latest version. This ensures that your [.noloc]`Pods` are equipped with the latest security updates. That way, if there's a critical https://cve.mitre.org/[Common Vulnerabilities and Exposures] (CVE) issue, you're kept up to date to reduce security risks.

To limit the number of [.noloc]`Pods` that are down at one time when [.noloc]`Pods` are recycled, you can set [.noloc]`Pod` disruption budgets (PDBs). You can use PDBs to define minimum availability based on the requirements of each of your applications while still allowing updates to occur. For more information, see https://kubernetes.io/docs/tasks/run-application/configure-pdb/[Specifying a Disruption Budget for your Application] in the [.noloc]`Kubernetes` Documentation.

Amazon EKS uses the https://kubernetes.io/docs/tasks/administer-cluster/safely-drain-node/#eviction-api[Eviction API] to safely drain the [.noloc]`Pod` while respecting the PDBs that you set for the application. Pods are evicted by Availability Zone to minimize impact. If the eviction succeeds, the new [.noloc]`Pod` gets the latest patch and no further action is required.

When the eviction for a [.noloc]`Pod` fails, Amazon EKS sends an event to your account with details about the [.noloc]`Pods` that failed eviction. You can act on the message before the scheduled termination time. The specific time varies based on the urgency of the patch. When it's time, Amazon EKS attempts to evict the [.noloc]`Pods` again. However, this time a new event isn't sent if the eviction fails. If the eviction fails again, your existing [.noloc]`Pods` are deleted periodically so that the new [.noloc]`Pods` can have the latest patch.

The following is a sample event received when the [.noloc]`Pod` eviction fails. It contains details about the cluster, [.noloc]`Pod` name, [.noloc]`Pod` namespace, Fargate profile, and the scheduled termination time.

[source,json,subs="verbatim,attributes,quotes"]
----
{
    "version": "0",
    "id": "12345678-90ab-cdef-0123-4567890abcde",
    "detail-type": "EKS Fargate Pod Scheduled Termination",
    "source": "aws.eks",
    "account": "111122223333",
    "time": "2021-06-27T12:52:44Z",
    "region": "region-code",
    "resources": [
        "default/my-database-deployment"
    ],
    "detail": {
        "clusterName": "my-cluster",
        "fargateProfileName": "my-fargate-profile",
        "podName": "my-pod-name",
        "podNamespace": "default",
        "evictErrorMessage": "Cannot evict pod as it would violate the pod's disruption budget",
        "scheduledTerminationTime": "2021-06-30T12:52:44.832Z[UTC]"
    }
}
----

In addition, having multiple PDBs associated with a [.noloc]`Pod` can cause an eviction failure event. This event returns the following error message.

[source,json,subs="verbatim,attributes,quotes"]
----
"evictErrorMessage": "This pod has multiple PodDisruptionBudget, which the eviction subresource does not support",
----

You can create a desired action based on this event. For example, you can adjust your [.noloc]`Pod` disruption budget (PDB) to control how the [.noloc]`Pods` are evicted. More specifically, suppose that you start with a PDB that specifies the target percentage of [.noloc]`Pods` that are available. Before your [.noloc]`Pods` are force terminated during an upgrade, you can adjust the PDB to a different percentage of [.noloc]`Pods`. To receive this event, you must create an Amazon EventBridge rule in the {aws} account and {aws} Region that the cluster belongs to. The rule must use the following  *Custom pattern*. For more information, see link:eventbridge/latest/userguide/eb-create-rule.html[Creating Amazon EventBridge rules that react to events,type="documentation"] in the _Amazon EventBridge User Guide_.

[source,json,subs="verbatim,attributes,quotes"]
----
{
  "source": ["aws.eks"],
  "detail-type": ["EKS Fargate Pod Scheduled Termination"]
}
----

A suitable target can be set for the event to capture it. For a complete list of available targets, see link:eventbridge/latest/userguide/eb-targets.html[Amazon EventBridge targets,type="documentation"] in the _Amazon EventBridge User Guide_. You can also create a notification configuration in {aws} User Notifications. When using the {aws-management-console} to create the notification, under *Event Rules*, choose  *Elastic Kubernetes Service (EKS)* for *{aws} service name* and  *EKS Fargate Pod Scheduled Termination* for  *Event type*. For more information, see link:notifications/latest/userguide/getting-started.html[Getting started with {aws} User Notifications,type="documentation"] in the {aws} User Notifications User Guide.

