//!!NODE_ROOT <section>
[.topic]
[[hybrid-nodes-remove,hybrid-nodes-remove.title]]
= Remove hybrid nodes
:info_doctype: section
:info_title: Delete hybrid nodes from your EKS cluster
:info_titleabbrev: Delete hybrid nodes
:keywords: Delete hybrid nodes from your EKS cluster
:info_abstract: Delete hybrid nodes from your EKS cluster

include::../attributes.txt[]

[abstract]
--
Delete hybrid nodes from your EKS cluster
--

This topic describes how to delete hybrid nodes from your Amazon EKS cluster. You must delete your hybrid nodes with your choice of Kubernetes-compatible tooling such as https://kubernetes.io/docs/reference/kubectl/[kubectl]. Charges for hybrid nodes stop when the node object is removed from the Amazon EKS cluster. For more information on hybrid nodes pricing, see https://aws.amazon.com/eks/pricing/[Amazon EKS Pricing].

[Important]
====
Removing nodes is disruptive to workloads running on the node. Before deleting hybrid nodes, it is recommended to first drain the node to move pods to another active node. For more information on draining nodes, see https://kubernetes.io/docs/tasks/administer-cluster/safely-drain-node/[Safely Drain a Node] in the Kubernetes documentation.
====

Run the kubectl steps below from your local machine or instance that you use to interact with the Amazon EKS cluster's Kubernetes API endpoint. If you are using a specific `kubeconfig` file, use the `--kubeconfig` flag.

== Step 1: List your nodes

[source,yaml,subs="verbatim,attributes,quotes"]
----
kubectl get nodes
----

== Step 2: Drain your node

See https://kubernetes.io/docs/reference/kubectl/generated/kubectl_drain/[kubectl drain] in the Kubernetes documentation for more information on the `kubectl drain` command.

[source,yaml,subs="verbatim,attributes,quotes"]
----
kubectl drain --ignore-daemonsets <node-name>
----

== Step 3: Stop and uninstall hybrid nodes artifacts

You can use the Amazon EKS Hybrid Nodes CLI (`nodeadm`) to stop and remove the hybrid nodes artifacts from the host. You must run `nodeadm` with a user that has root/sudo privileges. By default, `nodeadm uninstall` will not proceed if there are pods remaining on the node. If you are using {aws} Systems Manager (SSM) as your credentials provider, the `nodeadm uninstall` command deregisters the host as an {aws} SSM managed instance. For more information, see <<hybrid-nodes-nodeadm>>.

[source,yaml,subs="verbatim,attributes,quotes"]
----
nodeadm uninstall
----

== Step 4: Delete your node from the cluster

With the hybrid nodes artifacts stopped and uninstalled, remove the node resource from your cluster.

[source,yaml,subs="verbatim,attributes,quotes"]
----
kubectl delete node <node-name>
----

== Step 5: Check for remaining artifacts
Depending on your choice of CNI, there may be artifacts remaining on your hybrid nodes after running the above steps. See <<hybrid-nodes-cni>> for more information.


📝 https://github.com/search?q=repo:awsdocs/amazon-eks-user-guide+&#91;&#91;hybrid-nodes-remove,&type=code[Edit this page on GitHub]