//!!NODE_ROOT <section>
include::../attributes.txt[]
[.topic]
[[launch-node-ubuntu,launch-node-ubuntu.title]]
= Create self-managed [.noloc]`Ubuntu Linux` nodes
:info_titleabbrev: Ubuntu Linux

[abstract]
--
This topic describes how to launch Auto Scaling groups of [.noloc]`Ubuntu` nodes that register with your Amazon EKS cluster
--

[NOTE]
====

Managed node groups might offer some advantages for your use case. For more information, see <<managed-node-groups>>.

====

This topic describes how to launch Auto Scaling groups of https://cloud-images.ubuntu.com/aws-eks/[Ubuntu on Amazon Elastic Kubernetes Service (EKS)] or https://ubuntu.com/blog/ubuntu-pro-for-eks-is-now-generally-available[Ubuntu Pro on Amazon Elastic Kubernetes Service (EKS)] nodes that register with your Amazon EKS cluster. [.noloc]`Ubuntu` and [.noloc]`Ubuntu Pro` for EKS are based on the official [.noloc]`Ubuntu` Minimal LTS, include the custom {aws} kernel that is jointly developed with {aws}, and have been built specifically for EKS. [.noloc]`Ubuntu Pro` adds additional security coverage by supporting EKS extended support periods, kernel [.noloc]`livepatch`, FIPS compliance and the ability to run unlimited [.noloc]`Pro` containers.

After the nodes join the cluster, you can deploy containerized applications to them. For more information, visit the documentation for https://documentation.ubuntu.com/aws/en/latest/[Ubuntu on {aws}] and https://eksctl.io/usage/custom-ami-support/[Custom AMI support] in the `eksctl` documentation.

[IMPORTANT]
====


* Amazon EKS nodes are standard Amazon EC2 instances, and you are billed for them based on normal Amazon EC2 instance prices. For more information, see link:ec2/pricing/[Amazon EC2 pricing,type="marketing"].
* You can launch [.noloc]`Ubuntu` nodes in Amazon EKS extended clusters on {aws} Outposts, but you can't launch them in local clusters on {aws} Outposts. For more information, see <<eks-outposts>>.
* You can deploy to Amazon EC2 instances with `x86` or [.noloc]`Arm` processors. However, instances that have [.noloc]`Inferentia` chips might need to install the https://awsdocs-neuron.readthedocs-hosted.com/en/latest/[Neuron SDK] first.

====

This procedure requires `eksctl` version `{eksctl-min-version}` or later. You can check your version with the following command:

[source,bash,subs="verbatim,attributes,quotes"]
----
eksctl version
----

For instructions on how to install or upgrade `eksctl`, see https://eksctl.io/installation[Installation] in the `eksctl` documentation.NOTE: This procedure only works for clusters that were created with `eksctl`.
+
. Copy the following contents to your device. Replace `my-cluster` with the name of your cluster. The name can contain only alphanumeric characters (case-sensitive) and hyphens. It must start with an alphabetic character and can't be longer than 100 characters. Replace `ng-ubuntu` with a name for your node group. The node group name can't be longer than 63 characters. It must start with letter or digit, but can also include hyphens and underscores for the remaining characters. To deploy on [.noloc]`Arm` instances, replace `m5.large` with an [.noloc]`Arm` instance type. Replace `my-ec2-keypair-name` with the name of an Amazon EC2 SSH key pair that you can use to connect using SSH into your nodes with after they launch. If you don't already have an Amazon EC2 key pair, you can create one in the {aws-management-console}. For more information, see link:AWSEC2/latest/UserGuide/ec2-key-pairs.html[Amazon EC2 key pairs,type="documentation"] in the Amazon EC2 User Guide. Replace all remaining [.replaceable]`example values` with your own values. Once you've made the replacements, run the modified command to create the `ubuntu.yaml` file.
+
IMPORTANT: To deploy a node group to {aws} Outposts, {aws} Wavelength, or {aws} Local Zone subnets, don't pass {aws} Outposts, {aws} Wavelength, or {aws} Local Zone subnets when you create the cluster. You must specify the subnets in the following example. For more information see https://eksctl.io/usage/nodegroups/#creating-a-nodegroup-from-a-config-file[Create a nodegroup from a config file] and https://eksctl.io/usage/schema/[Config file schema] in the `eksctl` documentation. Replace [.replaceable]`region-code` with the {aws} Region that your cluster is in.
+
[source,yaml,subs="verbatim,attributes,quotes"]
----
cat >ubuntu.yaml <<EOF
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-cluster
  region: region-code
  version: '1.30'

iam:
  withOIDC: true

nodeGroups:
  - name: ng-ubuntu
    instanceType: m5.large
    desiredCapacity: 3
    amiFamily: Ubuntu2204
    ami: auto-ssm
    iam:
       attachPolicyARNs:
          - {arn-aws}iam::aws:policy/AmazonEKSWorkerNodePolicy
          - {arn-aws}iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
          - {arn-aws}iam::aws:policy/AmazonSSMManagedInstanceCore
          - {arn-aws}iam::aws:policy/AmazonEKS_CNI_Policy
    ssh:
        allow: true
        publicKeyName: my-ec2-keypair-name
EOF
----
+
To create an [.noloc]`Ubuntu Pro` node group, just change the `amiFamily` value to `UbuntuPro2204`.
. Deploy your nodes with the following command.
+
[source,bash,subs="verbatim,attributes,quotes"]
----
eksctl create nodegroup --config-file=ubuntu.yaml
----
+
An example output is as follows.
+
Several lines are output while the nodes are created. One of the last lines of output is the following example line.
+
[source,bash,subs="verbatim,attributes,quotes"]
----
[✔]  created 1 nodegroup(s) in cluster "my-cluster"
----
. (Optional) Deploy a <<sample-deployment,sample application>> to test your [.noloc]`Ubuntu` nodes.
. We recommend blocking [.noloc]`Pod` access to IMDS if the following conditions are true:
+
** You plan to assign IAM roles to all of your [.noloc]`Kubernetes` service accounts so that [.noloc]`Pods` only have the minimum permissions that they need.
** No [.noloc]`Pods` in the cluster require access to the Amazon EC2 instance metadata service (IMDS) for other reasons, such as retrieving the current {aws} Region.

+
For more information, see https://aws.github.io/aws-eks-best-practices/security/docs/iam/#restrict-access-to-the-instance-profile-assigned-to-the-worker-node[Restrict access to the instance profile assigned to the worker node].


