//!!NODE_ROOT <section>
include::../attributes.txt[]
[.topic]
[[launch-node-bottlerocket,launch-node-bottlerocket.title]]
= Create self-managed [.noloc]`Bottlerocket` nodes
:info_titleabbrev: Bottlerocket

[abstract]
--
This topic describes how to launch Auto Scaling groups of [.noloc]`Bottlerocket` nodes that register with your Amazon EKS cluster
--

[NOTE]
====

Managed node groups might offer some advantages for your use case. For more information, see <<managed-node-groups>>.

====

This topic describes how to launch Auto Scaling groups of link:bottlerocket/[Bottlerocket,type="marketing"] nodes that register with your Amazon EKS cluster. [.noloc]`Bottlerocket` is a [.noloc]`Linux`-based open-source operating system from {aws} that you can use for running containers on virtual machines or bare metal hosts. After the nodes join the cluster, you can deploy [.noloc]`Kubernetes` applications to them. For more information about [.noloc]`Bottlerocket`, see https://github.com/bottlerocket-os/bottlerocket/blob/develop/QUICKSTART-EKS.md[Using a Bottlerocket AMI with Amazon EKS] on [.noloc]`GitHub` and https://eksctl.io/usage/custom-ami-support/[Custom AMI support] in the `eksctl` documentation.

For information about in-place upgrades, see https://github.com/bottlerocket-os/bottlerocket-update-operator[Bottlerocket Update Operator] on [.noloc]`GitHub`.

[IMPORTANT]
====


* Amazon EKS nodes are standard Amazon EC2 instances, and you are billed for them based on normal Amazon EC2 instance prices. For more information, see link:ec2/pricing/[Amazon EC2 pricing,type="marketing"].
* You can launch Bottlerocket nodes in Amazon EKS extended clusters on {aws} Outposts, but you can't launch them in local clusters on {aws} Outposts. For more information, see <<eks-outposts>>.
* You can deploy to Amazon EC2 instances with `x86` or [.noloc]`Arm` processors. However, you can't deploy to instances that have [.noloc]`Inferentia` chips.
* [.noloc]`Bottlerocket` is compatible with {aws} CloudFormation. However, there is no official CloudFormation template that can be copied to deploy [.noloc]`Bottlerocket` nodes for Amazon EKS.
* [.noloc]`Bottlerocket` images don't come with an [.noloc]`SSH` server or a shell. You can use out-of-band access methods to allow [.noloc]`SSH` enabling the admin container and to pass some bootstrapping configuration steps with user data. For more information, see these sections in the https://github.com/bottlerocket-os/bottlerocket[bottlerocket README.md] on [.noloc]`GitHub`:
+
** https://github.com/bottlerocket-os/bottlerocket#exploration[Exploration]
** https://github.com/bottlerocket-os/bottlerocket#admin-container[Admin container]
** https://github.com/bottlerocket-os/bottlerocket#kubernetes-settings[Kubernetes settings]

====

This procedure requires `eksctl` version `{eksctl-min-version}` or later. You can check your version with the following command:

[source,bash,subs="verbatim,attributes,quotes"]
----
eksctl version
----

For instructions on how to install or upgrade `eksctl`, see https://eksctl.io/installation[Installation] in the `eksctl` documentation.NOTE: This procedure only works for clusters that were created with `eksctl`.
+
. Copy the following contents to your device. Replace [.replaceable]`my-cluster` with the name of your cluster. The name can contain only alphanumeric characters (case-sensitive) and hyphens. It must start with an alphanumeric character and can't be longer than 100 characters. The name must be unique within the {aws} Region and {aws} account that you're creating the cluster in. Replace [.replaceable]`ng-bottlerocket` with a name for your node group. The node group name can't be longer than 63 characters. It must start with letter or digit, but can also include hyphens and underscores for the remaining characters. To deploy on Arm instances, replace [.replaceable]`m5.large` with an Arm instance type. Replace [.replaceable]`my-ec2-keypair-name` with the name of an Amazon EC2 SSH key pair that you can use to connect using SSH into your nodes with after they launch. If you don't already have an Amazon EC2 key pair, you can create one in the {aws-management-console}. For more information, see link:AWSEC2/latest/UserGuide/ec2-key-pairs.html[Amazon EC2 key pairs,type="documentation"] in the _Amazon EC2 User Guide_. Replace all remaining [.replaceable]`example values` with your own values. Once you've made the replacements, run the modified command to create the `bottlerocket.yaml` file.
+
If specifying an Arm Amazon EC2 instance type, then review the considerations in <<arm-ami,Amazon EKS optimized Arm Amazon Linux AMIs>> before deploying. For instructions on how to deploy using a custom AMI, see https://github.com/bottlerocket-os/bottlerocket/blob/develop/BUILDING.md[Building Bottlerocket] on [.noloc]`GitHub` and https://eksctl.io/usage/custom-ami-support/[Custom AMI support] in the `eksctl` documentation. To deploy a managed node group, deploy a custom AMI using a launch template. For more information, see <<launch-templates>>.
+
IMPORTANT: To deploy a node group to {aws} Outposts, {aws} Wavelength, or {aws} Local Zone subnets, don't pass {aws} Outposts, {aws} Wavelength, or {aws} Local Zone subnets when you create the cluster. You must specify the subnets in the following example. For more information see https://eksctl.io/usage/nodegroups/#creating-a-nodegroup-from-a-config-file[Create a nodegroup from a config file] and https://eksctl.io/usage/schema/[Config file schema] in the `eksctl` documentation. Replace [.replaceable]`region-code` with the {aws} Region that your cluster is in.
+
[source,yaml,subs="verbatim,attributes,quotes"]
----
cat >bottlerocket.yaml <<EOF
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-cluster
  region: region-code
  version: '1.30'

iam:
  withOIDC: true

nodeGroups:
  - name: ng-bottlerocket
    instanceType: m5.large
    desiredCapacity: 3
    amiFamily: Bottlerocket
    ami: auto-ssm
    iam:
       attachPolicyARNs:
          - {arn-aws}iam::aws:policy/AmazonEKSWorkerNodePolicy
          - {arn-aws}iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
          - {arn-aws}iam::aws:policy/AmazonSSMManagedInstanceCore
          - {arn-aws}iam::aws:policy/AmazonEKS_CNI_Policy
    ssh:
        allow: true
        publicKeyName: my-ec2-keypair-name
EOF
----
. Deploy your nodes with the following command.
+
[source,bash,subs="verbatim,attributes,quotes"]
----
eksctl create nodegroup --config-file=bottlerocket.yaml
----
+
An example output is as follows.
+
Several lines are output while the nodes are created. One of the last lines of output is the following example line.
+
[source,bash,subs="verbatim,attributes,quotes"]
----
[✔]  created 1 nodegroup(s) in cluster "my-cluster"
----
. (Optional) Create a [.noloc]`Kubernetes` https://kubernetes.io/docs/concepts/storage/persistent-volumes/[persistent volume] on a [.noloc]`Bottlerocket` node using the https://github.com/kubernetes-sigs/aws-ebs-csi-driver[Amazon EBS CSI Plugin]. The default Amazon EBS driver relies on file system tools that aren't included with [.noloc]`Bottlerocket`. For more information about creating a storage class using the driver, see <<ebs-csi>>.
. (Optional) By default, `kube-proxy` sets the `nf_conntrack_max` kernel parameter to a default value that may differ from what [.noloc]`Bottlerocket` originally sets at boot. To keep [.noloc]`Bottlerocket`'s https://github.com/bottlerocket-os/bottlerocket/blob/develop/packages/release/release-sysctl.conf[default setting], edit the `kube-proxy` configuration with the following command.
+
[source,bash,subs="verbatim,attributes,quotes"]
----
kubectl edit -n kube-system daemonset kube-proxy
----
+
Add `--conntrack-max-per-core` and `--conntrack-min` to the `kube-proxy` arguments that are in the following example. A setting of `0` implies no change.
+
[source,yaml,subs="verbatim,attributes,quotes"]
----
      containers:
      - command:
        - kube-proxy
        - --v=2
        - --config=/var/lib/kube-proxy-config/config
        - --conntrack-max-per-core=0
        - --conntrack-min=0
----
. (Optional) Deploy a <<sample-deployment,sample application>> to test your [.noloc]`Bottlerocket` nodes.
. We recommend blocking [.noloc]`Pod` access to IMDS if the following conditions are true:
+
** You plan to assign IAM roles to all of your [.noloc]`Kubernetes` service accounts so that [.noloc]`Pods` only have the minimum permissions that they need.
** No [.noloc]`Pods` in the cluster require access to the Amazon EC2 instance metadata service (IMDS) for other reasons, such as retrieving the current {aws} Region.

+
For more information, see https://aws.github.io/aws-eks-best-practices/security/docs/iam/#restrict-access-to-the-instance-profile-assigned-to-the-worker-node[Restrict access to the instance profile assigned to the worker node].


