//!!NODE_ROOT <section>
[.topic]
[[retrieve-ami-id-bottlerocket,retrieve-ami-id-bottlerocket.title]]
= Retrieve recommended [.noloc]`Bottlerocket` AMI IDs
:info_titleabbrev: Get latest IDs

include::../attributes.txt[]

[abstract]
--
You can retrieve the Amazon Machine Image (AMI) ID for Amazon EKS optimized AMIs by querying the {aws} Systems Manager Parameter Store API. 
--

When deploying nodes, you can specify an ID for a pre-built Amazon EKS optimized Amazon Machine Image (AMI). To retrieve an AMI ID that fits your desired configuration, query the {aws} Systems Manager Parameter Store API. Using this API eliminates the need to manually look up Amazon EKS optimized AMI IDs. For more information, see link:systems-manager/latest/APIReference/API_GetParameter.html[GetParameter,type="documentation"]. The link:IAM/latest/UserGuide/id_roles.html#iam-term-principal[IAM principal,type="documentation"] that you use must have the `ssm:GetParameter` IAM permission to retrieve the Amazon EKS optimized AMI metadata.

You can retrieve the image ID of the latest recommended Amazon EKS optimized [.noloc]`Bottlerocket` AMI with the following {aws} CLI command, which uses the sub-parameter `image_id`. Make the following modifications to the command as needed and then run the modified command:

* Replace [.replaceable]`kubernetes-version` with a supported <<platform-versions,Amazon EKS version>>.
* Replace [.replaceable]`-flavor` with one of the following options.
+
** Remove [.replaceable]`-flavor` for variants without a GPU.
** Use [.replaceable]`-nvidia` for GPU-enabled variants.
** Use [.replaceable]`-fips` for FIPS-enabled variants.
* Replace [.replaceable]`architecture` with one of the following options.
+
** Use [.replaceable]`x86_64` for `x86` based instances.
** Use [.replaceable]`arm64` for ARM instances.
* Replace [.replaceable]`region-code` with an link:general/latest/gr/eks.html[Amazon EKS supported {aws} Region,type="documentation"] for which you want the AMI ID.


[source,bash,subs="verbatim,attributes,quotes"]
----
aws ssm get-parameter --name /aws/service/bottlerocket/aws-k8s-[.replaceable]`kubernetes-version-flavor`/[.replaceable]`architecture`/latest/image_id \
    --region [.replaceable]`region-code` --query "Parameter.Value" --output text
----

Here's an example command after placeholder replacements have been made.

[source,bash,subs="verbatim,attributes,quotes"]
----
aws ssm get-parameter --name /aws/service/bottlerocket/aws-k8s-[.replaceable]`1.31`/[.replaceable]`x86_64`/latest/image_id \
    --region [.replaceable]`us-west-2` --query "Parameter.Value" --output text
----

An example output is as follows.

[source,bash,subs="verbatim,attributes,quotes"]
----
ami-[.replaceable]`1234567890abcdef0`
----


📝 https://github.com/search?q=repo:awsdocs/amazon-eks-user-guide+&#91;&#91;retrieve-ami-id-bottlerocket,&type=code[Edit this page on GitHub]