//!!NODE_ROOT <section>
include::../attributes.txt[]
[.topic]
[[update-workers,update-workers.title]]
= Update self-managed nodes for your cluster
:info_titleabbrev: Update methods

[abstract]
--
When a new Amazon EKS optimized AMI is released, consider replacing the nodes in your self-managed node group with the new AMI.
--

When a new Amazon EKS optimized AMI is released, consider replacing the nodes in your self-managed node group with the new AMI. Likewise, if you have updated the [.noloc]`Kubernetes` version for your Amazon EKS cluster, update the nodes to use nodes with the same [.noloc]`Kubernetes` version.

[IMPORTANT]
====

This topic covers node updates for self-managed nodes. If you are using <<managed-node-groups,Simplify node lifecycle with managed node groups>>, see <<update-managed-node-group>>.

====

There are two basic ways to update self-managed node groups in your clusters to use a new AMI:

*<<migrate-stack,Migrate applications to a new node group>>*::
Create a new node group and migrate your [.noloc]`Pods` to that group. Migrating to a new node group is more graceful than simply updating the AMI ID in an existing {aws} CloudFormation stack. This is because the migration process https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/[taints] the old node group as `NoSchedule` and drains the nodes after a new stack is ready to accept the existing [.noloc]`Pod` workload.


*<<update-stack,Update an {aws} CloudFormation node stack>>*::
Update the {aws} CloudFormation stack for an existing node group to use the new AMI. This method isn't supported for node groups that were created with `eksctl`.

include::migrate-stack.adoc[leveloffset=+1]

include::update-stack.adoc[leveloffset=+1]
