//!!NODE_ROOT <section>
include::../attributes.txt[]

[.topic]
[[eks-outposts-self-managed-nodes,eks-outposts-self-managed-nodes.title]]
= Create Amazon Linux nodes on {aws} Outposts
:info_doctype: section
:info_title: Create Amazon Linux nodes on {aws} Outposts
:info_titleabbrev: Nodes
:keywords: launch, start, self-managed, Linux, node
:info_abstract: Learn how to launch Auto Scaling groups of Amazon Linux nodes on an Outpost that register with \
                your Amazon EKS cluster. The cluster can be on the {aws} Cloud or on an Outpost.

[abstract]
--
Learn how to launch Auto Scaling groups of Amazon Linux nodes on an Outpost that register with your Amazon EKS cluster. The cluster can be on the {aws} Cloud or on an Outpost.
--

This topic describes how you can launch Auto Scaling groups of Amazon Linux nodes on an Outpost that register with your Amazon EKS cluster. The cluster can be on the {aws} Cloud or on an Outpost.



* An existing Outpost. For more information, see link:outposts/latest/userguide/what-is-outposts.html[What is {aws} Outposts,type="documentation"].
* An existing Amazon EKS cluster. To deploy a cluster on the {aws} Cloud, see <<create-cluster>>. To deploy a cluster on an Outpost, see <<eks-outposts-local-cluster-overview>>.
* Suppose that you're creating your nodes in a cluster on the {aws} Cloud and you have subnets in the {aws} Region where you have {aws} Outposts, {aws} Wavelength, or {aws} Local Zones enabled. Then, those subnets must not have been passed in when you created your cluster. If you're creating your nodes in a cluster on an Outpost, you must have passed in an Outpost subnet when creating your cluster.
* (Recommended for clusters on the {aws} Cloud) The [.noloc]`Amazon VPC CNI plugin for Kubernetes` add-on configured with its own IAM role that has the necessary IAM policy attached to it. For more information, see <<cni-iam-role>>. Local clusters do not support IAM roles for service accounts. 

You can create a self-managed Amazon Linux node group with `eksctl` or the {aws-management-console} (with an {aws} CloudFormation template). You can also use https://registry.terraform.io/modules/terraform-aws-modules/eks/aws/latest[Terraform].

You can create a local cluster with the following tools described in this page:

* <<eksctl_create_nodes_outpost>>
* <<console_create_nodes_outpost>>

== `eksctl` [[eksctl_create_nodes_outpost]]

*To launch self-managed Linux nodes using `eksctl`*`

. Install version `{eksctl-min-version}` or later of the `eksctl` command line tool installed on your device or {aws} CloudShell. To install or update `eksctl`, see https://eksctl.io/installation[Installation] in the `eksctl` documentation.
+
. If your cluster is on the {aws} Cloud and the *AmazonEKS_CNI_Policy* managed IAM policy is attached to your  <<create-node-role,Amazon EKS node IAM role>>, we recommend assigning it to an IAM role that you associate to the [.noloc]`Kubernetes` `aws-node` service account instead. For more information, see <<cni-iam-role>>. If your cluster in on your Outpost, the policy must be attached to your node role.
. The following command creates a node group in an existing cluster. The cluster must have been created using `eksctl`. Replace [.replaceable]`al-nodes` with a name for your node group. The node group name can't be longer than 63 characters. It must start with letter or digit, but can also include hyphens and underscores for the remaining characters. Replace [.replaceable]`my-cluster` with the name of your cluster. The name can contain only alphanumeric characters (case-sensitive) and hyphens. It must start with an alphanumeric character and can't be longer than 100 characters. The name must be unique within the {aws} Region and {aws} account that you're creating the cluster in. If your cluster exists on an Outpost, replace [.replaceable]`id` with the ID of an Outpost subnet. If your cluster exists on the {aws} Cloud, replace [.replaceable]`id` with the ID of a subnet that you didn't specify when you created your cluster. Replace [.replaceable]`instance-type` with an instance type supported by your Outpost. Replace the remaining [.replaceable]`example values` with your own values. The nodes are created with the same [.noloc]`Kubernetes` version as the control plane, by default.  
+
Replace [.replaceable]`instance-type` with an instance type available on your Outpost.
+
Replace [.replaceable]`my-key` with the name of your Amazon EC2 key pair or public key. This key is used to SSH into your nodes after they launch. If you don't already have an Amazon EC2 key pair, you can create one in the {aws-management-console}. For more information, see link:AWSEC2/latest/UserGuide/ec2-key-pairs.html[Amazon EC2 key pairs,type="documentation"] in the _Amazon EC2 User Guide_.
+
Create your node group with the following command.
+
[source,bash,subs="verbatim,attributes"]
----
eksctl create nodegroup --cluster my-cluster --name al-nodes --node-type instance-type \
    --nodes 3 --nodes-min 1 --nodes-max 4 --managed=false --node-volume-type gp2 --subnet-ids subnet-id
----
+
If your cluster is deployed on the {aws} Cloud:
+
** The node group that you deploy can assign `IPv4` addresses to [.noloc]`Pods` from a different [.noloc]`CIDR` block than that of the instance. For more information, see <<cni-custom-network>>.
** The node group that you deploy doesn't require outbound internet access. For more information, see <<private-clusters>>.

+
For a complete list of all available options and defaults, see https://eksctl.io/usage/outposts/[{aws} Outposts Support] in the `eksctl` documentation.
** If nodes fail to join the cluster, then see <<worker-node-fail>> in <<troubleshooting,Troubleshoot problems with Amazon EKS clusters and nodes>> and <<outposts-troubleshooting-unable-to-join-nodes-to-a-cluster>> in <<eks-outposts-troubleshooting,Troubleshoot local Amazon EKS clusters on {aws} Outposts>>.
** An example output is as follows. Several lines are output while the nodes are created. One of the last lines of output is the following example line.
+
[source,bash,subs="verbatim,attributes"]
----
[✔]  created 1 nodegroup(s) in cluster "my-cluster"
----
. (Optional) Deploy a <<sample-deployment,sample application>> to test your cluster and [.noloc]`Linux` nodes.


== {aws-management-console} [[console_create_nodes_outpost]]

*Step 1: Launch self-managed Linux nodes using {aws-management-console}*`

. Download the latest version of the {aws} CloudFormation template.
+
[source,bash,subs="verbatim,attributes"]
----
curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/cloudformation/2022-12-23/amazon-eks-nodegroup.yaml
----
. Open the link:cloudformation/[{aws} CloudFormation console,type="console"].
. Choose *Create stack* and then select  *With new resources (standard)*.
. For *Specify template*, select  *Upload a template file* and then select  *Choose file*. Select the `amazon-eks-nodegroup.yaml` file that you downloaded in a previous step and then select *Next*.
. On the *Specify stack details* page, enter the following parameters accordingly, and then choose  *Next*:
+
** *Stack name*: Choose a stack name for your {aws} CloudFormation stack. For example, you can call it [.replaceable]`al-nodes`. The name can contain only alphanumeric characters (case-sensitive) and hyphens. It must start with an alphanumeric character and can't be longer than 100 characters. The name must be unique within the {aws} Region and {aws} account that you're creating the cluster in.
** *ClusterName*: Enter the name of your cluster. If this name doesn't match your cluster name, your nodes can't join the cluster.
** *ClusterControlPlaneSecurityGroup*: Choose the  *SecurityGroups* value from the {aws} CloudFormation output that you generated when you created your  <<creating-a-vpc,VPC>>.
+
The following steps show one operation to retrieve the applicable group.
+
... Open the link:eks/home#/clusters[Amazon EKS console,type="console"].
... Choose the name of the cluster.
... Choose the *Networking* tab.
... Use the *Additional security groups* value as a reference when selecting from the  *ClusterControlPlaneSecurityGroup* dropdown list.
** *NodeGroupName*: Enter a name for your node group. This name can be used later to identify the Auto Scaling node group that's created for your nodes.
** *NodeAutoScalingGroupMinSize*: Enter the minimum number of nodes that your node Auto Scaling group can scale in to.
** *NodeAutoScalingGroupDesiredCapacity*: Enter the desired number of nodes to scale to when your stack is created.
** *NodeAutoScalingGroupMaxSize*: Enter the maximum number of nodes that your node Auto Scaling group can scale out to.
** *NodeInstanceType*: Choose an instance type for your nodes. If your cluster is running on the {aws} Cloud, then for more information, see <<choosing-instance-type>>. If your cluster is running on an Outpost, then you can only select an instance type that is available on your Outpost.
** *NodeImageIdSSMParam*: Pre-populated with the Amazon EC2 Systems Manager parameter of a recent Amazon EKS optimized AMI for a variable [.noloc]`Kubernetes` version. To use a different [.noloc]`Kubernetes` minor version supported with Amazon EKS, replace [.replaceable]`1.XX` with a different <<kubernetes-versions,supported version>>. We recommend specifying the same [.noloc]`Kubernetes` version as your cluster.
+
To use the Amazon EKS optimized accelerated AMI, replace [.replaceable]`amazon-linux-2` with `amazon-linux-2-gpu`. To use the Amazon EKS optimized Arm AMI, replace [.replaceable]`amazon-linux-2` with `amazon-linux-2-arm64`.
+
NOTE: The Amazon EKS node AMI is based on Amazon Linux. You can track security or privacy events for Amazon Linux at the https://alas.aws.amazon.com/[Amazon Linux security center] by choosing the tab for your desired version. You can also subscribe to the applicable RSS feed. Security and privacy events include an overview of the issue, what packages are affected, and how to update your instances to correct the issue.
** *NodeImageId*: (Optional) If you're using your own custom AMI (instead of the Amazon EKS optimized AMI), enter a node AMI ID for your {aws} Region. If you specify a value here, it overrides any values in the  *NodeImageIdSSMParam* field.  
** *NodeVolumeSize*: Specify a root volume size for your nodes, in GiB.
** *NodeVolumeType*: Specify a root volume type for your nodes.
** *KeyName*: Enter the name of an Amazon EC2 SSH key pair that you can use to connect using SSH into your nodes with after they launch. If you don't already have an Amazon EC2 key pair, you can create one in the {aws-management-console}. For more information, see link:AWSEC2/latest/UserGuide/ec2-key-pairs.html[Amazon EC2 key pairs,type="documentation"] in the _Amazon EC2 User Guide_.
+
NOTE: If you don't provide a key pair here, the {aws} CloudFormation stack creation fails.
** *BootstrapArguments*: There are several optional arguments that you can pass to your nodes. For more information, view the https://github.com/awslabs/amazon-eks-ami/blob/main/templates/al2/runtime/bootstrap.sh[bootstrap script usage information] on [.noloc]`GitHub`. If you're adding nodes to an Amazon EKS Local Cluster on {aws} Outposts (where the [.noloc]`Kubernetes` control plane instances run on {aws} Outposts) and the cluster doesn't have ingress and egress internet connection (also known as private clusters), then you must provide the following bootstrap arguments (as a single line).
+
[source,bash,subs="verbatim,attributes"]
----
--b64-cluster-ca ${CLUSTER_CA} --apiserver-endpoint https://${APISERVER_ENDPOINT} --enable-local-outpost true --cluster-id ${CLUSTER_ID}
----
** *DisableIMDSv1*: By default, each node supports the Instance Metadata Service Version 1 (IMDSv1) and IMDSv2. You can disable IMDSv1. To prevent future nodes and [.noloc]`Pods` in the node group from using IMDSv1, set  *DisableIMDSv1* to  *true*. For more information about IMDS, see link:AWSEC2/latest/UserGuide/configuring-instance-metadata-service.html[Configuring the instance metadata service,type="documentation"]. For more information about restricting access to it on your nodes, see https://aws.github.io/aws-eks-best-practices/security/docs/iam/#restrict-access-to-the-instance-profile-assigned-to-the-worker-node[Restrict access to the instance profile assigned to the worker node].
** *VpcId*: Enter the ID for the  <<creating-a-vpc,VPC>> that you created. Before choosing a VPC, review <<outposts-vpc-requirements,VPC requirements and considerations>>.
** *Subnets*: If your cluster is on an Outpost, then choose at least one private subnet in your VPC. Before choosing subnets, review  <<outposts-subnet-requirements,Subnet requirements and considerations>>. You can see which subnets are private by opening each subnet link from the *Networking* tab of your cluster.
. Select your desired choices on the *Configure stack options* page, and then choose  *Next*.
. Select the check box to the left of *I acknowledge that {aws} CloudFormation might create IAM resources.*, and then choose  *Create stack*.
. When your stack has finished creating, select it in the console and choose *Outputs*.
. Record the *NodeInstanceRole* for the node group that was created. You need this when you configure your Amazon EKS nodes.

*Step 2: Enable nodes to join your cluster*

. Check to see if you already have an `aws-auth` `ConfigMap`.
+
[source,bash,subs="verbatim,attributes"]
----
kubectl describe configmap -n kube-system aws-auth
----
. If you are shown an `aws-auth` `ConfigMap`, then update it as needed.
+
.. Open the `ConfigMap` for editing.
+
[source,bash,subs="verbatim,attributes"]
----
kubectl edit -n kube-system configmap/aws-auth
----
.. Add a new `mapRoles` entry as needed. Set the `rolearn` value to the *NodeInstanceRole* value that you recorded in the previous procedure.
+
[source,yaml,subs="verbatim,attributes"]
----
[...]
data:
  mapRoles: |
    - rolearn: <ARN of instance role (not instance profile)>
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
[...]
----
.. Save the file and exit your text editor.
. If you received an error stating "``Error from server (NotFound): configmaps "aws-auth" not found``, then apply the stock `ConfigMap`.
+
.. Download the configuration map.
+
[source,bash,subs="verbatim,attributes"]
----
curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/cloudformation/2020-10-29/aws-auth-cm.yaml
----
.. In the ``aws-auth-cm.yaml`` file, set the `rolearn` to the *NodeInstanceRole* value that you recorded in the previous procedure. You can do this with a text editor, or by replacing [.replaceable]`my-node-instance-role` and running the following command:
+
[source,bash,subs="verbatim,attributes"]
----
sed -i.bak -e 's|<ARN of instance role (not instance profile)>|my-node-instance-role|' aws-auth-cm.yaml
----
.. Apply the configuration. This command may take a few minutes to finish.
+
[source,bash,subs="verbatim,attributes"]
----
kubectl apply -f aws-auth-cm.yaml
----
. Watch the status of your nodes and wait for them to reach the `Ready` status.
+
[source,bash,subs="verbatim,attributes"]
----
kubectl get nodes --watch
----
+
Enter `Ctrl`+``C`` to return to a shell prompt.
+
NOTE: If you receive any authorization or resource type errors, see <<unauthorized>> in the troubleshooting topic.
+
If nodes fail to join the cluster, then see <<worker-node-fail>> in <<troubleshooting,Troubleshoot problems with Amazon EKS clusters and nodes>> and <<outposts-troubleshooting-unable-to-join-nodes-to-a-cluster>> in <<eks-outposts-troubleshooting,Troubleshoot local Amazon EKS clusters on {aws} Outposts>>.
. Install the Amazon EBS CSI driver. For more information, see https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/docs/install.md[Installation] on GitHub. In the *Set up driver permission* section, make sure to follow the instruction for the *Using IAM instance profile* option. You must use the `gp2` storage class. The `gp3` storage class isn't supported.
+
To create a `gp2` storage class on your cluster, complete the following steps.
+
.. Run the following command to create the `gp2-storage-class.yaml` file.
+
[source,yaml,subs="verbatim,attributes"]
----
cat >gp2-storage-class.yaml <<EOF
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  name: ebs-sc
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: gp2
  encrypted: "true"
allowVolumeExpansion: true
EOF
----
.. Apply the manifest to your cluster.
+
[source,bash,subs="verbatim,attributes"]
----
kubectl apply -f gp2-storage-class.yaml
----
. (GPU nodes only) If you chose a GPU instance type and the Amazon EKS optimized accelerated AMI, you must apply the https://github.com/NVIDIA/k8s-device-plugin[NVIDIA device plugin for Kubernetes] as a [.noloc]`DaemonSet` on your cluster. Replace [.replaceable]`vX.X.X` with your desired https://github.com/NVIDIA/k8s-device-plugin/releases[NVIDIA/k8s-device-plugin] version before running the following command.
+
[source,bash,subs="verbatim,attributes"]
----
kubectl apply -f https://raw.githubusercontent.com/NVIDIA/k8s-device-plugin/vX.X.X/deployments/static/nvidia-device-plugin.yml
----

*Step3: Additional actions*

. (Optional) Deploy a <<sample-deployment,sample application>> to test your cluster and [.noloc]`Linux` nodes.
. If your cluster is deployed on an Outpost, then skip this step. If your cluster is deployed on the {aws} Cloud, the following information is optional. If the *AmazonEKS_CNI_Policy* managed IAM policy is attached to your  <<create-node-role,Amazon EKS node IAM role>>, we recommend assigning it to an IAM role that you associate to the [.noloc]`Kubernetes` `aws-node` service account instead. For more information, see <<cni-iam-role>>.
