//!!NODE_ROOT <section>
include::../attributes.txt[]

[.topic]
[[copy-image-to-repository,copy-image-to-repository.title]]
= Copy a container image from one repository to another repository
:info_doctype: section
:info_title: Copy a container image from one repository to \
            another repository
:info_titleabbrev: Copy an image to a repository

This topic describes how to pull a container image from a repository that your nodes don't have access to and push the image to a repository that your nodes have access to. You can push the image to Amazon ECR or an alternative repository that your nodes have access to.



* The [.noloc]`Docker` engine installed and configured on your computer. For instructions, see https://docs.docker.com/engine/install/[Install Docker Engine] in the [.noloc]`Docker` documentation.
* Version `2.12.3` or later or version `1.27.160` or later of the {aws} Command Line Interface ({aws} CLI) installed and configured on your device or {aws} CloudShell. To check your current version, use `aws --version | cut -d / -f2 | cut -d ' ' -f1`. Package managers such `yum`, `apt-get`, or [.noloc]`Homebrew` for [.noloc]`macOS` are often several versions behind the latest version of the {aws} CLI. To install the latest version, see link:cli/latest/userguide/cli-chap-install.html[Installing, updating, and uninstalling the {aws} CLI,type="documentation"] and  link:cli/latest/userguide/cli-configure-quickstart.html#cli-configure-quickstart-config[Quick configuration with aws configure,type="documentation"] in the _{aws} Command Line Interface User Guide_. The {aws} CLI version that is installed in {aws} CloudShell might also be several versions behind the latest version. To update it, see  link:cloudshell/latest/userguide/vm-specs.html#install-cli-software[Installing {aws} CLI to your home directory,type="documentation"] in the _{aws} CloudShell User Guide_.
* An interface VPC endpoint for Amazon ECR if you want your nodes to pull container images from or push container images to a private Amazon ECR repository over Amazon's network. For more information, see  link:AmazonECR/latest/userguide/vpc-endpoints.html#ecr-setting-up-vpc-create[Create the VPC endpoints for Amazon ECR,type="documentation"] in the Amazon Elastic Container Registry User Guide.

Complete the following steps to pull a container image from a repository and push it to your own repository. In the following examples that are provided in this topic, the image for the https://github.com/aws/amazon-vpc-cni-k8s/blob/master/cmd/cni-metrics-helper/README.md[Amazon VPC CNI plugin for Kubernetes metrics helper] is pulled. When you follow these steps, make sure to replace the [.replaceable]`example values` with your own values.

. If you don't already have an Amazon ECR repository or another repository, then create one that your nodes have access to. The following command creates an Amazon ECR private repository. An Amazon ECR private repository name must start with a letter. It can only contain lowercase letters, numbers, hyphens (-), underscores (_), and forward slashes (/). For more information, see link:AmazonECR/latest/userguide/repository-create.html[Creating a private repository,type="documentation"] in the Amazon Elastic Container Registry User Guide. 
+
You can replace [.replaceable]`cni-metrics-helper` with whatever you choose. As a best practice, create a separate repository for each image. We recommend this because image tags must be unique within a repository. Replace [.replaceable]`region-code` with an link:general/latest/gr/ecr.html[{aws} Region supported by Amazon ECR,type="documentation"].
+
[source,bash,subs="verbatim,attributes"]
----
aws ecr create-repository --region region-code --repository-name cni-metrics-helper
----
. Determine the registry, repository, and tag (optional) of the image that your nodes need to pull. This information is in the `registry/repository[:tag]` format.
+
Many of the Amazon EKS topics about installing images require that you apply a manifest file or install the image using a Helm chart. However, before you apply a manifest file or install a Helm chart, first view the contents of the manifest or chart's `values.yaml` file. That way, you can determine the registry, repository, and tag to pull.
+
For example, you can find the following line in the https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/v1.12.6/config/master/cni-metrics-helper.yaml[manifest file] for the https://github.com/aws/amazon-vpc-cni-k8s/blob/master/cmd/cni-metrics-helper/README.md[Amazon VPC CNI plugin for Kubernetes metrics helper]. The registry is `602401143452.dkr.ecr.us-west-2.amazonaws.com`, which is an Amazon ECR private registry. The repository is `cni-metrics-helper`.
+
[source,bash,subs="verbatim,attributes"]
----
image: "602401143452.dkr.ecr.us-west-2.amazonaws.com/cni-metrics-helper:v1.12.6"
----
+
You may see the following variations for an image location:
+
** Only `repository-name:tag`. In this case, `docker.io` is usually the registry, but not specified since [.noloc]`Kubernetes` prepends it to a repository name by default if no registry is specified.
** `repository-name/repository-namespace/repository:tag`. A repository namespace is optional, but is sometimes specified by the repository owner for categorizing images. For example, all https://gallery.ecr.aws/aws-ec2/[Amazon EC2 images in the Amazon ECR Public Gallery] use the `aws-ec2` namespace.
+
Before installing an image with Helm, view the Helm `values.yaml` file to determine the image location. For example, the  https://github.com/aws/amazon-vpc-cni-k8s/blob/master/charts/cni-metrics-helper/values.yaml#L5-L9[values.yaml] file for the https://github.com/aws/amazon-vpc-cni-k8s/blob/master/cmd/cni-metrics-helper/README.md[Amazon VPC CNI plugin for Kubernetes metrics helper] includes the following lines.
+
[source,yaml,subs="verbatim,attributes"]
----
image:
  region: us-west-2
  tag: v1.12.6
  account: "602401143452"
  domain: "amazonaws.com"
----
. Pull the container image specified in the manifest file.
+
[loweralpha]
.. If you're pulling from a public registry, such as the https://gallery.ecr.aws/[Amazon ECR Public Gallery], you can skip to the next sub-step, because authentication isn't required. In this example, you authenticate to an Amazon ECR private registry that contains the repository for the CNI metrics helper image. Amazon EKS maintains the image in each registry listed in <<add-ons-images,View Amazon container image registries for Amazon EKS add-ons>>. You can authenticate to any of the registries by replacing [.replaceable]`602401143452` and [.replaceable]`region-code` with the information for a different registry. A separate registry exists for each  link:general/latest/gr/eks.html#eks_region[{aws} Region that Amazon EKS is supported in,type="documentation"].
+
[source,bash,subs="verbatim,attributes"]
----
aws ecr get-login-password --region region-code | docker login --username {aws} --password-stdin 602401143452.dkr.ecr.region-code.amazonaws.com
----
.. Pull the image. In this example, you pull from the registry that you authenticated to in the previous sub-step. Replace [.replaceable]`602401143452` and [.replaceable]`region-code` with the information that you provided in the previous sub-step.
+
[source,bash,subs="verbatim,attributes"]
----
docker pull 602401143452.dkr.ecr.region-code.amazonaws.com/cni-metrics-helper:v1.12.6
----
. Tag the image that you pulled with your registry, repository, and tag. The following example assumes that you pulled the image from the manifest file and are going to push it to the Amazon ECR private repository that you created in the first step. Replace [.replaceable]`111122223333` with your account ID. Replace [.replaceable]`region-code` with the {aws} Region that you created your Amazon ECR private repository in.
+
[source,bash,subs="verbatim,attributes"]
----
docker tag cni-metrics-helper:v1.12.6 111122223333.dkr.ecr.region-code.amazonaws.com/cni-metrics-helper:v1.12.6
----
. Authenticate to your registry. In this example, you authenticate to the Amazon ECR private registry that you created in the first step. For more information, see  link:AmazonECR/latest/userguide/Registries.html#registry_auth[Registry authentication,type="documentation"] in the Amazon Elastic Container Registry User Guide.
+
[source,bash,subs="verbatim,attributes"]
----
aws ecr get-login-password --region region-code | docker login --username {aws} --password-stdin 111122223333.dkr.ecr.region-code.amazonaws.com
----
. Push the image to your repository. In this example, you push the image to the Amazon ECR private repository that you created in the first step. For more information, see link:AmazonECR/latest/userguide/docker-push-ecr-image.html[Pushing a Docker image,type="documentation"] in the Amazon Elastic Container Registry User Guide.
+
[source,bash,subs="verbatim,attributes"]
----
docker push 111122223333.dkr.ecr.region-code.amazonaws.com/cni-metrics-helper:v1.12.6
----
. Update the manifest file that you used to determine the image in a previous step with the `registry/repository:tag` for the image that you pushed. If you're installing with a Helm chart, there's often an option to specify the `registry/repository:tag`. When installing the chart, specify the `registry/repository:tag` for the image that you pushed to your repository.
