//!!NODE_ROOT <section>
[.topic]
[[network-load-balancing,network-load-balancing.title]]
= Route [.noloc]`TCP` and [.noloc]`UDP` traffic with [.noloc]`Network Load Balancers`
:info_doctype: section
:info_title: Route TCP and UDP traffic with Network Load Balancers
:info_titleabbrev: Network load balancing
:info_abstract: Use the {aws} Load Balancer Controller to create network load balancers for Amazon EKS workloads, supporting IP and instance targets with {aws} Network Load Balancers.

include::../attributes.txt[]

[abstract]
--
Use the {aws} Load Balancer Controller to create network load balancers for Amazon EKS workloads, supporting IP and instance targets with {aws} Network Load Balancers.
--

[NOTE]
====
*New:* Amazon EKS Auto Mode automates routine tasks for load balancing. For more information, see:

* <<auto-elb-example>>
* <<auto-configure-nlb>>

====

Network traffic is load balanced at `L4` of the OSI model. To load balance application traffic at `L7`, you deploy a [.noloc]`Kubernetes` `ingress`, which provisions an {aws} Application Load Balancer. For more information, see <<alb-ingress>>. To learn more about the differences between the two types of load balancing, see link:elasticloadbalancing/features/[Elastic Load Balancing features,type="marketing"] on the {aws} website. 

When you create a [.noloc]`Kubernetes` `Service` of type `LoadBalancer`, the {aws} cloud provider load balancer controller creates {aws} link:elasticloadbalancing/latest/classic/introduction.html[Classic Load Balancers,type="documentation"] by default, but can also create {aws} link:elasticloadbalancing/latest/network/introduction.html[Network Load Balancers,type="documentation"]. This controller is only receiving critical bug fixes in the future. For more information about using the {aws} cloud provider load balancer , see https://kubernetes.io/docs/concepts/services-networking/service/#loadbalancer[{aws} cloud provider load balancer controller] in the [.noloc]`Kubernetes` documentation. Its use is not covered in this topic.

We recommend that you use version `2.7.2` or later of the <<aws-load-balancer-controller,{aws} Load Balancer Controller>> instead of the {aws} cloud provider load balancer controller. The [.noloc]`{aws} Load Balancer Controller` creates {aws} Network Load Balancers, but doesn't create {aws} Classic Load Balancers. The remainder of this topic is about using the {aws} Load Balancer Controller.

An {aws} Network Load Balancer can load balance network traffic to [.noloc]`Pods` deployed to Amazon EC2 IP and instance   link:elasticloadbalancing/latest/network/load-balancer-target-groups.html#target-type[targets,type="documentation"], to {aws} Fargate IP targets, or to Amazon EKS Hybrid Nodes as IP targets. For more information, see https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.7/guide/targetgroupbinding/targetgroupbinding/#targettype[{aws} Load Balancer Controller] on [.noloc]`GitHub`.


== Prerequisites

Before you can load balance network traffic using the [.noloc]`{aws} Load Balancer Controller`, you must meet the following requirements.

* Have an existing cluster. If you don't have an existing cluster, see <<getting-started>>. If you need to update the version of an existing cluster, see <<update-cluster>>.
* Have the [.noloc]`{aws} Load Balancer Controller` deployed on your cluster. For more information, see <<aws-load-balancer-controller>>. We recommend version `2.7.2` or later.
* At least one subnet. If multiple tagged subnets are found in an Availability Zone, the controller chooses the first subnet whose subnet ID comes first lexicographically. The subnet must have at least eight available IP addresses.
* If you're using the [.noloc]`{aws} Load Balancer Controller` version `2.1.1` or earlier, subnets must be tagged as follows. If using version `2.1.2` or later, this tag is optional. You might want to tag a subnet if you have multiple clusters running in the same VPC, or multiple {aws} services sharing subnets in a VPC, and want more control over where load balancers are provisioned for each cluster. If you explicitly specify subnet IDs as an annotation on a service object, then [.noloc]`Kubernetes` and the [.noloc]`{aws} Load Balancer Controller` use those subnets directly to create the load balancer. Subnet tagging isn't required if you choose to use this method for provisioning load balancers and you can skip the following private and public subnet tagging requirements. Replace [.replaceable]`my-cluster` with your cluster name.
+
** *Key*
 – `kubernetes.io/cluster/<my-cluster>`
** *Value*
 – `shared` or `owned`
* Your public and private subnets must meet the following requirements, unless you explicitly specify subnet IDs as an annotation on a service or ingress object. If you provision load balancers by explicitly specifying subnet IDs as an annotation on a service or ingress object, then [.noloc]`Kubernetes` and the [.noloc]`{aws} Load Balancer Controller` use those subnets directly to create the load balancer and the following tags aren't required.
+
** *Private subnets*
 – Must be tagged in the following format. This is so that [.noloc]`Kubernetes` and the {aws} Load Balancer Controller know that the subnets can be used for internal load balancers. If you use `eksctl` or an Amazon EKS {aws} {aws} CloudFormation template to create your VPC after March 26, 2020, then the subnets are tagged appropriately when they're created. For more information about the Amazon EKS {aws} {aws} CloudFormation VPC templates, see <<creating-a-vpc>>.
+
*** *Key*
 – `kubernetes.io/role/internal-elb`
*** *Value*
 – `1`
** *Public subnets*
 – Must be tagged in the following format. This is so that [.noloc]`Kubernetes` knows to use only those subnets for external load balancers instead of choosing a public subnet in each Availability Zone (based on the lexicographical order of the subnet IDs). If you use `eksctl` or an Amazon EKS {aws} CloudFormation template to create your VPC after March 26, 2020, then the subnets are tagged appropriately when they're created. For more information about the Amazon EKS {aws} CloudFormation VPC templates, see <<creating-a-vpc>>.
+
*** *Key* – `kubernetes.io/role/elb`
*** *Value* – `1`

+
If the subnet role tags aren't explicitly added, the [.noloc]`Kubernetes` service controller examines the route table of your cluster VPC subnets to determine if the subnet is private or public. We recommend that you don't rely on this behavior, and instead explicitly add the private or public role tags. The [.noloc]`{aws} Load Balancer Controller` doesn't examine route tables, and requires the private and public tags to be present for successful auto discovery.  


== Considerations 

* The configuration of your load balancer is controlled by annotations that are added to the manifest for your service. Service annotations are different when using the [.noloc]`{aws} Load Balancer Controller` than they are when using the {aws} cloud provider load balancer controller. Make sure to review the https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.7/guide/service/annotations/[annotations] for the [.noloc]`{aws} Load Balancer Controller` before deploying services.
* When using the <<managing-vpc-cni,Amazon VPC CNI plugin for Kubernetes>>, the [.noloc]`{aws} Load Balancer Controller` can load balance to Amazon EC2 IP or instance targets and Fargate IP targets. When using <<alternate-cni-plugins,Alternate compatible CNI plugins>>, the controller can only load balance to instance targets, unless you are load balancing to Amazon EKS Hybrid Nodes. For hybrid nodes, the controller can load balance IP targets. For more information about Network Load Balancer target types, see  link:elasticloadbalancing/latest/network/load-balancer-target-groups.html#target-type[Target type,type="documentation"] in the User Guide for Network Load Balancers
* If you want to add tags to the load balancer when or after it's created, add the following annotation in your service specification. For more information, see https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.7/guide/service/annotations/#aws-resource-tags[{aws} Resource Tags] in the [.noloc]`{aws} Load Balancer Controller` documentation.
+
[source,bash,subs="verbatim,attributes"]
----
service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags
----
* You can assign link:AWSEC2/latest/UserGuide/elastic-ip-addresses-eip.html[Elastic IP addresses,type="documentation"] to the Network Load Balancer by adding the following annotation. Replace the [.replaceable]`example values` with the `Allocation IDs` of your Elastic IP addresses. The number of `Allocation IDs` must match the number of subnets that are used for the load balancer. For more information, see the https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.7/guide/service/annotations/#eip-allocations[{aws} Load Balancer Controller] documentation.
+
[source,bash,subs="verbatim,attributes"]
----
service.beta.kubernetes.io/aws-load-balancer-eip-allocations: eipalloc-xxxxxxxxxxxxxxxxx,eipalloc-yyyyyyyyyyyyyyyyy
----
* Amazon EKS adds one inbound rule to the node's security group for client traffic and one rule for each load balancer subnet in the VPC for health checks for each Network Load Balancer that you create. Deployment of a service of type `LoadBalancer` can fail if Amazon EKS attempts to create rules that exceed the quota for the maximum number of rules allowed for a security group. For more information, see  link:vpc/latest/userguide/amazon-vpc-limits.html#vpc-limits-security-groups[Security groups,type="documentation"] in Amazon VPC quotas in the Amazon VPC User Guide. Consider the following options to minimize the chances of exceeding the maximum number of rules for a security group:
+
** Request an increase in your rules per security group quota. For more information, see link:servicequotas/latest/userguide/request-quota-increase.html[Requesting a quota increase,type="documentation"] in the Service Quotas User Guide.
** Use IP targets, rather than instance targets. With IP targets, you can share rules for the same target ports. You can manually specify load balancer subnets with an annotation. For more information, see https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.7/guide/service/annotations/[Annotations] on [.noloc]`GitHub`.
** Use an ingress, instead of a service of type `LoadBalancer`, to send traffic to your service. The {aws} Application Load Balancer requires fewer rules than Network Load Balancers. You can share an ALB across multiple ingresses. For more information, see <<alb-ingress>>. You can't share a Network Load Balancer across multiple services.
** Deploy your clusters to multiple accounts.
* If your [.noloc]`Pods` run on [.noloc]`Windows` in an Amazon EKS cluster, a single service with a load balancer can support up to 1024 back-end [.noloc]`Pods`. Each [.noloc]`Pod` has its own unique IP address.
* We recommend only creating new Network Load Balancers with the [.noloc]`{aws} Load Balancer Controller`. Attempting to replace existing Network Load Balancers created with the {aws} cloud provider load balancer controller can result in multiple Network Load Balancers that might cause application downtime.


[[network-load-balancer,network-load-balancer.title]]
== Create a network load balancer

You can create a network load balancer with IP or instance targets.

=== Create network load balancer -- IP Targets

* You can use IP targets with [.noloc]`Pods` deployed to Amazon EC2 nodes, Fargate, or Amazon EKS Hybrid Nodes. Your [.noloc]`Kubernetes` service must be created as type `LoadBalancer`. For more information, see https://kubernetes.io/docs/concepts/services-networking/service/#loadbalancer[Type LoadBalancer] in the [.noloc]`Kubernetes` documentation.  
+
To create a load balancer that uses IP targets, add the following annotations to a service manifest and deploy your service. The `external` value for `aws-load-balancer-type` is what causes the [.noloc]`{aws} Load Balancer Controller`, rather than the {aws} cloud provider load balancer controller, to create the Network Load Balancer. You can view a  <<network-load-balancing-service-sample-manifest,sample service manifest>> with the annotations.
+
[source,bash,subs="verbatim,attributes"]
----
service.beta.kubernetes.io/aws-load-balancer-type: "external"
service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
----
+
NOTE: If you're load balancing to `IPv6` [.noloc]`Pods`, add the following annotation. You can only load balance over `IPv6` to IP targets, not instance targets. Without this annotation, load balancing is over `IPv4`.
+
[source,bash,subs="verbatim,attributes"]
----
service.beta.kubernetes.io/aws-load-balancer-ip-address-type: dualstack
----
+
Network Load Balancers are created with the `internal` `aws-load-balancer-scheme`, by default. You can launch Network Load Balancers in any subnet in your cluster's VPC, including subnets that weren't specified when you created your cluster.
+
[.noloc]`Kubernetes` examines the route table for your subnets to identify whether they are public or private. Public subnets have a route directly to the internet using an internet gateway, but private subnets do not.  
+
If you want to create a Network Load Balancer in a public subnet to load balance to Amazon EC2 nodes (Fargate can only be private), specify `internet-facing` with the following annotation:
+
[source,bash,subs="verbatim,attributes"]
----
service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
----
+
NOTE: The `service.beta.kubernetes.io/aws-load-balancer-type: "nlb-ip"` annotation is still supported for backwards compatibility. However, we recommend using the previous annotations for new load balancers instead of `service.beta.kubernetes.io/aws-load-balancer-type: "nlb-ip"`.
+
IMPORTANT: Do not edit the annotations after creating your service. If you need to modify it, delete the service object and create it again with the desired value for this annotation.


=== Create network load balancer -- Instance Targets

* The {aws} cloud provider load balancer controller creates Network Load Balancers with instance targets only. Version `2.2.0` and later of the {aws} Load Balancer Controller also creates Network Load Balancers with instance targets. We recommend using it, rather than the {aws} cloud provider load balancer controller, to create new Network Load Balancers. You can use Network Load Balancer instance targets with [.noloc]`Pods` deployed to Amazon EC2 nodes, but not to Fargate. To load balance network traffic across [.noloc]`Pods` deployed to Fargate, you must use IP targets.  
+
To deploy a Network Load Balancer to a private subnet, your service specification must have the following annotations. You can view a <<network-load-balancing-service-sample-manifest,sample service manifest>> with the annotations. The `external` value for `aws-load-balancer-type` is what causes the {aws} Load Balancer Controller, rather than the {aws} cloud provider load balancer controller, to create the Network Load Balancer.
+
[source,bash,subs="verbatim,attributes"]
----
service.beta.kubernetes.io/aws-load-balancer-type: "external"
service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "instance"
----
+
Network Load Balancers are created with the `internal` `aws-load-balancer-scheme`, by default. For internal Network Load Balancers, your Amazon EKS cluster must be configured to use at least one private subnet in your VPC. [.noloc]`Kubernetes` examines the route table for your subnets to identify whether they are public or private. Public subnets have a route directly to the internet using an internet gateway, but private subnets do not.  
+
If you want to create an Network Load Balancer in a public subnet to load balance to Amazon EC2 nodes, specify `internet-facing` with the following annotation:
+
[source,bash,subs="verbatim,attributes"]
----
service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
----
+
IMPORTANT: Do not edit the annotations after creating your service. If you need to modify it, delete the service object and create it again with the desired value for this annotation.


[[load-balancer-sample-application,load-balancer-sample-application.title]]
== (Optional) Deploy a sample application

* At least one public or private subnet in your cluster VPC.
* Have the [.noloc]`{aws} Load Balancer Controller` deployed on your cluster. For more information, see <<aws-load-balancer-controller>>. We recommend version `2.7.2` or later.
. If you're deploying to Fargate, make sure you have an available private subnet in your VPC and create a Fargate profile. If you're not deploying to Fargate, skip this step. You can create the profile by running the following command or in the <<create-fargate-profile,{aws-management-console}>> using the same values for `name` and `namespace` that are in the command. Replace the [.replaceable]`example values` with your own.
+
[source,bash,subs="verbatim,attributes"]
----
eksctl create fargateprofile \
    --cluster my-cluster \
    --region region-code \
    --name nlb-sample-app \
    --namespace nlb-sample-app
----
. Deploy a sample application.
+
.. Create a namespace for the application.
+
[source,bash,subs="verbatim,attributes"]
----
kubectl create namespace nlb-sample-app
----
.. Save the following contents to a file named [.replaceable]`sample-deployment`.yaml` file on your computer.
+
[source,yaml,subs="verbatim,attributes"]
----
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nlb-sample-app
  namespace: nlb-sample-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: public.ecr.aws/nginx/nginx:1.23
          ports:
            - name: tcp
              containerPort: 80
----
.. Apply the manifest to the cluster.
+
[source,bash,subs="verbatim,attributes"]
----
kubectl apply -f sample-deployment.yaml
----
. Create a service with an internet-facing Network Load Balancer that load balances to IP targets. 
+
.. [[network-load-balancing-service-sample-manifest]]Save the following contents to a file named [.replaceable]`sample-service`.yaml` file on your computer. If you're deploying to Fargate nodes, remove the `service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing` line.
+
[source,yaml,subs="verbatim,attributes"]
----
apiVersion: v1
kind: Service
metadata:
  name: nlb-sample-service
  namespace: nlb-sample-app
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: LoadBalancer
  selector:
    app: nginx
----
.. Apply the manifest to the cluster.
+
[source,bash,subs="verbatim,attributes"]
----
kubectl apply -f sample-service.yaml
----
. [[nlb-sample-app-verify-deployment]]Verify that the service was deployed.
+
[source,bash,subs="verbatim,attributes"]
----
kubectl get svc nlb-sample-service -n nlb-sample-app
----
+
An example output is as follows.
+
[source,bash,subs="verbatim,attributes"]
----
NAME            TYPE           CLUSTER-IP         EXTERNAL-IP                                                                    PORT(S)        AGE
sample-service  LoadBalancer   10.100.240.137   k8s-nlbsampl-nlbsampl-xxxxxxxxxx-xxxxxxxxxxxxxxxx.elb.region-code.amazonaws.com  80:32400/TCP   16h
----
+
NOTE: The values for [.replaceable]`10.100.240.137` and [.replaceable]`xxxxxxxxxx`-[.replaceable]`xxxxxxxxxxxxxxxx` will be different than the example output (they will be unique to your load balancer) and [.replaceable]`us-west-2` may be different for you, depending on which {aws} Region that your cluster is in. 
. Open the link:ec2[Amazon EC2 {aws-management-console},type="console"]. Select *Target Groups* (under  *Load Balancing*) in the left navigation pane. In the  *Name* column, select the target group's name where the value in the  *Load balancer* column matches a portion of the name in the `EXTERNAL-IP` column of the output in the previous step. For example, you'd select the target group named `k8s-default-samplese-[.replaceable]``xxxxxxxxxx``` if your output were the same as the previous output. The *Target type* is `IP` because that was specified in the sample service manifest.
. Select the *Target group* and then select the  *Targets* tab. Under  *Registered targets*, you should see three IP addresses of the three replicas deployed in a previous step. Wait until the status of all targets is  *healthy* before continuing. It might take several minutes before all targets are `healthy`. The targets might be in an `unhealthy` state before changing to a `healthy` state.
. Send traffic to the service replacing [.replaceable]`xxxxxxxxxx-xxxxxxxxxxxxxxxx` and [.replaceable]`us-west-2` with the values returned in the output for a <<nlb-sample-app-verify-deployment,previous step>> for `EXTERNAL-IP`. If you deployed to a private subnet, then you'll need to view the page from a device within your VPC, such as a bastion host. For more information, see link:quickstart/architecture/linux-bastion/[Linux Bastion Hosts on {aws},type="marketing"].
+
[source,bash,subs="verbatim,attributes"]
----
curl k8s-default-samplese-xxxxxxxxxx-xxxxxxxxxxxxxxxx.elb.region-code.amazonaws.com
----
+
An example output is as follows.
+
[source,html,subs="verbatim"]
----
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
[...]
----
. When you're finished with the sample deployment, service, and namespace, remove them.
+
[source,bash,subs="verbatim,attributes"]
----
kubectl delete namespace nlb-sample-app
----


📝 https://github.com/search?q=repo:awsdocs/amazon-eks-user-guide+&#91;&#91;network-load-balancing,&type=code[Edit this page on GitHub]