//!!NODE_ROOT <chapter>
include::../attributes.txt[]
[[eks-connector,eks-connector.title]]
= Connect a [.noloc]`Kubernetes` cluster to an Amazon EKS Management Console with Amazon EKS Connector
:doctype: book
:sectnums:
:toc: left
:icons: font
:experimental:
:idprefix:
:idseparator: -
:sourcedir: .
:info_doctype: chapter
:info_title: Connect a Kubernetes cluster to an Amazon EKS Management Console with Amazon EKS Connector
:info_titleabbrev: Amazon EKS Connector
:info_abstract: Discover how to connect conformant Kubernetes clusters to {aws} and visualize them in the Amazon EKS console using the Amazon EKS Connector agent and required IAM roles.

[abstract]
--
Discover how to connect conformant [.noloc]`Kubernetes` clusters to {aws} and visualize them in the Amazon EKS console using the Amazon EKS Connector agent and required IAM roles.
--

You can use Amazon EKS Connector to register and connect any conformant [.noloc]`Kubernetes` cluster to {aws} and visualize it in the Amazon EKS console. After a cluster is connected, you can see the status, configuration, and workloads for that cluster in the Amazon EKS console. You can use this feature to view connected clusters in Amazon EKS console, but you can't manage them. The Amazon EKS Connector requires an agent that is an https://github.com/aws/amazon-eks-connector[open source project on Github]. For additional technical content, including frequently asked questions and troubleshooting, see <<troubleshooting-connector>>.


The Amazon EKS Connector can connect the following types of [.noloc]`Kubernetes` clusters to Amazon EKS.



* On-premises [.noloc]`Kubernetes` clusters
* Self-managed clusters that are running on Amazon EC2
* Managed clusters from other cloud providers


[[connect-cluster-reqts,connect-cluster-reqts.title]]
== Amazon EKS Connector considerations

Before you use Amazon EKS Connector, understand the following:



* You must have administrative privileges to the [.noloc]`Kubernetes` cluster to connect the cluster to Amazon EKS.
* The [.noloc]`Kubernetes` cluster must have [.noloc]`Linux` 64-bit (x86) worker nodes present before connecting. ARM worker nodes aren't supported.
* You must have worker nodes in your [.noloc]`Kubernetes` cluster that have outbound access to the `ssm.` and `ssmmessages.` Systems Manager endpoints. For more information, see link:general/latest/gr/ssm.html[Systems Manager endpoints,type="documentation"] in the _{aws} General Reference_.
* By default, you can connect up to 10 clusters in a Region. You can request an increase through the link:servicequotas/latest/userguide/request-quota-increase.html[service quota console,type="documentation"]. See link:servicequotas/latest/userguide/request-quota-increase.html[Requesting a quota increase,type="documentation"] for more information.
* Only the Amazon EKS `RegisterCluster`, `ListClusters`, `DescribeCluster`, and `DeregisterCluster` APIs are supported for external [.noloc]`Kubernetes` clusters.
* You must have the following permissions to register a cluster:
+
** eks:RegisterCluster 
** ssm:CreateActivation
** ssm:DeleteActivation
** iam:PassRole
* You must have the following permissions to deregister a cluster:
+
** eks:DeregisterCluster 
** ssm:DeleteActivation
** ssm:DeregisterManagedInstance


[[connector-iam-permissions,connector-iam-permissions.title]]
== Required IAM roles for Amazon EKS Connector

Using the Amazon EKS Connector requires the following two IAM roles:



* The <<using-service-linked-roles-eks-connector,Amazon EKS Connector>> service-linked role is created when you register a cluster for the first time.
* You must create the Amazon EKS Connector agent IAM role. See <<connector-iam-role>> for details.

To enable cluster and workload view permission for   link:IAM/latest/UserGuide/id_roles.html#iam-term-principal[IAM principals,type="documentation"], apply the `eks-connector` and Amazon EKS Connector cluster roles to your cluster. Follow the steps in <<connector-grant-access,Grant access to view Kubernetes cluster resources on an Amazon EKS console>>.

include::connecting-cluster.adoc[leveloffset=+1]


include::connector-grant-access.adoc[leveloffset=+1]


include::deregister-connected-cluster.adoc[leveloffset=+1]


include::troubleshooting-connector.adoc[leveloffset=+1]


include::tsc-faq.adoc[leveloffset=+1]


include::security-connector.adoc[leveloffset=+1]


📝 https://github.com/search?q=repo:awsdocs/amazon-eks-user-guide+&#91;&#91;eks-connector,&type=code[Edit this page on GitHub]