//!!NODE_ROOT <section>
[.topic]
[[eks-deployment-options,eks-deployment-options.title]]
= Deploy Amazon EKS clusters across cloud and on-premises environments
:info_doctype: section
:info_title: Deploy Amazon EKS clusters across cloud and on-premises environments
:info_titleabbrev: Deployment options
:keywords: Amazon Elastic Kubernetes Service, Amazon EKS, deployment, options, comparison
:info_abstract: Learn to deploy Kubernetes clusters with Amazon EKS across cloud and on-premises environments to meet your operational needs, while leveraging {aws} services and support.

include::../attributes.txt[]

[abstract]
--
Learn to deploy [.noloc]`Kubernetes` clusters with Amazon EKS across cloud and on-premises environments to meet your operational needs, while leveraging {aws} services and support.
--

[[understand-deployment-options,understand-deployment-options.title]]
== Understand Amazon EKS deployment options

Amazon Elastic Kubernetes Service (Amazon EKS) is a fully managed Kubernetes service that enables you to run Kubernetes seamlessly in the cloud and in your on-premises environments. 

In the cloud, Amazon EKS automates Kubernetes cluster infrastructure management for the Kubernetes control plane and nodes. This is essential for scheduling containers, managing application availability, dynamically scaling resources, optimizing compute, storing cluster data, and performing other critical functions. With Amazon EKS, you get the robust performance, scalability, reliability, and availability of {aws} infrastructure, along with native integrations with {aws} networking, security, storage, and observability services. 

To simplify running Kubernetes in your on-premises environments, you can use the same Amazon EKS clusters, features, and tools to <<eks-outposts-self-managed-nodes>> or link:eks/latest/userguide/hybrid-nodes-overview.html[Amazon EKS Hybrid Nodes,type="documentation"] on your own infrastructure, or you can use https://anywhere.eks.amazonaws.com/[Amazon EKS Anywhere]for self-contained air-gapped environments. 

[[eks-cloud-deployment-options,eks-cloud-deployment-options.title]]
== Amazon EKS in the cloud

You can use Amazon EKS with compute in {aws} Regions, {aws} Local Zones, and {aws} Wavelength Zones. With Amazon EKS in the cloud, the security, scalability, and availability of the Kubernetes control plane is fully managed by {aws} in the {aws} Region. When running applications with compute in {aws} Regions, you get the full breadth of {aws} and Amazon EKS features, including Amazon EKS Auto Mode, which fully automates Kubernetes cluster infrastructure management for compute, storage, and networking on {aws} with a single click. When running applications with compute in {aws} Local Zones and {aws} Wavelength Zones, you can use Amazon EKS self-managed nodes to connect Amazon EC2 instances for your cluster compute and can use the other available {aws} services in {aws} Local Zones and {aws} Wavelength Zones. For more information see https://aws.amazon.com/about-aws/global-infrastructure/localzones/features/[{aws} Local Zones features] and https://aws.amazon.com/wavelength/features/[{aws} Wavelength Zones features].

[cols="1,1,1", options="header"]
|===
|
|Amazon EKS in {aws} Regions
|Amazon EKS in Local/Wavelength Zones

|Kuberenetes control plane management
|{aws}-managed
|{aws}-managed

|Kubernetes control plane location
|{aws} Regions
|{aws} Regions

|Kubernetes data plane
a|* Amazon EKS Auto Mode
* Amazon EKS Managed Node Groups
* Amazon EC2 self-managed nodes
* {aws} Fargate
a|* Amazon EKS Managed Node Groups (Local Zones only)
* Amazon EC2 self-managed nodes

|Kubernetes data plane location
|{aws} Regions
|{aws} Local or Wavelength Zones
|===

[[dc-or-edge-deployment-options,dc-or-edge-deployment-options.title]]
== Amazon EKS in your data center or edge environments

If you need to run applications in your own data centers or edge environments, you can use <<eks-outposts>> or link:eks/latest/userguide/hybrid-nodes.html[Amazon EKS Hybrid Nodes,type="documentation"]. You can use self-managed nodes with Amazon EC2 instances on {aws} Outposts for your cluster compute, or you can use Amazon EKS Hybrid Nodes with your own on-premises or edge infrastructure for your cluster compute. {aws} Outposts is {aws}-managed infrastructure that you run in your data centers or co-location facilities, whereas Amazon EKS Hybrid Nodes runs on your physical or virtual machines that you manage in your on-premises or edge environments. Amazon EKS on {aws} Outposts and Amazon EKS Hybrid Nodes require a reliable connection from your on-premises environments to an {aws} Region, and you can use the same Amazon EKS clusters, features, and tools you use to run applications in the cloud. When running on {aws} Outposts, you can alternatively deploy the entire Kubernetes cluster on {aws} Outposts with Amazon EKS local clusters on {aws} Outposts.


[cols="1,1,1", options="header"]
|===
|
|Amazon EKS Hybrid Nodes
|Amazon EKS on {aws} Outposts

|Kuberenetes control plane management
|{aws}-managed
|{aws}-managed

|Kubernetes control plane location
|{aws} Regions
|{aws} Regions or {aws} Outposts

|Kubernetes data plane
|Customer-managed physical or virtual machines
|Amazon EC2 self-managed nodes

|Kubernetes data plane location
|Customer data center or edge environment
|Customer data center or edge environment
|===

[[air-gapped-deployment-options,air-gapped-deployment-options.title]]
== Amazon EKS Anywhere for air-gapped environments

https://aws.amazon.com/eks/eks-anywhere/[Amazon EKS Anywhere] simplifies Kubernetes cluster management through the automation of undifferentiated heavy lifting such as infrastructure setup and Kubernetes cluster lifecycle operations in on-premises and edge environments. Unlike Amazon EKS, Amazon EKS Anywhere is a customer-managed product and customers are responsible for cluster lifecycle operations and maintenance of Amazon EKS Anywhere clusters. Amazon EKS Anywhere is built on the Kubernetes sub-project Cluster API (CAPI) and supports a range of infrastructure including VMware vSphere, bare metal, Nutanix, Apache CloudStack, and {aws} Snow. Amazon EKS Anywhere can be run in air-gapped environments and offers optional integrations with regional {aws} services for observability and identity management. To receive support for Amazon EKS Anywhere and access to {aws}-vended Kubernetes add-ons, you can purchase https://aws.amazon.com/eks/eks-anywhere/pricing/[Amazon EKS Anywhere Enterprise Subscriptions].

[cols="1,1", options="header"]
|===
|
|Amazon EKS Anywhere

|Kuberenetes control plane management
|Customer-managed

|Kubernetes control plane location
|Customer data center or edge environment

|Kubernetes data plane
|Customer-managed physical or virtual machines

|Kubernetes data plane location
|Customer data center or edge environment
|===

[[tooling-deployment-options,tooling-deployment-options.title]]
== Amazon EKS tooling

You can use the <<eks-connector,Amazon EKS Connector>> to register and connect any conformant Kubernetes cluster to {aws} and view it in the Amazon EKS console. After a cluster is connected, you can see the status, configuration, and workloads for that cluster in the Amazon EKS console. You can use this feature to view connected clusters in Amazon EKS console, but the Amazon EKS Connector does not enable management or mutating operations for your connected clusters through the Amazon EKS console.

https://aws.amazon.com/eks/eks-distro/[Amazon EKS Distro] is the {aws} distribution of the underlying Kubernetes components that power all Amazon EKS offerings. It includes the core components required for a functioning Kubernetes cluster such as Kubernetes control plane components (etcd, kube-apiserver, kube-scheduler, kube-controller-manager) and networking components (CoreDNS, kube-proxy, CNI plugins). Amazon EKS Distro can be used to self-manage Kubernetes clusters with your choice of tooling. Amazon EKS Distro deployments are not covered by {aws} Support Plans.


📝 https://github.com/search?q=repo:awsdocs/amazon-eks-user-guide+&#91;&#91;eks-deployment-options,&type=code[Edit this page on GitHub]