//!!NODE_ROOT <section>
include::../attributes.txt[]

[.topic]
[[eks-architecture,eks-architecture.title]]
= Amazon EKS architecture
:info_doctype: section
:info_title: Amazon EKS architecture
:info_titleabbrev: Architecture
:keywords: Amazon Elastic Kubernetes Service, Amazon EKS, architecture, control plane, nodes, data plane
:info_abstract: Learn how Amazon EKS aligns with Kubernetes cluster architecture, offering a highly available and resilient control plane, and flexible compute options like {aws} Fargate, Karpenter, managed node groups, and self-managed nodes to meet diverse workload requirements.

[abstract]
--
Learn how Amazon EKS aligns with [.noloc]`Kubernetes` cluster architecture, offering a highly available and resilient control plane, and flexible compute options like {aws} Fargate, [.noloc]`Karpenter`, managed node groups, and self-managed nodes to meet diverse workload requirements.
--

Amazon EKS aligns with the general cluster architecture of [.noloc]`Kubernetes`. For more information, see https://kubernetes.io/docs/concepts/overview/components/[Kubernetes Components] in the [.noloc]`Kubernetes` documentation. The following sections summarize some extra architecture details for Amazon EKS.

[[control-plane,control-plane.title]]
== Control plane

Amazon EKS ensures every cluster has its own unique [.noloc]`Kubernetes` control plane. This design keeps each cluster's infrastructure separate, with no overlaps between clusters or {aws} accounts. The setup includes:



*Distributed components*::
The control plane positions at least two API server instances and three https://etcd.io/[etcd] instances across three {aws} Availability Zones within an {aws} Region.


*Optimal performance*::
Amazon EKS actively monitors and adjusts control plane instances to maintain peak performance.


*Resilience*::
If a control plane instance falters, Amazon EKS quickly replaces it, using different Availability Zone if needed.


*Consistent uptime*::
By running clusters across multiple  Availability Zones, a reliable link:eks/sla[API server endpoint availability Service Level Agreement (SLA),type="marketing"] is achieved.

Amazon EKS uses Amazon Virtual Private Cloud (Amazon VPC) to limit traffic between control plane components within a single cluster. Cluster components can't view or receive communication from other clusters or {aws} accounts, except when authorized by [.noloc]`Kubernetes` role-based access control (RBAC) policies.

[[nodes,nodes.title]]
== Compute

In addition to the control plane, an Amazon EKS cluster has a set of worker machines called nodes. Selecting the appropriate Amazon EKS cluster node type is crucial for meeting your specific requirements and optimizing resource utilization. Amazon EKS offers the following primary node types:

*EKS Auto Mode*::
xref:automode[EKS Auto Mode] extends {aws} management beyond the control plane to include the data plane, automating cluster infrastructure management. It integrates core Kubernetes capabilities as built-in components, including compute autoscaling, networking, load balancing, DNS, storage, and GPU support. EKS Auto Mode dynamically manages nodes based on workload demands, using immutable AMIs with enhanced security features. It automates updates and upgrades while respecting Pod Disruption Budgets, and includes managed components that would otherwise require add-on management. This option is ideal for users who want to leverage {aws} expertise for day-to-day operations, minimize operational overhead, and focus on application development rather than infrastructure management.

*{aws} Fargate*::
<<fargate,Fargate>> is a serverless compute engine for containers that eliminates the need to manage the underlying instances. With Fargate, you specify your application's resource needs, and {aws} automatically provisions, scales, and maintains the infrastructure. This option is ideal for users who prioritize ease-of-use and want to concentrate on application development and deployment rather than managing infrastructure.


*[.noloc]`Karpenter`*::
https://karpenter.sh/[Karpenter] is a flexible, high-performance [.noloc]`Kubernetes` cluster autoscaler that helps improve application availability and cluster efficiency. [.noloc]`Karpenter` launches right-sized compute resources in response to changing application load. This option can provision just-in-time compute resources that meet the requirements of your workload.


*Managed node groups*::
<<managed-node-groups,Managed node groups>> are a blend of automation and customization for managing a collection of Amazon EC2 instances within an Amazon EKS cluster. {aws} takes care of tasks like patching, updating, and scaling nodes, easing operational aspects. In parallel, custom `kubelet` arguments are supported, opening up possibilities for advanced CPU and memory management policies. Moreover, they enhance security via {aws} Identity and Access Management (IAM) roles for service accounts, while curbing the need for separate permissions per cluster.


*Self-managed nodes*::
<<worker,Self-managed nodes>> offer full control over your Amazon EC2 instances within an Amazon EKS cluster. You are in charge of managing, scaling, and maintaining the nodes, giving you total control over the underlying infrastructure. This option is suitable for users who need granular control and customization of their nodes and are ready to invest time in managing and maintaining their infrastructure.

*Amazon EKS Hybrid Nodes*::
With <<hybrid-nodes-overview,Amazon EKS Hybrid Nodes>>, you can use your on-premises and edge infrastructure as nodes in Amazon EKS clusters. Amazon EKS Hybrid Nodes unifies Kubernetes management across environments and offloads Kubernetes control plane management to {aws} for your on-premises and edge applications.


📝 https://github.com/search?q=repo:awsdocs/amazon-eks-user-guide+&#91;&#91;eks-architecture,&type=code[Edit this page on GitHub]