//!!NODE_ROOT <chapter>
include::../attributes.txt[]
[[getting-started,getting-started.title]]
= Get started with Amazon EKS
:doctype: book
:sectnums:
:toc: left
:icons: font
:experimental:
:idprefix:
:idseparator: -
:sourcedir: .
:info_doctype: chapter
:info_title: Get started with Amazon EKS
:info_titleabbrev: Get started
:info_abstract: Learn about the tools needed for creating and working with an Amazon EKS cluster.
:keywords: getting, started, tutorials, quick, start

[abstract]
--
Learn about the tools needed for creating and working with an Amazon EKS cluster.
--

Make sure that you are set up to use Amazon EKS before going through the getting started guides. For more information, see <<setting-up>>.

There are two getting started guides available for creating a new [.noloc]`Kubernetes` cluster with nodes in Amazon EKS:



* <<getting-started-eksctl,Get started with Amazon EKS – eksctl>> – This getting started guide helps you to install all of the required resources to get started with Amazon EKS using `eksctl`, a simple command line utility for creating and managing [.noloc]`Kubernetes` clusters on Amazon EKS. At the end of the tutorial, you will have a running Amazon EKS cluster that you can deploy applications to. This is the fastest and simplest way to get started with Amazon EKS.
* <<getting-started-console,Get started with Amazon EKS – {aws-management-console} and {aws} CLI>> – This getting started guide helps you to create all of the required resources to get started with Amazon EKS using the {aws-management-console} and {aws} CLI. At the end of the tutorial, you will have a running Amazon EKS cluster that you can deploy applications to. In this guide, you manually create each resource required for an Amazon EKS cluster. The procedures give you visibility into how each resource is created and how they interact with each other.

We also offer the following references:



* For a collection of hands-on tutorials, see https://community.aws/tags/eks-cluster-setup[EKS Cluster Setup] on _{aws} Community_.
* For code examples, see  link:code-library/latest/ug/eks_code_examples.html[Code examples for Amazon EKS using {aws} SDKs,type="documentation"].


include::getting-started-automode.adoc[leveloffset=+1]

include::getting-started-eksctl.adoc[leveloffset=+1]

include::getting-started-console.adoc[leveloffset=+1]


📝 https://github.com/search?q=repo:awsdocs/amazon-eks-user-guide+&#91;&#91;getting-started,&type=code[Edit this page on GitHub]