//!!NODE_ROOT <section>
include::../attributes.txt[]

[.topic]
[[install-awscli,install-awscli.title]]
= Set up {aws} CLI
:info_doctype: section
:info_title: Set up {aws} CLI
:info_titleabbrev: Set up {aws} CLI
:keywords: setting up, setup
:info_abstract: Set up the {aws} CLI for managing {aws} resources needed to use Amazon EKS. Follow these \
                instructions to set up the credentials with {aws} CLI.

[abstract]
--
Set up the {aws} CLI for managing {aws} resources needed to use Amazon EKS. Follow these instructions to set up the credentials with {aws} CLI.
--

The link:cli/[{aws} CLI,type="marketing"] is a command line tool for working with {aws} services, including Amazon EKS. It is also used to authenticate IAM users or roles for access to the Amazon EKS cluster and other {aws} resources from your local machine. To provision resources in {aws} from the command line, you need to obtain an {aws} access key ID and secret key to use in the command line. Then you need to configure these credentials in the {aws} CLI. If you haven't already installed the {aws} CLI, see link:cli/latest/userguide/cli-chap-install.html[Install or update the latest version of the {aws} CLI,type="documentation"] in the _{aws} Command Line Interface User Guide_.

[[create-access-key,create-access-key.title]]
== To create an access key
. Sign into the https://console.aws.amazon.com/[{aws-management-console}].
. For single-user or multiple-user accounts:
+
** *Single-user account –*::
 In the top right, choose your {aws} user name to open the navigation menu. For example, choose  *`webadmin`*.
** *Multiple-user account –*::
 Choose IAM from the list of services. From the IAM Dashboard, select  *Users*, and choose the name of the user.
. Choose *Security credentials*.
. Under *Access keys*, choose  *Create access key*.
. Choose *Command Line Interface (CLI)*, then choose  *Next*.
. Choose *Create access key*.
. Choose *Download .csv file*.


[[configure-cli,configure-cli.title]]
== To configure the {aws} CLI

After installing the {aws} CLI, do the following steps to configure it. For more information, see link:cli/latest/userguide/cli-chap-configure.html[Configure the {aws} CLI,type="documentation"] in the _{aws} Command Line Interface User Guide_.

. In a terminal window, enter the following command:
+
[source,bash,subs="verbatim,attributes"]
----
aws configure
----
+
Optionally, you can configure a named profile, such as `--profile cluster-admin`. If you configure a named profile in the {aws} CLI, you must *always* pass this flag in subsequent commands.
. Enter your {aws} credentials. For example:
+
[source,bash,subs="verbatim,attributes"]
----
Access Key ID [None]: AKIAIOSFODNN7EXAMPLE
Secret Access Key [None]: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
Default region name [None]: region-code
Default output format [None]: json
----


[[security-token,security-token.title]]
== To get a security token

If needed, run the following command to get a new security token for the {aws} CLI. For more information, see link:cli/latest/reference/sts/get-session-token.html[get-session-token,type="documentation"] in the _{aws} CLI Command Reference_.

By default, the token is valid for 15 minutes. To change the default session timeout, pass the `--duration-seconds` flag. For example:

[source,bash,subs="verbatim,attributes"]
----
aws sts get-session-token --duration-seconds 3600
----

This command returns the temporary security credentials for an {aws} CLI session. You should see the following response output:

[source,bash,subs="verbatim,attributes"]
----
{
    "Credentials": {
        "AccessKeyId": "ASIA5FTRU3LOEXAMPLE",
        "SecretAccessKey": "JnKgvwfqUD9mNsPoi9IbxAYEXAMPLE",
        "SessionToken": "VERYLONGSESSIONTOKENSTRING",
        "Expiration": "2023-02-17T03:14:24+00:00"
    }
}
----


[[verify-identity,verify-identity.title]]
== To verify the user identity

If needed, run the following command to verify the {aws} credentials for your IAM user identity (such as [.replaceable]`ClusterAdmin`) for the terminal session.

[source,bash,subs="verbatim,attributes"]
----
aws sts get-caller-identity
----

This command returns the Amazon Resource Name (ARN) of the IAM entity that's configured for the {aws} CLI. You should see the following example response output:

[source,bash,subs="verbatim,attributes"]
----
{
    "UserId": "AKIAIOSFODNN7EXAMPLE",
    "Account": "01234567890",
    "Arn": "{arn-aws}iam::01234567890:user/ClusterAdmin"
}
----


[[install-awscli-next-steps,install-awscli-next-steps.title]]
== Next steps

* <<install-kubectl,Set up kubectl and eksctl>>
* <<quickstart,Quickstart: Deploy a web app and store data>>
