include::../attributes.txt[]

[.topic]
[#delete-cluster]
= Delete a cluster
:info_titleabbrev: Delete a cluster

[abstract]
--
Learn how to delete Amazon EKS clusters, including managed and self-managed node groups, Fargate profiles, related services, and {aws} CloudFormation stacks using eksctl, {aws-management-console}, or {aws} CLI for cost optimization and resource cleanup.
--

When you're done using an Amazon EKS cluster, you should delete the resources associated with it so that you don't incur any unnecessary costs.



You can delete a cluster with `eksctl`, the {aws-management-console}, or the {aws} CLI.

== Considerations

* If you receive an error because the cluster creator has been removed, see link:premiumsupport/knowledge-center/eks-api-server-unauthorized-error[this article,type="marketing"] to resolve.
* Amazon Managed Service for Prometheus resources are outside of the cluster lifecycle and need to be maintained independent of the cluster. When you delete your cluster, make sure to also delete any applicable scrapers to stop applicable costs. For more information, see link:prometheus/latest/userguide/AMP-collector-how-to.html#AMP-collector-list-delete[Find and delete scrapers,type="documentation"] in the _Amazon Managed Service for Prometheus User Guide_.
* To remove a connected cluster, see <<deregister-connected-cluster>>
* Before you can delete a cluster, make sure deletion protection is disabled for your cluster.

=== Considerations for EKS Auto Mode

* Any EKS Auto Mode Nodes will be deleted, including the EC2 managed instances
* All load balancers will be deleted

For more information, see <<auto-disable>>. 

[#prerequisite-steps]
== Prerequisite steps

The following are steps that you must first perform before you can delete a cluster. These steps apply regardless of the method that you use to delete your cluster.

. List all services running in your cluster.
+
[source,bash,subs="verbatim,attributes"]
----
kubectl get svc --all-namespaces
----

. Delete any services that have an associated `EXTERNAL-IP` value. These services are fronted by an Elastic Load Balancing load balancer, and you must delete them in Kubernetes to allow the load balancer and associated resources to be properly released.
Replace [.replaceable]`service-name` with the name of each service listed as described.
+
[source,bash,subs="verbatim,attributes"]
----
kubectl delete svc service-name
----

. Delete any ingress resources as well. If you don't delete the ingress resources, the application load balancer remains even if you deleted the cluster. Replace [.replaceable]`ingress-name` with the name of your ingress resources.
+
[source,bash,subs="verbatim,attributes"]
----
kubectl get ingress --all-namespaces
----
+
[source,bash,subs="verbatim,attributes"]
----
kubectl delete ing ingress-name
----


== Delete cluster (eksctl)

This procedure requires `eksctl` version `{eksctl-min-version}` or later. You can check your version with the following command:

[source,bash,subs="verbatim,attributes"]
----
eksctl version
----

For instructions on how to install or upgrade `eksctl`, see https://eksctl.io/installation[Installation] in the `eksctl` documentation.

. Go through the <<prerequisite-steps, prerequisite steps>>. After doing so, delete your cluster and its associated nodes with the following command, replacing [.replaceable]`prod` with your cluster name.
+
[source,bash,subs="verbatim,attributes"]
----
eksctl delete cluster --name prod
----
+
Output:
+
[source,bash,subs="verbatim,attributes"]
----
[ℹ]  using region region-code
[ℹ]  deleting EKS cluster "prod"
[ℹ]  will delete stack "eksctl-prod-nodegroup-standard-nodes"
[ℹ]  waiting for stack "eksctl-prod-nodegroup-standard-nodes" to get deleted
[ℹ]  will delete stack "eksctl-prod-cluster"
[✔]  the following EKS cluster resource(s) for "prod" will be deleted: cluster. If in doubt, check CloudFormation console
----


== Delete cluster ({aws} console)
. Go through the <<prerequisite-steps, prerequisite steps>>. After doing so, delete all node groups and Fargate profiles.
+
.. Open the link:eks/home#/clusters[Amazon EKS console,type="console"].
.. In the left navigation pane, choose Amazon EKS *Clusters*, and then in the tabbed list of clusters, choose the name of the cluster that you want to delete.
.. Choose the *Compute* tab and choose a node group to delete. Choose *Delete*, enter the name of the node group, and then choose *Delete*. Delete all node groups in the cluster.
+
NOTE: The node groups listed are <<managed-node-groups,managed node groups>> only.
.. Choose a *Fargate Profile* to delete, select *Delete*, enter the name of the profile, and then choose *Delete*. Delete all Fargate profiles in the cluster.
. Delete all link:eks/latest/userguide/worker[self-managed node {aws} CloudFormation stacks,type="documentation"].
+
.. Open the link:cloudformation/[{aws} CloudFormation console,type="console"].
.. Choose the node stack to delete, and then choose *Delete*.
.. In the *Delete stack* confirmation dialog box, choose *Delete stack*. Delete all self-managed node stacks in the cluster.
. Delete the cluster.
+
.. Open the link:eks/home#/clusters[Amazon EKS console,type="console"].
.. Choose the cluster to delete and choose *Delete*.
.. On the delete cluster confirmation screen, choose *Delete*.
. (Optional) Delete the VPC {aws} CloudFormation stack.
+
.. Open the link:cloudformation/[{aws} CloudFormation console,type="console"].
.. Select the VPC stack to delete, and then choose *Delete*.
.. In the *Delete stack* confirmation dialog box, choose *Delete stack*.


== Delete cluster ({aws} CLI)

. Go through the <<prerequisite-steps, prerequisite steps>>. After doing so, delete all node groups and Fargate profiles.
+
.. List the node groups in your cluster with the following command.
+
[source,bash,subs="verbatim,attributes"]
----
aws eks list-nodegroups --cluster-name my-cluster
----
+
NOTE: The node groups listed are <<managed-node-groups,managed node groups>> only.
.. Delete each node group with the following command. Delete all node groups in the cluster.
+
[source,bash,subs="verbatim,attributes"]
----
aws eks delete-nodegroup --nodegroup-name my-nodegroup --cluster-name my-cluster
----
.. List the Fargate profiles in your cluster with the following command.
+
[source,bash,subs="verbatim,attributes"]
----
aws eks list-fargate-profiles --cluster-name my-cluster
----
.. Delete each Fargate profile with the following command. Delete all Fargate profiles in the cluster.
+
[source,bash,subs="verbatim,attributes"]
----
aws eks delete-fargate-profile --fargate-profile-name my-fargate-profile --cluster-name my-cluster
----
. Delete all link:eks/latest/userguide/worker[self-managed node {aws} CloudFormation stacks,type="documentation"].
+
.. List your available {aws} CloudFormation stacks with the following command. Find the node template name in the resulting output.
+
[source,bash,subs="verbatim,attributes"]
----
aws cloudformation list-stacks --query "StackSummaries[].StackName"
----
.. Delete each node stack with the following command, replacing [.replaceable]`node-stack` with your node stack name. Delete all self-managed node stacks in the cluster.
+
[source,bash,subs="verbatim,attributes"]
----
aws cloudformation delete-stack --stack-name node-stack
----
. Delete the cluster with the following command, replacing [.replaceable]`my-cluster` with your cluster name.
+
[source,bash,subs="verbatim,attributes"]
----
aws eks delete-cluster --name my-cluster
----
. (Optional) Delete the VPC {aws} CloudFormation stack.
+
.. List your available {aws} CloudFormation stacks with the following command. Find the VPC template name in the resulting output.
+
[source,bash,subs="verbatim,attributes"]
----
aws cloudformation list-stacks --query "StackSummaries[].StackName"
----
.. Delete the VPC stack with the following command, replacing [.replaceable]`my-vpc-stack` with your VPC stack name.
+
[source,bash,subs="verbatim,attributes"]
----
aws cloudformation delete-stack --stack-name my-vpc-stack
----

include::deletion-protection.adoc[leveloffset=+1]
