//!!NODE_ROOT <section>

[.topic]
[[kubernetes-versions,kubernetes-versions.title]]
= Understand the [.noloc]`Kubernetes` version lifecycle on EKS
:info_doctype: section
:info_title: Understand the Kubernetes version lifecycle on EKS
:info_titleabbrev: Kubernetes versions
:keywords: Amazon EKS, available, Kubernetes, version, release notes
:info_abstract: Learn how Amazon EKS supports Kubernetes versions with standard and extended \
                support periods, allowing you to proactively update clusters with the latest \
                versions, features, and security patches..


include::../attributes.txt[]

[abstract]
--
Learn how Amazon EKS supports Kubernetes versions with standard and extended support periods, allowing you to proactively update clusters with the latest versions, features, and security patches..
--

[.noloc]`Kubernetes` rapidly evolves with new features, design updates, and bug fixes. The community releases new [.noloc]`Kubernetes` minor versions (such as `1.30`) on average once every four months. Amazon EKS follows the upstream release and deprecation cycle for minor versions. As new [.noloc]`Kubernetes` versions become available in Amazon EKS, we recommend that you proactively update your clusters to use the latest available version.

A minor version is under standard support in Amazon EKS for the first 14 months after it's released. Once a version is past the end of standard support date, it enters extended support for the next 12 months. Extended support allows you to stay at a specific [.noloc]`Kubernetes` version for longer at an additional cost per cluster hour. If you haven't updated your cluster before the extended support period ends, your cluster is auto-upgraded to the oldest currently supported extended version.

Extended support is enabled by default. <<disable-extended-support>>

We recommend that you create your cluster with the latest available [.noloc]`Kubernetes` version supported by Amazon EKS. If your application requires a specific version of [.noloc]`Kubernetes`, you can select older versions. You can create new Amazon EKS clusters on any version offered in standard or extended support.



video::_dJdAZ_J_jw[youtube,align = center,height = 405,fileref = https://www.youtube.com/embed/_dJdAZ_J_jw,width = 720]


[[available-versions,available-versions.title]]
== Available versions on standard support

The following [.noloc]`Kubernetes` versions are currently available in Amazon EKS standard support:


* `1.31`
* `1.30`
* `1.29`

For important changes to be aware of for each version in standard support, see <<kubernetes-versions-standard>>.

[[available-versions-extended,available-versions-extended.title]]
== Available versions on extended support

The following [.noloc]`Kubernetes` versions are currently available in Amazon EKS extended support:


* `1.28`
* `1.27`
* `1.26`
* `1.25`
* `1.24`

For important changes to be aware of for each version in extended support, see <<kubernetes-versions-extended>>.

[[kubernetes-release-calendar,kubernetes-release-calendar.title]]
== Amazon EKS [.noloc]`Kubernetes` release calendar

The following table shows important release and support dates to consider for each [.noloc]`Kubernetes` version. Billing for extended support starts at the beginning of the day that the version reaches end of standard support.

[NOTE]
====

Dates with only a month and a year are approximate and are updated with an exact date when it's known.

====

[cols="1,1,1,1,1", options="header"]
|===
|Kubernetes version
|Upstream release
|Amazon EKS release
|End of standard support
|End of extended support


|`1.31`
|August 13, 2024
|September 26, 2024
|November 26, 2025
|November 26, 2026

|`1.30`
|April 17, 2024
|May 23, 2024
|July 23, 2025
|July 23, 2026

|`1.29`
|December 13, 2023
|January 23, 2024
|March 23, 2025 
|March 23, 2026

|`1.28`
|August 15, 2023
|September 26, 2023
|November 26, 2024 
|November 26, 2025

|`1.27`
|April 11, 2023
|May 24, 2023
|July 24, 2024
|July 24, 2025

|`1.26`
|December 9, 2022
|April 11, 2023
|June 11, 2024
|June 11, 2025

|`1.25`
|August 23, 2022
|February 22, 2023
|May 1, 2024
|May 1, 2025

|`1.24`
|May 3, 2022
|November 15, 2022
|January 31, 2024
|January 31, 2025

|===

[[version-faqs,version-faqs.title]]
== Amazon EKS version FAQs

*How many [.noloc]`Kubernetes` versions are available in standard support?*::
In line with the [.noloc]`Kubernetes` community support for [.noloc]`Kubernetes` versions, Amazon EKS is committed to offering support for three [.noloc]`Kubernetes` versions at any given time. We will announce the end of standard support date of a given [.noloc]`Kubernetes` minor version at least 60 days in advance. Because of the Amazon EKS qualification and release process for new [.noloc]`Kubernetes` versions, the end of standard support date of a [.noloc]`Kubernetes` version on Amazon EKS will be after the date that the [.noloc]`Kubernetes` project stops supporting the version upstream.

*How long does a [.noloc]`Kubernetes` receive standard support by Amazon EKS?*::
A [.noloc]`Kubernetes` version received standard support for 14 months after first being available on Amazon EKS. This is true even if upstream [.noloc]`Kubernetes` no longer support a version that's available on Amazon EKS. We backport security patches that are applicable to the [.noloc]`Kubernetes` versions that are supported on Amazon EKS.


*Am I notified when standard support is ending for a [.noloc]`Kubernetes` version on Amazon EKS?*::
Yes. If any clusters in your account are running the version nearing the end of support, Amazon EKS sends out a notice through the {aws} Health Dashboard approximately 12 months after the [.noloc]`Kubernetes` version was released on Amazon EKS. The notice includes the end of support date. This is at least 60 days from the date of the notice.


*Which [.noloc]`Kubernetes` features are supported by Amazon EKS?*::
Amazon EKS supports all generally available (GA) features of the [.noloc]`Kubernetes` API. Starting with [.noloc]`Kubernetes` version `1.24`, new beta APIs aren't enabled in clusters by default. However, previously existing beta APIs and new versions of existing beta APIs continue to be enabled by default. Alpha features aren't supported.


*Are Amazon EKS managed node groups automatically updated along with the cluster control plane version?*::
No. A managed node group creates Amazon EC2 instances in your account. These instances aren't automatically upgraded when you or Amazon EKS update your control plane. For more information, see <<update-managed-node-group>>. We recommend maintaining the same [.noloc]`Kubernetes` version on your control plane and nodes.


*Are self-managed node groups automatically updated along with the cluster control plane version?*::
No. A self-managed node group includes Amazon EC2 instances in your account. These instances aren't automatically upgraded when you or Amazon EKS update the control plane version on your behalf. A self-managed node group doesn't have any indication in the console that it needs updating. You can view the `kubelet` version installed on a node by selecting the node in the *Nodes* list on the  *Overview* tab of your cluster to determine which nodes need updating. You must manually update the nodes. For more information, see <<update-workers>>.
+
The [.noloc]`Kubernetes` project tests compatibility between the control plane and nodes for up to three minor versions. For example, `1.27` nodes continue to operate when orchestrated by a `1.30` control plane. However, running a cluster with nodes that are persistently three minor versions behind the control plane isn't recommended. For more information, see https://kubernetes.io/docs/setup/version-skew-policy/[Kubernetes version and version skew support policy] in the [.noloc]`Kubernetes` documentation. We recommend maintaining the same [.noloc]`Kubernetes` version on your control plane and nodes.


*Are [.noloc]`Pods` running on Fargate automatically upgraded with an automatic cluster control plane version upgrade?*::
No. We strongly recommend running Fargate [.noloc]`Pods` as part of a replication controller, such as a [.noloc]`Kubernetes` deployment. Then do a rolling restart of all Fargate [.noloc]`Pods`. The new version of the Fargate [.noloc]`Pod` is deployed with a `kubelet` version that's the same version as your updated cluster control plane version. For more information, see https://kubernetes.io/docs/concepts/workloads/controllers/deployment[Deployments] in the [.noloc]`Kubernetes` documentation.
+
IMPORTANT: If you update the control plane, you must still update the Fargate nodes yourself. To update Fargate nodes, delete the Fargate [.noloc]`Pod` represented by the node and redeploy the [.noloc]`Pod`. The new [.noloc]`Pod` is deployed with a `kubelet` version that's the same version as your cluster.


*What Kubernetes versions are supported for hybrid nodes?*::
Amazon EKS Hybrid Nodes supports the same Kubernetes versions as Amazon EKS clusters with other node compute types, including standard and extended Kubernetes version support. Hybrid nodes are not automatically upgraded when you upgrade your control plane version and you are responsible for upgrading your hybrid nodes. For more information, see <<hybrid-nodes-upgrade>>.


[[extended-support-faqs,extended-support-faqs.title]]
== Amazon EKS extended support FAQs

*The standard support and extended support terminology is new to me. What do those terms mean?*::
Standard support for a [.noloc]`Kubernetes` version in Amazon EKS begins when a [.noloc]`Kubernetes` version is released on Amazon EKS, and will end 14 months after the release date. Extended support for a [.noloc]`Kubernetes` version will begin immediately after the end of standard support, and will end after the next 12 months. For example, standard support for version `1.23` in Amazon EKS ends on October 11, 2023. Extended support for version `1.23` began on October 12, 2023 and will end on October 11, 2024.


*What do I need to do to get extended support for Amazon EKS clusters?*::
You will need to enable extended support (see <<enable-extended-support>>) for your cluster by changing the cluster upgrade policy to EXTENDED. By default, for all new and existing clusters, the upgrade policy is set to EXTENDED, unless specified otherwise. See <<view-upgrade-policy>> to view the upgrade policy for your cluster. Standard support will begin when a [.noloc]`Kubernetes` version is released on Amazon EKS, and will end 14 months after the release date. Extended support for a [.noloc]`Kubernetes` version will begin immediately after the end of standard support, and will end after the next 12 months.  


*For which [.noloc]`Kubernetes` versions can I get extended support?*::
Extended support is available for [.noloc]`Kubernetes` versions `1.23` and higher. You can run clusters on any version for up to 12 months after the end of standard support for that version. This means that each version will be supported for 26 months in Amazon EKS (14 months of standard support plus 12 months of extended support).


*What if I don't want to use extended support?*::
If you don't want to be automatically enrolled in extended support, you can upgrade your cluster to a [.noloc]`Kubernetes` version that's in standard Amazon EKS support. See <<disable-extended-support>> to learn how to disable extended support. Note: If you disable extended support, your cluster will be auto upgraded at the end of standard support.


*What will happen at the end of 12 months of extended support?*::
Clusters running on a [.noloc]`Kubernetes` version that has completed its 26-month lifecycle (14 months of standard support plus 12 months of extended support) will be auto-upgraded to the next version. The auto-upgrade includes only the Kubernetes control plane. If you have EKS Auto Mode nodes, they may automatically update. Self managed nodes and EKS Managed Node Groups will remain on the previous version.
+
On the end of extended support date, you can no longer create new Amazon EKS clusters with the unsupported version. Existing control planes are automatically updated by Amazon EKS to the earliest supported version through a gradual deployment process after the end of support date. After the automatic control plane update, make sure to manually update cluster add-ons and Amazon EC2 nodes. For more information, see <<update-cluster>>.


*When exactly is my control plane automatically updated after the end of extended support date?*::
Amazon EKS can't provide specific time frames. Automatic updates can happen at any time after the end of extended support date. You won't receive any notification before the update. We recommend that you proactively update your control plane without relying on the Amazon EKS automatic update process. For more information, see <<update-cluster>>.


*Can I leave my control plane on a [.noloc]`Kubernetes` version indefinitely?*::
No. Cloud security at {aws} is the highest priority. Past a certain point (usually one year), the [.noloc]`Kubernetes` community stops releasing common vulnerabilities and exposures ([.noloc]`CVE`) patches and discourages CVE submission for unsupported versions. This means that vulnerabilities specific to an older version of [.noloc]`Kubernetes` might not even be reported. This leaves clusters exposed with no notice and no remediation options in the event of a vulnerability. Given this, Amazon EKS doesn't allow control planes to stay on a version that reached end of extended support.


*Is there additional cost to get extended support?*::
Yes, there is additional cost for Amazon EKS clusters running in extended support. For pricing details, see link:containers/amazon-eks-extended-support-for-kubernetes-versions-pricing[Amazon EKS extended support for Kubernetes version pricing,type="blog"] on the {aws} blog or our https://aws.amazon.com/eks/pricing/[pricing page].


*What is included in extended support?*::
Amazon EKS clusters in Extended Support receive ongoing security patches for the [.noloc]`Kubernetes` control plane. Additionally, Amazon EKS will release patches for the Amazon VPC CNI, `kube-proxy`, and [.noloc]`CoreDNS` add-ons for Extended Support versions. Amazon EKS will also release patches for {aws}-published Amazon EKS optimized AMIs for Amazon Linux, [.noloc]`Bottlerocket`, and Windows, as well as Amazon EKS Fargate nodes for those versions. All clusters in Extended Support will continue to get access to technical support from {aws}.
+
NOTE: Extended Support for Amazon EKS optimized [.noloc]`Windows` AMIs that are published by {aws} isn't available for [.noloc]`Kubernetes` version `1.23` but is available for [.noloc]`Kubernetes` version `1.24` and higher.


*Are there any limitations to patches for non-[.noloc]`Kubernetes` components in extended support?*::
While Extended Support covers all of the [.noloc]`Kubernetes` specific components from {aws}, it will only provide support for {aws}-published Amazon EKS optimized AMIs for Amazon Linux, [.noloc]`Bottlerocket`, and Windows at all times. This means, you will potentially have newer components (such as OS or kernel) on your Amazon EKS optimized AMI while using Extended Support. For example, once Amazon Linux 2 reaches the link:amazon-linux-2/faqs/[end of its lifecycle in 2025,type="marketing"], the Amazon EKS optimized Amazon Linux AMIs will be built using a newer Amazon Linux OS. Amazon EKS will announce and document important support lifecycle discrepancies such as this for each [.noloc]`Kubernetes` version.


*Can I create new clusters using a version on extended support?*::
Yes.

include::kubernetes-versions-standard.adoc[leveloffset=+1]

include::kubernetes-versions-extended.adoc[leveloffset=+1]

include::view-support-status.adoc[leveloffset=+1]

include::view-upgrade-policy.adoc[leveloffset=+1]

include::enable-extended-support.adoc[leveloffset=+1]

include::disable-extended-support.adoc[leveloffset=+1]


📝 https://github.com/search?q=repo:awsdocs/amazon-eks-user-guide+&#91;&#91;kubernetes-versions,&type=code[Edit this page on GitHub]