//!!NODE_ROOT <section>

[.topic]
[[ml-prepare-for-cluster,ml-prepare-for-cluster.title]]
= Prepare for ML clusters
:info_doctype: section
:info_title: Prepare to create an EKS cluster for Machine Learning
:info_titleabbrev: Prepare for ML
:info_abstract: Learn how to make decisions about CPU, AMIs, and tooling before creating an EKS cluster for ML.

include::../attributes.txt[]


[abstract]
--
Learn how to make decisions about CPU, AMIs, and tooling before creating an EKS cluster for ML.
--

There are ways that you can enhance your Machine Learning on EKS experience. 
Following pages in this section will help you:

* Understand your choices for using ML on EKS and
* Help in preparation of your EKS and ML environment.

In particular, this will help you:

* *Choose AMIs*: {aws} offers multiple customized AMIs for running ML workloads on EKS. See <<ml-eks-optimized-ami>> and  <<ml-eks-windows-optimized-ami>>.
* *Customize AMIs*: You can further modify {aws} custom AMIs to add other software and drivers needed for your particular use cases. See <<capacity-blocks>>.
* *Reserve GPUs*: Because of the demand for GPUs, to ensure that the GPUs you need are available when you need them, you can reserve the GPUs you need in advance. See <<node-taints-managed-node-groups>>.
* *Add EFA*: Add the Elastic Fabric Adapter to improve network performance for inter-node cluster communications. See <<node-efa>>.
* *Use AWSInferentia workloads*: Create an EKS cluster with Amazon EC2 Inf1 instances. See <<inferentia-support>>.

[.topiclist]
[[Topic List]]

include::ml-eks-optimized-ami.adoc[leveloffset=+1]

include::ml-eks-windows-optimized-ami.adoc[leveloffset=+1]

include::capacity-blocks-mng.adoc[leveloffset=+1]

include::capacity-blocks.adoc[leveloffset=+1]

include::node-taints-managed-node-groups.adoc[leveloffset=+1]

include::node-efa.adoc[leveloffset=+1]

include::inferentia-support.adoc[leveloffset=+1]
