//!!NODE_ROOT <section>

[.topic]
[[auto-enable-existing,auto-enable-existing.title]]
= Enable EKS Auto Mode on an existing cluster
:info_doctype: section
:info_title: Enable EKS Auto Mode on an existing cluster
:info_titleabbrev: Enable on cluster
:info_abstract: Enable EKS Auto Mode on an existing cluster

include::../attributes.txt[]

This topic describes how to enable Amazon EKS Auto Mode on your existing Amazon EKS clusters. Enabling Auto Mode on an existing cluster requires updating IAM permissions and configuring core EKS Auto Mode settings. Once enabled, you can begin migrating your existing compute workloads to take advantage of Auto Mode's simplified operations and automated infrastructure management.

[IMPORTANT]
====
Verify you have the minimum required version of certain Amazon EKS Add-ons installed before enabling EKS Auto Mode. For more information, see <<auto-addons-required>>.
====


Before you begin, ensure you have administrator access to your Amazon EKS cluster and permissions to modify IAM roles. The steps in this topic guide you through enabling Auto Mode using either the {aws} Management Console or {aws} CLI.

== {aws} Management Console

You must be logged into the {aws} console with permission to manage IAM, EKS, and EC2 resources. 

[NOTE]
====
The Cluster IAM role of an EKS Cluster cannot be changed after the cluster is created. {eam} requires additional permissions on this role. You must attach additional policies to the current role. 
====

=== Update Cluster IAM Role

. Open your cluster overview page in the {aws} Management Console. 
. Under *Cluster IAM role ARN*, select *View in IAM*. 
. From the *Add Permissions* dropdown, select *Attach Policies*.
. Use the *Search* box to find and select the following policies:
** `AmazonEKSComputePolicy`
** `AmazonEKSBlockStoragePolicy`
** `AmazonEKSLoadBalancingPolicy`
** `AmazonEKSNetworkingPolicy`
** `AmazonEKSClusterPolicy`
. Select *Add permissions*
. From the *Trust relationships* tab, select *Edit trust policy*
. Insert the following Cluster IAM Role trust policy, and select *Update policy*

[source,json]
----
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "Service": "eks.amazonaws.com"
      },
      "Action": [
        "sts:AssumeRole",
        "sts:TagSession"
      ]
    }
  ]
}
----


=== Enable {eam} 

. Open your cluster overview page in the {aws} Management Console. 
. Under *EKS Auto Mode* select *Manage*
. Toggle *EKS Auto Mode* to on. 
. From the *EKS Node Pool* dropdown, select the default node pools you want to create. 
** Learn more about Node Pools in {eam}. For more information, see <<create-node-pool>>.
. If you have previously created an {eam} Node IAM role this {aws} account, select it in the *Node IAM Role* dropdown. If you have not created this role before, select *Create {recd} Role* and follow the steps. 


== {aws} CLI

=== Prerequisites
* The Cluster IAM Role of the existing EKS Cluster must include sufficent permissiosn for {eam}, such as the following policies:
** `AmazonEKSComputePolicy`
** `AmazonEKSBlockStoragePolicy`
** `AmazonEKSLoadBalancingPolicy`
** `AmazonEKSNetworkingPolicy`
** `AmazonEKSClusterPolicy`
* The Cluster IAM Role must have an updated trust policy including the `sts:TagSession` action. For more information on creating a Cluster IAM Role, see <<automode-get-started-cli>>.
* `aws` CLI installed, logged in, and a sufficent version. You must have permission to manage IAM, EKS, and EC2 resources. For more information, see <<setting-up>>.

=== Procedure

Use the following commands to enable {eam} on an existing cluster. 

[NOTE]
====
The compute, block storage, and load balancing capabilities must all be enabled or disabled in the same request. 
====

[source,cli]
----
aws eks update-cluster-config \
 --name $CLUSTER_NAME \
 --compute-config enabled=true \
 --kubernetes-network-config '{"elasticLoadBalancing":{"enabled": true}}' \
 --storage-config '{"blockStorage":{"enabled": true}}'
----

[[auto-addons-required,auto-addons-required.title]]
== Required Add-on Versions

If you're planning to enable EKS Auto Mode on an existing cluster, you may need to update certain add-ons. Please note:

- This applies only to existing clusters transitioning to EKS Auto Mode.
- New clusters created with EKS Auto Mode enabled don't require these updates.

If you have any of the following add-ons installed, ensure they are at least at the specified minimum version:

[cols="1,1"]
|===
| Add-on Name | Minimum Required Version

| Amazon VPC CNI plugin for Kubernetes
| v1.19.0-eksbuild.1

| Kube-proxy 
a|
* v1.25.16-eksbuild.22
* v1.26.15-eksbuild.19 
* v1.27.16-eksbuild.14
* v1.28.15-eksbuild.4
* v1.29.10-eksbuild.3
* v1.30.6-eksbuild.3
* v1.31.2-eksbuild.3 

| Amazon EBS CSI driver
| v1.37.0-eksbuild.1

| CSI snapshot controller
| v8.1.0-eksbuild.2

| EKS Pod Identity Agent
| v1.3.4-eksbuild.1

|===

For more information, see <<updating-an-add-on>>.

== Next Steps

* To migrate Manage Node Group workloads, see <<auto-migrate-mng>>.
* To migrate from Self-Managed Karpenter, see <<auto-migrate-karpenter>>.


📝 https://github.com/search?q=repo:awsdocs/amazon-eks-user-guide+&#91;&#91;auto-enable-existing,&type=code[Edit this page on GitHub]