//!!NODE_ROOT <section>
include::../attributes.txt[]

[.topic]
[[creating-resources-with-cloudformation,creating-resources-with-cloudformation.title]]
= Create Amazon EKS resources with {aws} CloudFormation
:info_doctype: section
:info_title: Create Amazon EKS resources with \
            {aws} CloudFormation
:info_abstract: Learn about how to create resources for Amazon EKS using an {aws} CloudFormation \
                template.

[abstract]
--
Learn about how to create resources for Amazon EKS using an {aws} CloudFormation template.
--

Amazon EKS is integrated with {aws} CloudFormation, a service that helps you model and set up your {aws} resources so that you can spend less time creating and managing your resources and infrastructure. You create a template that describes all the {aws} resources that you want, for example an Amazon EKS cluster, and {aws} CloudFormation takes care of provisioning and configuring those resources for you.  

When you use {aws} CloudFormation, you can reuse your template to set up your Amazon EKS resources consistently and repeatedly. Just describe your resources once, and then provision the same resources over and over in multiple {aws} accounts and Regions.

[[working-with-templates,working-with-templates.title]]
== Amazon EKS and {aws} CloudFormation templates

To provision and configure resources for Amazon EKS and related services, you must understand link:AWSCloudFormation/latest/UserGuide/template-guide.html[{aws} CloudFormation templates,type="documentation"]. Templates are formatted text files in JSON or YAML. These templates describe the resources that you want to provision in your {aws} CloudFormation stacks. If you're unfamiliar with JSON or YAML, you can use {aws} CloudFormation Designer to help you get started with {aws} CloudFormation templates. For more information, see link:AWSCloudFormation/latest/UserGuide/working-with-templates-cfn-designer.html[What is {aws} CloudFormation Designer?,type="documentation"] in the _{aws} CloudFormation User Guide_.

Amazon EKS supports creating clusters and node groups in {aws} CloudFormation. For more information, including examples of JSON and YAML templates for your Amazon EKS resources, see  link:AWSCloudFormation/latest/UserGuide/AWS_EKS.html[Amazon EKS resource type reference,type="documentation"] in the _{aws} CloudFormation User Guide_.

[[learn-more-cloudformation,learn-more-cloudformation.title]]
== Learn more about {aws} CloudFormation

To learn more about {aws} CloudFormation, see the following resources:



* link:cloudformation/[{aws} CloudFormation,type="marketing"]
* link:AWSCloudFormation/latest/UserGuide/Welcome.html[{aws} CloudFormation User Guide,type="documentation"]
* link:cloudformation-cli/latest/userguide/what-is-cloudformation-cli.html[{aws} CloudFormation Command Line Interface User Guide,type="documentation"]


📝 https://github.com/search?q=repo:awsdocs/amazon-eks-user-guide+&#91;&#91;creating-resources-with-cloudformation,&type=code[Edit this page on GitHub]