//!!NODE_ROOT <section>
include::../attributes.txt[]

[.topic]
[[fsx-ontap,fsx-ontap.title]]
= Store high-performance apps with FSx for NetApp ONTAP
:info_doctype: section
:info_title: Store high-performance apps with FSx for NetApp ONTAP
:info_titleabbrev: Amazon FSx for NetApp ONTAP
:keywords: Amazon FSx for NetApp ONTAP CSI driver, storage
:info_abstract: NetApp's \
                Astra Trident allows Amazon EKS clusters to manage the lifecycle of \
                persistent volumes (PVs) backed by Amazon FSx for NetApp ONTAP file systems.

[abstract]
--
[.noloc]`NetApp's` [.noloc]`Astra Trident` allows Amazon EKS clusters to manage the lifecycle of persistent volumes (PVs) backed by Amazon FSx for NetApp ONTAP file systems.
--

[.noloc]`NetApp's` [.noloc]`Astra Trident` provides dynamic storage orchestration using a Container Storage Interface (CSI) compliant driver. This allows Amazon EKS clusters to manage the lifecycle of persistent volumes (PVs) backed by Amazon FSx for NetApp ONTAP file systems. To get started, see https://docs.netapp.com/us-en/trident/trident-use/trident-fsx.html[Use Astra Trident with Amazon FSx for NetApp ONTAP] in the [.noloc]`Astra Trident` documentation.

Amazon FSx for NetApp ONTAP is a storage service that allows you to launch and run fully managed [.noloc]`ONTAP` file systems in the cloud. [.noloc]`ONTAP` is [.noloc]`NetApp's` file system technology that provides a widely adopted set of data access and data management capabilities. FSx for ONTAP provides the features, performance, and APIs of on-premises [.noloc]`NetApp` file systems with the agility, scalability, and simplicity of a fully managed {aws} service. For more information, see the link:fsx/latest/ONTAPGuide/what-is-fsx-ontap.html[FSx for ONTAP User Guide,type="documentation"].